/*
 * Copyright (c) 2025, nucleon <https://github.com/nucleon>
 * Copyright (c) 2025, Cooper Morris <https://github.com/coopermor>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.nucleon.porttasks.enums;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.NpcID;

public enum BountyTaskData
{
	PORT_SARIM_TERN_BOUNTY_438(438, PortLocation.PORT_SARIM, "Port sarim tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	PORT_SARIM_MOGRE_BOUNTY_439(439, PortLocation.PORT_SARIM, "Port sarim mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 5, 2),
	PORT_SARIM_BULL_SHARK_BOUNTY_440(440, PortLocation.PORT_SARIM, "Port sarim bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 4, 2),
	PORT_SARIM_TIGER_SHARK_BOUNTY_441(441, PortLocation.PORT_SARIM, "Port sarim tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 6, 2),
	PORT_SARIM_OSPREY_BOUNTY_442(442, PortLocation.PORT_SARIM, "Port sarim osprey bounty", ItemID.SAILING_OSPREY_BEAK, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 1, 10),
	PORT_SARIM_BULL_SHARK_BOUNTY_443(443, PortLocation.PORT_SARIM, "Port sarim bull shark bounty", ItemID.SAILING_BULL_SHARK_LIVER, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 1, 10),
	PORT_SARIM_PYGMY_KRAKEN_BOUNTY_444(444, PortLocation.PORT_SARIM, "Port sarim pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_INK_SAC, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 1, 10),
	PANDEMONIUM_BULL_SHARK_BOUNTY_445(445, PortLocation.PANDEMONIUM, "Pandemonium bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PANDEMONIUM_MOGRE_BOUNTY_446(446, PortLocation.PANDEMONIUM, "Pandemonium mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 5, 2),
	PANDEMONIUM_OSPREY_BOUNTY_447(447, PortLocation.PANDEMONIUM, "Pandemonium osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	PANDEMONIUM_BUTTERFLY_RAY_BOUNTY_448(448, PortLocation.PANDEMONIUM, "Pandemonium butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	PANDEMONIUM_TERN_BOUNTY_449(449, PortLocation.PANDEMONIUM, "Pandemonium tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	PANDEMONIUM_HAMMERHEAD_SHARK_BOUNTY_450(450, PortLocation.PANDEMONIUM, "Pandemonium hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	PANDEMONIUM_FRIGATEBIRD_BOUNTY_451(451, PortLocation.PANDEMONIUM, "Pandemonium frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	MUSA_POINT_BULL_SHARK_BOUNTY_452(452, PortLocation.MUSA_POINT, "Musa point bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 5, 2),
	MUSA_POINT_MOGRE_BOUNTY_453(453, PortLocation.MUSA_POINT, "Musa point mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 5, 2),
	MUSA_POINT_TERN_BOUNTY_454(454, PortLocation.MUSA_POINT, "Musa point tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	MUSA_POINT_BUTTERFLY_RAY_BOUNTY_455(455, PortLocation.MUSA_POINT, "Musa point butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	MUSA_POINT_EAGLE_RAY_BOUNTY_456(456, PortLocation.MUSA_POINT, "Musa point eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	MUSA_POINT_BULL_SHARK_BOUNTY_457(457, PortLocation.MUSA_POINT, "Musa point bull shark bounty", ItemID.SAILING_BULL_SHARK_LIVER, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 1, 10),
	MUSA_POINT_HAMMERHEAD_SHARK_BOUNTY_458(458, PortLocation.MUSA_POINT, "Musa point hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	CATHERBY_TERN_BOUNTY_459(459, PortLocation.CATHERBY, "Catherby tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	CATHERBY_OSPREY_BOUNTY_460(460, PortLocation.CATHERBY, "Catherby osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	CATHERBY_BULL_SHARK_BOUNTY_461(461, PortLocation.CATHERBY, "Catherby bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 4, 2),
	CATHERBY_PYGMY_KRAKEN_BOUNTY_462(462, PortLocation.CATHERBY, "Catherby pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 5, 2),
	CATHERBY_MOGRE_BOUNTY_463(463, PortLocation.CATHERBY, "Catherby mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	CATHERBY_FRIGATEBIRD_BOUNTY_464(464, PortLocation.CATHERBY, "Catherby frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	CATHERBY_ALBATROSS_BOUNTY_465(465, PortLocation.CATHERBY, "Catherby albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	TBRIMHAVEN_OSPREY_BOUNTY_466(466, PortLocation.BRIMHAVEN, "Brimhaven osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	TBRIMHAVEN_TERN_BOUNTY_467(467, PortLocation.BRIMHAVEN, "Brimhaven tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	TBRIMHAVEN_BULL_SHARK_BOUNTY_468(468, PortLocation.BRIMHAVEN, "Brimhaven bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 5, 2),
	TBRIMHAVEN_ALBATROSS_BOUNTY_469(469, PortLocation.BRIMHAVEN, "Brimhaven albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 5, 2),
	TBRIMHAVEN_HAMMERHEAD_SHARK_BOUNTY_470(470, PortLocation.BRIMHAVEN, "Brimhaven hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	TBRIMHAVEN_TIGER_SHARK_BOUNTY_471(471, PortLocation.BRIMHAVEN, "Brimhaven tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	TBRIMHAVEN_MOGRE_BOUNTY_472(472, PortLocation.BRIMHAVEN, "Brimhaven mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	ARDOUGNE_MOGRE_BOUNTY_473(473, PortLocation.ARDOUGNE, "Ardougne mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 5, 2),
	ARDOUGNE_OSPREY_BOUNTY_474(474, PortLocation.ARDOUGNE, "Ardougne osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	ARDOUGNE_BULL_SHARK_BOUNTY_475(475, PortLocation.ARDOUGNE, "Ardougne bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 5, 2),
	ARDOUGNE_PYGMY_KRAKEN_BOUNTY_476(476, PortLocation.ARDOUGNE, "Ardougne pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	ARDOUGNE_HAMMERHEAD_SHARK_BOUNTY_477(477, PortLocation.ARDOUGNE, "Ardougne hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	ARDOUGNE_STINGRAY_BOUNTY_478(478, PortLocation.ARDOUGNE, "Ardougne stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	ARDOUGNE_SPINED_KRAKEN_BOUNTY_479(479, PortLocation.ARDOUGNE, "Ardougne spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	PORT_KHAZARD_MOGRE_BOUNTY_480(480, PortLocation.PORT_KHAZARD, "Port khazard mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	PORT_KHAZARD_BULL_SHARK_BOUNTY_481(481, PortLocation.PORT_KHAZARD, "Port khazard bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PORT_KHAZARD_HAMMERHEAD_SHARK_BOUNTY_482(482, PortLocation.PORT_KHAZARD, "Port khazard hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 5, 2),
	PORT_KHAZARD_GREAT_WHITE_SHARK_BOUNTY_483(483, PortLocation.PORT_KHAZARD, "Port khazard great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	PORT_KHAZARD_MOGRE_BOUNTY_484(484, PortLocation.PORT_KHAZARD, "Port khazard mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	PORT_KHAZARD_EAGLE_RAY_BOUNTY_485(485, PortLocation.PORT_KHAZARD, "Port khazard eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	PORT_KHAZARD_ALBATROSS_BOUNTY_486(486, PortLocation.PORT_KHAZARD, "Port khazard albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	CORSAIR_COVE_HAMMERHEAD_SHARK_BOUNTY_487(487, PortLocation.CORSAIR_COVE, "Corsair cove hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 5, 2),
	CORSAIR_COVE_PYGMY_KRAKEN_BOUNTY_488(488, PortLocation.CORSAIR_COVE, "Corsair cove pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	CORSAIR_COVE_MOGRE_BOUNTY_489(489, PortLocation.CORSAIR_COVE, "Corsair cove mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 4, 2),
	CORSAIR_COVE_STINGRAY_BOUNTY_490(490, PortLocation.CORSAIR_COVE, "Corsair cove stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 4, 2),
	CORSAIR_COVE_OSPREY_BOUNTY_491(491, PortLocation.CORSAIR_COVE, "Corsair cove osprey bounty", ItemID.SAILING_OSPREY_BEAK, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 1, 10),
	CORSAIR_COVE_TIGER_SHARK_BOUNTY_492(492, PortLocation.CORSAIR_COVE, "Corsair cove tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	CORSAIR_COVE_GREAT_WHITE_SHARK_BOUNTY_493(493, PortLocation.CORSAIR_COVE, "Corsair cove great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	RUINS_OF_UNKAH_BULL_SHARK_BOUNTY_494(494, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 4, 2),
	RUINS_OF_UNKAH_HAMMERHEAD_SHARK_BOUNTY_495(495, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 5, 2),
	RUINS_OF_UNKAH_TIGER_SHARK_BOUNTY_496(496, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 3, 3),
	RUINS_OF_UNKAH_BUTTERFLY_RAY_BOUNTY_497(497, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	RUINS_OF_UNKAH_EAGLE_RAY_BOUNTY_498(498, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	RUINS_OF_UNKAH_ALBATROSS_BOUNTY_499(499, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	RUINS_OF_UNKAH_GREAT_WHITE_SHARK_BOUNTY_500(500, PortLocation.RUINS_OF_UNKAH, "Ruins of unkah great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_STINGRAY_BOUNTY_501(501, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 6, 2),
	VOID_KNIGHTS_OUTPOST_OSPREY_BOUNTY_502(502, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 5, 2),
	VOID_KNIGHTS_OUTPOST_FRIGATEBIRD_BOUNTY_503(503, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 4, 2),
	VOID_KNIGHTS_OUTPOST_PYGMY_KRAKEN_BOUNTY_504(504, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 3, 3),
	VOID_KNIGHTS_OUTPOST_EAGLE_RAY_BOUNTY_505(505, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_GREAT_WHITE_SHARK_BOUNTY_506(506, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_MANTA_RAY_BOUNTY_507(507, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	SUMMER_SHORE_BUTTERFLY_RAY_BOUNTY_508(508, PortLocation.SUMMER_SHORE, "Summer shore butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	SUMMER_SHORE_EAGLE_RAY_BOUNTY_509(509, PortLocation.SUMMER_SHORE, "Summer shore eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 4, 2),
	SUMMER_SHORE_FRIGATEBIRD_BOUNTY_510(510, PortLocation.SUMMER_SHORE, "Summer shore frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 3, 3),
	SUMMER_SHORE_GREAT_WHITE_SHARK_BOUNTY_511(511, PortLocation.SUMMER_SHORE, "Summer shore great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	SUMMER_SHORE_ALBATROSS_BOUNTY_512(512, PortLocation.SUMMER_SHORE, "Summer shore albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	SUMMER_SHORE_TIGER_SHARK_BOUNTY_513(513, PortLocation.SUMMER_SHORE, "Summer shore tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	SUMMER_SHORE_STINGRAY_BOUNTY_514(514, PortLocation.SUMMER_SHORE, "Summer shore stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	RED_ROCK_TIGER_SHARK_BOUNTY_515(515, PortLocation.RED_ROCK, "Red rock tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 5, 2),
	RED_ROCK_FRIGATEBIRD_BOUNTY_516(516, PortLocation.RED_ROCK, "Red rock frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 4, 2),
	RED_ROCK_EAGLE_RAY_BOUNTY_517(517, PortLocation.RED_ROCK, "Red rock eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 5, 2),
	RED_ROCK_GREAT_WHITE_SHARK_BOUNTY_518(518, PortLocation.RED_ROCK, "Red rock great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 4, 2),
	RED_ROCK_STINGRAY_BOUNTY_519(519, PortLocation.RED_ROCK, "Red rock stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	RED_ROCK_TIGER_SHARK_BOUNTY_520(520, PortLocation.RED_ROCK, "Red rock tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	RED_ROCK_SPINED_KRAKEN_BOUNTY_521(521, PortLocation.RED_ROCK, "Red rock spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	LANDS_END_BULL_SHARK_BOUNTY_522(522, PortLocation.LANDS_END, "Land's end bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 4, 2),
	LANDS_END_OSPREY_BOUNTY_523(523, PortLocation.LANDS_END, "Land's end osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	LANDS_END_TERN_BOUNTY_524(524, PortLocation.LANDS_END, "Land's end tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	LANDS_END_PYGMY_KRAKEN_BOUNTY_525(525, PortLocation.LANDS_END, "Land's end pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 4, 2),
	LANDS_END_HAMMERHEAD_SHARK_BOUNTY_526(526, PortLocation.LANDS_END, "Land's end hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	LANDS_END_GREAT_WHITE_SHARK_BOUNTY_527(527, PortLocation.LANDS_END, "Land's end great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	LANDS_END_BUTTERFLY_RAY_BOUNTY_528(528, PortLocation.LANDS_END, "Land's end butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_SKIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 1, 10),
	PORT_PISCARILIUS_OSPREY_BOUNTY_529(529, PortLocation.PORT_PISCARILIUS, "Port piscarilius osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	PORT_PISCARILIUS_BULL_SHARK_BOUNTY_530(530, PortLocation.PORT_PISCARILIUS, "Port piscarilius bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PORT_PISCARILIUS_TERN_BOUNTY_531(531, PortLocation.PORT_PISCARILIUS, "Port piscarilius tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	PORT_PISCARILIUS_SPINED_KRAKEN_BOUNTY_532(532, PortLocation.PORT_PISCARILIUS, "Port piscarilius spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_TENTACLE, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 6, 2),
	PORT_PISCARILIUS_TIGER_SHARK_BOUNTY_533(533, PortLocation.PORT_PISCARILIUS, "Port piscarilius tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	PORT_PISCARILIUS_BUTTERFLY_RAY_BOUNTY_534(534, PortLocation.PORT_PISCARILIUS, "Port piscarilius butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_SKIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 1, 10),
	PORT_PISCARILIUS_ARMOURED_KRAKEN_BOUNTY_535(535, PortLocation.PORT_PISCARILIUS, "Port piscarilius armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_INK_SAC, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_OSPREY_BOUNTY_536(536, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	CIVITAS_ILLA_FORTIS_HAMMERHEAD_SHARK_BOUNTY_537(537, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	CIVITAS_ILLA_FORTIS_BULL_SHARK_BOUNTY_538(538, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 5, 2),
	CIVITAS_ILLA_FORTIS_ARMOURED_KRAKEN_BOUNTY_539(539, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 4, 2),
	CIVITAS_ILLA_FORTIS_TERN_BOUNTY_540(540, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_FRIGATEBIRD_BOUNTY_541(541, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_EAGLE_RAY_BOUNTY_542(542, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	ALDARIN_STINGRAY_BOUNTY_543(543, PortLocation.ALDARIN, "Aldarin stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 5, 2),
	ALDARIN_OSPREY_BOUNTY_544(544, PortLocation.ALDARIN, "Aldarin osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 5, 2),
	ALDARIN_BUTTERFLY_RAY_BOUNTY_545(545, PortLocation.ALDARIN, "Aldarin butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	ALDARIN_GREAT_WHITE_SHARK_BOUNTY_546(546, PortLocation.ALDARIN, "Aldarin great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 6, 2),
	ALDARIN_HAMMERHEAD_SHARK_BOUNTY_547(547, PortLocation.ALDARIN, "Aldarin hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	ALDARIN_SPINED_KRAKEN_BOUNTY_548(548, PortLocation.ALDARIN, "Aldarin spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ALDARIN_FRIGATEBIRD_BOUNTY_549(549, PortLocation.ALDARIN, "Aldarin frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	PORT_ROBERTS_HAMMERHEAD_SHARK_BOUNTY_550(550, PortLocation.PORT_ROBERTS, "Port roberts hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	PORT_ROBERTS_OSPREY_BOUNTY_551(551, PortLocation.PORT_ROBERTS, "Port roberts osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 5, 2),
	PORT_ROBERTS_ARMOURED_KRAKEN_BOUNTY_552(552, PortLocation.PORT_ROBERTS, "Port roberts armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 4, 2),
	PORT_ROBERTS_GREAT_WHITE_SHARK_BOUNTY_553(553, PortLocation.PORT_ROBERTS, "Port roberts great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	PORT_ROBERTS_TERN_BOUNTY_554(554, PortLocation.PORT_ROBERTS, "Port roberts tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	PORT_ROBERTS_ORCA_BOUNTY_555(555, PortLocation.PORT_ROBERTS, "Port roberts orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	PORT_ROBERTS_ALBATROSS_BOUNTY_556(556, PortLocation.PORT_ROBERTS, "Port roberts albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	DEEPFIN_POINT_FRIGATEBIRD_BOUNTY_557(557, PortLocation.DEEPFIN_POINT, "Deepfin point frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 6, 2),
	DEEPFIN_POINT_EAGLE_RAY_BOUNTY_558(558, PortLocation.DEEPFIN_POINT, "Deepfin point eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 6, 2),
	DEEPFIN_POINT_SPINED_KRAKEN_BOUNTY_559(559, PortLocation.DEEPFIN_POINT, "Deepfin point spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_TENTACLE, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 6, 2),
	DEEPFIN_POINT_OSPREY_BOUNTY_560(560, PortLocation.DEEPFIN_POINT, "Deepfin point osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	DEEPFIN_POINT_STINGRAY_BOUNTY_561(561, PortLocation.DEEPFIN_POINT, "Deepfin point stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	DEEPFIN_POINT_TIGER_SHARK_BOUNTY_562(562, PortLocation.DEEPFIN_POINT, "Deepfin point tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	DEEPFIN_POINT_HAMMERHEAD_SHARK_BOUNTY_563(563, PortLocation.DEEPFIN_POINT, "Deepfin point hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	PORT_TYRAS_BUTTERFLY_RAY_BOUNTY_564(564, PortLocation.PORT_TYRAS, "Port tyras butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 4, 2),
	PORT_TYRAS_HAMMERHEAD_SHARK_BOUNTY_565(565, PortLocation.PORT_TYRAS, "Port tyras hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 4, 2),
	PORT_TYRAS_BULL_SHARK_BOUNTY_566(566, PortLocation.PORT_TYRAS, "Port tyras bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 6, 2),
	PORT_TYRAS_ARMOURED_KRAKEN_BOUNTY_567(567, PortLocation.PORT_TYRAS, "Port tyras armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 6, 2),
	PORT_TYRAS_PYGMY_KRAKEN_BOUNTY_568(568, PortLocation.PORT_TYRAS, "Port tyras pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_INK_SAC, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 1, 10),
	PORT_TYRAS_GREAT_WHITE_SHARK_BOUNTY_569(569, PortLocation.PORT_TYRAS, "Port tyras great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	PORT_TYRAS_MANTA_RAY_BOUNTY_570(570, PortLocation.PORT_TYRAS, "Port tyras manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	PRIFDDINAS_HAMMERHEAD_SHARK_BOUNTY_571(571, PortLocation.PRIFDDINAS, "Prifddinas hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 5, 2),
	PRIFDDINAS_PYGMY_KRAKEN_BOUNTY_572(572, PortLocation.PRIFDDINAS, "Prifddinas pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	PRIFDDINAS_ARMOURED_KRAKEN_BOUNTY_573(573, PortLocation.PRIFDDINAS, "Prifddinas armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 6, 2),
	PRIFDDINAS_OSPREY_BOUNTY_574(574, PortLocation.PRIFDDINAS, "Prifddinas osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 5, 2),
	PRIFDDINAS_GREAT_WHITE_SHARK_BOUNTY_575(575, PortLocation.PRIFDDINAS, "Prifddinas great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	PRIFDDINAS_MANTA_RAY_BOUNTY_576(576, PortLocation.PRIFDDINAS, "Prifddinas manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	PRIFDDINAS_HAMMERHEAD_SHARK_BOUNTY_577(577, PortLocation.PRIFDDINAS, "Prifddinas hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	RELLEKKA_ALBATROSS_BOUNTY_578(578, PortLocation.RELLEKKA, "Rellekka albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 4, 2),
	RELLEKKA_HAMMERHEAD_SHARK_BOUNTY_579(579, PortLocation.RELLEKKA, "Rellekka hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	RELLEKKA_NARWHAL_BOUNTY_580(580, PortLocation.RELLEKKA, "Rellekka narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 6, 2),
	RELLEKKA_ARMOURED_KRAKEN_BOUNTY_581(581, PortLocation.RELLEKKA, "Rellekka armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 4, 2),
	RELLEKKA_ORCA_BOUNTY_582(582, PortLocation.RELLEKKA, "Rellekka orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	RELLEKKA_VAMPYRE_KRAKEN_BOUNTY_583(583, PortLocation.RELLEKKA, "Rellekka vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_INK_SAC, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 1, 10),
	RELLEKKA_SPINED_KRAKEN_BOUNTY_584(584, PortLocation.RELLEKKA, "Rellekka spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ETCETERIA_ALBATROSS_BOUNTY_585(585, PortLocation.ETCETERIA, "Etceteria albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 4, 2),
	ETCETERIA_ORCA_BOUNTY_586(586, PortLocation.ETCETERIA, "Etceteria orca bounty", ItemID.SAILING_ORCA_BLUBBER, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 5, 2),
	ETCETERIA_VAMPYRE_KRAKEN_BOUNTY_587(587, PortLocation.ETCETERIA, "Etceteria vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_TENTACLE, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 5, 2),
	ETCETERIA_NARWHAL_BOUNTY_588(588, PortLocation.ETCETERIA, "Etceteria narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 4, 2),
	ETCETERIA_SPINED_KRAKEN_BOUNTY_589(589, PortLocation.ETCETERIA, "Etceteria spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ETCETERIA_ORCA_BOUNTY_590(590, PortLocation.ETCETERIA, "Etceteria orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	ETCETERIA_ARMOURED_KRAKEN_BOUNTY_591(591, PortLocation.ETCETERIA, "Etceteria armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_INK_SAC, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 1, 10),
	LUNAR_ISLE_ARMOURED_KRAKEN_BOUNTY_592(592, PortLocation.LUNAR_ISLE, "Lunar isle armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 5, 2),
	LUNAR_ISLE_VAMPYRE_KRAKEN_BOUNTY_593(593, PortLocation.LUNAR_ISLE, "Lunar isle vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_TENTACLE, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 5, 2),
	LUNAR_ISLE_NARWHAL_BOUNTY_594(594, PortLocation.LUNAR_ISLE, "Lunar isle narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 4, 2),
	LUNAR_ISLE_ORCA_BOUNTY_595(595, PortLocation.LUNAR_ISLE, "Lunar isle orca bounty", ItemID.SAILING_ORCA_BLUBBER, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 4, 2),
	LUNAR_ISLE_ALBATROSS_BOUNTY_596(596, PortLocation.LUNAR_ISLE, "Lunar isle albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	LUNAR_ISLE_VAMPYRE_KRAKEN_BOUNTY_597(597, PortLocation.LUNAR_ISLE, "Lunar isle vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_INK_SAC, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 1, 10),
	LUNAR_ISLE_NARWHAL_BOUNTY_598(598, PortLocation.LUNAR_ISLE, "Lunar isle narwhal bounty", ItemID.SAILING_NARWHAL_TUSK, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 1, 10),
	;
	private final int id;
	private final PortLocation bountyLocation;
	public final String taskName;
	public final int itemId;
	public final int npcId;
	private final int deadNpcId;
	public final int itemQuantity;
	public final int itemRarity;

	private static final Set<Integer> VARBIT_VALUES;

	BountyTaskData(int id, PortLocation bountyLocation, String taskName, int itemId, int npcId, int deadNpcId, int itemQuantity, int itemRarity)
	{
		this.id = id;
		this.bountyLocation = bountyLocation;
		this.taskName = taskName;
		this.itemId = itemId;
		this.npcId = npcId;
		this.deadNpcId = deadNpcId;
		this.itemQuantity = itemQuantity;
		this.itemRarity = itemRarity; //
	}

	static
	{
		Set<Integer> varbitValues = new HashSet<>();
		for (BountyTaskData b : values())
		{
			varbitValues.add(b.id);
		}
		VARBIT_VALUES = Collections.unmodifiableSet(varbitValues);
	}

	public static BountyTaskData fromId(int id)
	{
		for (BountyTaskData task : values())
		{
			if (task.id == id)
				return task;
		}
		return null;
	}

	public static boolean isBountyTask(int id)
	{
		return VARBIT_VALUES.contains(id);
	}
}
