/*
 * Copyright (c) 2025, nucleon <https://github.com/nucleon>
 * Copyright (c) 2025, Cooper Morris <https://github.com/coopermor>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.nucleon.porttasks.enums;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.NpcID;

public enum BountyTaskData
{
	PORT_SARIM_TERN_BOUNTY_438(9101, 438, PortLocation.PORT_SARIM, "Port Sarim tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	PORT_SARIM_MOGRE_BOUNTY_439(9102, 439, PortLocation.PORT_SARIM, "Port Sarim mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	PORT_SARIM_BULL_SHARK_BOUNTY_440(9103, 440, PortLocation.PORT_SARIM, "Port Sarim bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PORT_SARIM_TIGER_SHARK_BOUNTY_441(9104, 441, PortLocation.PORT_SARIM, "Port Sarim tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 5, 2),
	PORT_SARIM_OSPREY_BOUNTY_442(9105, 442, PortLocation.PORT_SARIM, "Port Sarim osprey bounty", ItemID.SAILING_OSPREY_BEAK, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 1, 10),
	PORT_SARIM_BULL_SHARK_BOUNTY_443(9106, 443, PortLocation.PORT_SARIM, "Port Sarim bull shark bounty", ItemID.SAILING_BULL_SHARK_LIVER, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 1, 10),
	PORT_SARIM_PYGMY_KRAKEN_BOUNTY_444(9107, 444, PortLocation.PORT_SARIM, "Port Sarim pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_INK_SAC, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 1, 10),
	PANDEMONIUM_BULL_SHARK_BOUNTY_445(9108, 445, PortLocation.PANDEMONIUM, "Pandemonium bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PANDEMONIUM_MOGRE_BOUNTY_446(9109, 446, PortLocation.PANDEMONIUM, "Pandemonium mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	PANDEMONIUM_OSPREY_BOUNTY_447(9110, 447, PortLocation.PANDEMONIUM, "Pandemonium osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	PANDEMONIUM_BUTTERFLY_RAY_BOUNTY_448(9111, 448, PortLocation.PANDEMONIUM, "Pandemonium butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	PANDEMONIUM_TERN_BOUNTY_449(9112, 449, PortLocation.PANDEMONIUM, "Pandemonium tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	PANDEMONIUM_HAMMERHEAD_SHARK_BOUNTY_450(9113, 450, PortLocation.PANDEMONIUM, "Pandemonium hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	PANDEMONIUM_FRIGATEBIRD_BOUNTY_451(9114, 451, PortLocation.PANDEMONIUM, "Pandemonium frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	MUSA_POINT_BULL_SHARK_BOUNTY_452(9115, 452, PortLocation.MUSA_POINT, "Musa Point bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	MUSA_POINT_MOGRE_BOUNTY_453(9116, 453, PortLocation.MUSA_POINT, "Musa Point mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	MUSA_POINT_TERN_BOUNTY_454(9117, 454, PortLocation.MUSA_POINT, "Musa Point tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	MUSA_POINT_BUTTERFLY_RAY_BOUNTY_455(9118, 455, PortLocation.MUSA_POINT, "Musa Point butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 3, 3),
	MUSA_POINT_EAGLE_RAY_BOUNTY_456(9119, 456, PortLocation.MUSA_POINT, "Musa Point eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	MUSA_POINT_BULL_SHARK_BOUNTY_457(9120, 457, PortLocation.MUSA_POINT, "Musa Point bull shark bounty", ItemID.SAILING_BULL_SHARK_LIVER, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 1, 10),
	MUSA_POINT_HAMMERHEAD_SHARK_BOUNTY_458(9121, 458, PortLocation.MUSA_POINT, "Musa Point hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	CATHERBY_TERN_BOUNTY_459(9122, 459, PortLocation.CATHERBY, "Catherby tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	CATHERBY_OSPREY_BOUNTY_460(9123, 460, PortLocation.CATHERBY, "Catherby osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	CATHERBY_BULL_SHARK_BOUNTY_461(9124, 461, PortLocation.CATHERBY, "Catherby bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	CATHERBY_PYGMY_KRAKEN_BOUNTY_462(9125, 462, PortLocation.CATHERBY, "Catherby pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	CATHERBY_MOGRE_BOUNTY_463(9126, 463, PortLocation.CATHERBY, "Catherby mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	CATHERBY_FRIGATEBIRD_BOUNTY_464(9127, 464, PortLocation.CATHERBY, "Catherby frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	CATHERBY_ALBATROSS_BOUNTY_465(9128, 465, PortLocation.CATHERBY, "Catherby albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	BRIMHAVEN_OSPREY_BOUNTY_466(9129, 466, PortLocation.BRIMHAVEN, "Brimhaven osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	BRIMHAVEN_TERN_BOUNTY_467(9130, 467, PortLocation.BRIMHAVEN, "Brimhaven tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	BRIMHAVEN_BULL_SHARK_BOUNTY_468(9131, 468, PortLocation.BRIMHAVEN, "Brimhaven bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	BRIMHAVEN_ALBATROSS_BOUNTY_469(9132, 469, PortLocation.BRIMHAVEN, "Brimhaven albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 4, 2),
	BRIMHAVEN_HAMMERHEAD_SHARK_BOUNTY_470(9133, 470, PortLocation.BRIMHAVEN, "Brimhaven hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	BRIMHAVEN_TIGER_SHARK_BOUNTY_471(9134, 471, PortLocation.BRIMHAVEN, "Brimhaven tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	BRIMHAVEN_MOGRE_BOUNTY_472(9135, 472, PortLocation.BRIMHAVEN, "Brimhaven mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	ARDOUGNE_MOGRE_BOUNTY_473(9136, 473, PortLocation.ARDOUGNE, "Ardougne mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	ARDOUGNE_OSPREY_BOUNTY_474(9137, 474, PortLocation.ARDOUGNE, "Ardougne osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	ARDOUGNE_BULL_SHARK_BOUNTY_475(9138, 475, PortLocation.ARDOUGNE, "Ardougne bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	ARDOUGNE_PYGMY_KRAKEN_BOUNTY_476(9139, 476, PortLocation.ARDOUGNE, "Ardougne pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	ARDOUGNE_HAMMERHEAD_SHARK_BOUNTY_477(9140, 477, PortLocation.ARDOUGNE, "Ardougne hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	ARDOUGNE_STINGRAY_BOUNTY_478(9141, 478, PortLocation.ARDOUGNE, "Ardougne stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	ARDOUGNE_SPINED_KRAKEN_BOUNTY_479(9142, 479, PortLocation.ARDOUGNE, "Ardougne spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	PORT_KHAZARD_MOGRE_BOUNTY_480(9143, 480, PortLocation.PORT_KHAZARD, "Port Khazard mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	PORT_KHAZARD_BULL_SHARK_BOUNTY_481(9144, 481, PortLocation.PORT_KHAZARD, "Port Khazard bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PORT_KHAZARD_HAMMERHEAD_SHARK_BOUNTY_482(9145, 482, PortLocation.PORT_KHAZARD, "Port Khazard hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	PORT_KHAZARD_GREAT_WHITE_SHARK_BOUNTY_483(9146, 483, PortLocation.PORT_KHAZARD, "Port Khazard great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	PORT_KHAZARD_MOGRE_BOUNTY_484(9147, 484, PortLocation.PORT_KHAZARD, "Port Khazard mogre bounty", ItemID.SAILING_SEA_MOGRE_HEAD, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 1, 10),
	PORT_KHAZARD_EAGLE_RAY_BOUNTY_485(9148, 485, PortLocation.PORT_KHAZARD, "Port Khazard eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	PORT_KHAZARD_ALBATROSS_BOUNTY_486(9149, 486, PortLocation.PORT_KHAZARD, "Port Khazard albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	CORSAIR_COVE_HAMMERHEAD_SHARK_BOUNTY_487(9150, 487, PortLocation.CORSAIR_COVE, "Corsair Cove hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	CORSAIR_COVE_PYGMY_KRAKEN_BOUNTY_488(9151, 488, PortLocation.CORSAIR_COVE, "Corsair Cove pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 3, 3),
	CORSAIR_COVE_MOGRE_BOUNTY_489(9152, 489, PortLocation.CORSAIR_COVE, "Corsair Cove mogre bounty", ItemID.SAILING_SEA_MOGRE_MACE, NpcID.SAILING_SEA_MOGRE, NpcID.SAILING_SEA_MOGRE_DEAD, 3, 3),
	CORSAIR_COVE_STINGRAY_BOUNTY_490(9153, 490, PortLocation.CORSAIR_COVE, "Corsair Cove stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 5, 2),
	CORSAIR_COVE_OSPREY_BOUNTY_491(9154, 491, PortLocation.CORSAIR_COVE, "Corsair Cove osprey bounty", ItemID.SAILING_OSPREY_BEAK, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 1, 10),
	CORSAIR_COVE_TIGER_SHARK_BOUNTY_492(9155, 492, PortLocation.CORSAIR_COVE, "Corsair Cove tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	CORSAIR_COVE_GREAT_WHITE_SHARK_BOUNTY_493(9156, 493, PortLocation.CORSAIR_COVE, "Corsair Cove great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	RUINS_OF_UNKAH_BULL_SHARK_BOUNTY_494(9157, 494, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	RUINS_OF_UNKAH_HAMMERHEAD_SHARK_BOUNTY_495(9158, 495, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 5, 2),
	RUINS_OF_UNKAH_TIGER_SHARK_BOUNTY_496(9159, 496, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 4, 2),
	RUINS_OF_UNKAH_BUTTERFLY_RAY_BOUNTY_497(9160, 497, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 4, 2),
	RUINS_OF_UNKAH_EAGLE_RAY_BOUNTY_498(9161, 498, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	RUINS_OF_UNKAH_ALBATROSS_BOUNTY_499(9162, 499, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	RUINS_OF_UNKAH_GREAT_WHITE_SHARK_BOUNTY_500(9163, 500, PortLocation.RUINS_OF_UNKAH, "Ruins of Unkah great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_STINGRAY_BOUNTY_501(9164, 501, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 4, 2),
	VOID_KNIGHTS_OUTPOST_OSPREY_BOUNTY_502(9165, 502, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 5, 2),
	VOID_KNIGHTS_OUTPOST_FRIGATEBIRD_BOUNTY_503(9166, 503, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 3, 3),
	VOID_KNIGHTS_OUTPOST_PYGMY_KRAKEN_BOUNTY_504(9167, 504, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	VOID_KNIGHTS_OUTPOST_EAGLE_RAY_BOUNTY_505(9168, 505, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_GREAT_WHITE_SHARK_BOUNTY_506(9169, 506, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	VOID_KNIGHTS_OUTPOST_MANTA_RAY_BOUNTY_507(9170, 507, PortLocation.VOID_KNIGHTS_OUTPOST, "Void Knights' Outpost manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	SUMMER_SHORE_BUTTERFLY_RAY_BOUNTY_508(9171, 508, PortLocation.SUMMER_SHORE, "Summer Shore butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 5, 2),
	SUMMER_SHORE_EAGLE_RAY_BOUNTY_509(9172, 509, PortLocation.SUMMER_SHORE, "Summer Shore eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 5, 2),
	SUMMER_SHORE_FRIGATEBIRD_BOUNTY_510(9173, 510, PortLocation.SUMMER_SHORE, "Summer Shore frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 3, 3),
	SUMMER_SHORE_GREAT_WHITE_SHARK_BOUNTY_511(9174, 511, PortLocation.SUMMER_SHORE, "Summer Shore great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	SUMMER_SHORE_ALBATROSS_BOUNTY_512(9175, 512, PortLocation.SUMMER_SHORE, "Summer Shore albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	SUMMER_SHORE_TIGER_SHARK_BOUNTY_513(9176, 513, PortLocation.SUMMER_SHORE, "Summer Shore tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	SUMMER_SHORE_STINGRAY_BOUNTY_514(9177, 514, PortLocation.SUMMER_SHORE, "Summer Shore stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	RED_ROCK_TIGER_SHARK_BOUNTY_515(9178, 515, PortLocation.RED_ROCK, "Red Rock tiger shark bounty", ItemID.SAILING_TIGER_SHARK_JAW, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 4, 2),
	RED_ROCK_FRIGATEBIRD_BOUNTY_516(9179, 516, PortLocation.RED_ROCK, "Red Rock frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 3, 3),
	RED_ROCK_EAGLE_RAY_BOUNTY_517(9180, 517, PortLocation.RED_ROCK, "Red Rock eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 5, 2),
	RED_ROCK_GREAT_WHITE_SHARK_BOUNTY_518(9181, 518, PortLocation.RED_ROCK, "Red Rock great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 6, 2),
	RED_ROCK_STINGRAY_BOUNTY_519(9182, 519, PortLocation.RED_ROCK, "Red Rock stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	RED_ROCK_TIGER_SHARK_BOUNTY_520(9183, 520, PortLocation.RED_ROCK, "Red Rock tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	RED_ROCK_SPINED_KRAKEN_BOUNTY_521(9184, 521, PortLocation.RED_ROCK, "Red Rock spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	LANDS_END_BULL_SHARK_BOUNTY_522(9185, 522, PortLocation.LANDS_END, "Land's End bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	LANDS_END_OSPREY_BOUNTY_523(9186, 523, PortLocation.LANDS_END, "Land's End osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	LANDS_END_TERN_BOUNTY_524(9187, 524, PortLocation.LANDS_END, "Land's End tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	LANDS_END_PYGMY_KRAKEN_BOUNTY_525(9188, 525, PortLocation.LANDS_END, "Land's End pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 3, 3),
	LANDS_END_HAMMERHEAD_SHARK_BOUNTY_526(9189, 526, PortLocation.LANDS_END, "Land's End hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	LANDS_END_GREAT_WHITE_SHARK_BOUNTY_527(9190, 527, PortLocation.LANDS_END, "Land's End great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	LANDS_END_BUTTERFLY_RAY_BOUNTY_528(9191, 528, PortLocation.LANDS_END, "Land's End butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_SKIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 1, 10),
	PORT_PISCARILIUS_OSPREY_BOUNTY_529(9192, 529, PortLocation.PORT_PISCARILIUS, "Port Piscarilius osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	PORT_PISCARILIUS_BULL_SHARK_BOUNTY_530(9193, 530, PortLocation.PORT_PISCARILIUS, "Port Piscarilius bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 3, 3),
	PORT_PISCARILIUS_TERN_BOUNTY_531(9194, 531, PortLocation.PORT_PISCARILIUS, "Port Piscarilius tern bounty", ItemID.SAILING_TERN_FEATHER, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 3, 3),
	PORT_PISCARILIUS_SPINED_KRAKEN_BOUNTY_532(9195, 532, PortLocation.PORT_PISCARILIUS, "Port Piscarilius spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_TENTACLE, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 4, 2),
	PORT_PISCARILIUS_TIGER_SHARK_BOUNTY_533(9196, 533, PortLocation.PORT_PISCARILIUS, "Port Piscarilius tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	PORT_PISCARILIUS_BUTTERFLY_RAY_BOUNTY_534(9197, 534, PortLocation.PORT_PISCARILIUS, "Port Piscarilius butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_SKIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 1, 10),
	PORT_PISCARILIUS_ARMOURED_KRAKEN_BOUNTY_535(9198, 535, PortLocation.PORT_PISCARILIUS, "Port Piscarilius armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_INK_SAC, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_OSPREY_BOUNTY_536(9199, 536, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	CIVITAS_ILLA_FORTIS_HAMMERHEAD_SHARK_BOUNTY_537(9200, 537, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 4, 2),
	CIVITAS_ILLA_FORTIS_BULL_SHARK_BOUNTY_538(9201, 538, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 4, 2),
	CIVITAS_ILLA_FORTIS_ARMOURED_KRAKEN_BOUNTY_539(9202, 539, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 5, 2),
	CIVITAS_ILLA_FORTIS_TERN_BOUNTY_540(9203, 540, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_FRIGATEBIRD_BOUNTY_541(9204, 541, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	CIVITAS_ILLA_FORTIS_EAGLE_RAY_BOUNTY_542(9205, 542, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa Fortis eagle ray bounty", ItemID.SAILING_EAGLE_RAY_SKIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 1, 10),
	ALDARIN_STINGRAY_BOUNTY_543(9206, 543, PortLocation.ALDARIN, "Aldarin stingray bounty", ItemID.SAILING_STINGRAY_FIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 4, 2),
	ALDARIN_OSPREY_BOUNTY_544(9207, 544, PortLocation.ALDARIN, "Aldarin osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	ALDARIN_BUTTERFLY_RAY_BOUNTY_545(9208, 545, PortLocation.ALDARIN, "Aldarin butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 5, 2),
	ALDARIN_GREAT_WHITE_SHARK_BOUNTY_546(9209, 546, PortLocation.ALDARIN, "Aldarin great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 6, 2),
	ALDARIN_HAMMERHEAD_SHARK_BOUNTY_547(9210, 547, PortLocation.ALDARIN, "Aldarin hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	ALDARIN_SPINED_KRAKEN_BOUNTY_548(9211, 548, PortLocation.ALDARIN, "Aldarin spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ALDARIN_FRIGATEBIRD_BOUNTY_549(9212, 549, PortLocation.ALDARIN, "Aldarin frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_BEAK, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 1, 10),
	PORT_ROBERTS_HAMMERHEAD_SHARK_BOUNTY_550(9213, 550, PortLocation.PORT_ROBERTS, "Port Roberts hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 3, 3),
	PORT_ROBERTS_OSPREY_BOUNTY_551(9214, 551, PortLocation.PORT_ROBERTS, "Port Roberts osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 3, 3),
	PORT_ROBERTS_ARMOURED_KRAKEN_BOUNTY_552(9215, 552, PortLocation.PORT_ROBERTS, "Port Roberts armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 4, 2),
	PORT_ROBERTS_GREAT_WHITE_SHARK_BOUNTY_553(9216, 553, PortLocation.PORT_ROBERTS, "Port Roberts great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_JAW, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 5, 2),
	PORT_ROBERTS_TERN_BOUNTY_554(9217, 554, PortLocation.PORT_ROBERTS, "Port Roberts tern bounty", ItemID.SAILING_TERN_BEAK, NpcID.SAILING_TERN, NpcID.SAILING_TERN_DEAD, 1, 10),
	PORT_ROBERTS_ORCA_BOUNTY_555(9218, 555, PortLocation.PORT_ROBERTS, "Port Roberts orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	PORT_ROBERTS_ALBATROSS_BOUNTY_556(9219, 556, PortLocation.PORT_ROBERTS, "Port Roberts albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	DEEPFIN_POINT_FRIGATEBIRD_BOUNTY_557(9220, 557, PortLocation.DEEPFIN_POINT, "Deepfin Point frigatebird bounty", ItemID.SAILING_FRIGATEBIRD_FEATHER, NpcID.SAILING_FRIGATEBIRD, NpcID.SAILING_FRIGATEBIRD_DEAD, 4, 2),
	DEEPFIN_POINT_EAGLE_RAY_BOUNTY_558(9221, 558, PortLocation.DEEPFIN_POINT, "Deepfin Point eagle ray bounty", ItemID.SAILING_EAGLE_RAY_FIN, NpcID.SAILING_EAGLE_RAY, NpcID.SAILING_EAGLE_RAY_DEAD, 5, 2),
	DEEPFIN_POINT_SPINED_KRAKEN_BOUNTY_559(9222, 559, PortLocation.DEEPFIN_POINT, "Deepfin Point spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_TENTACLE, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 5, 2),
	DEEPFIN_POINT_OSPREY_BOUNTY_560(9223, 560, PortLocation.DEEPFIN_POINT, "Deepfin Point osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 4, 2),
	DEEPFIN_POINT_STINGRAY_BOUNTY_561(9224, 561, PortLocation.DEEPFIN_POINT, "Deepfin Point stingray bounty", ItemID.SAILING_STINGRAY_SKIN, NpcID.SAILING_STINGRAY, NpcID.SAILING_STINGRAY_DEAD, 1, 10),
	DEEPFIN_POINT_TIGER_SHARK_BOUNTY_562(9225, 562, PortLocation.DEEPFIN_POINT, "Deepfin Point tiger shark bounty", ItemID.SAILING_TIGER_SHARK_LIVER, NpcID.SAILING_TIGER_SHARK, NpcID.SAILING_TIGER_SHARK_DEAD, 1, 10),
	DEEPFIN_POINT_HAMMERHEAD_SHARK_BOUNTY_563(9226, 563, PortLocation.DEEPFIN_POINT, "Deepfin Point hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	PORT_TYRAS_BUTTERFLY_RAY_BOUNTY_564(9227, 564, PortLocation.PORT_TYRAS, "Port Tyras butterfly ray bounty", ItemID.SAILING_BUTTERFLY_RAY_FIN, NpcID.SAILING_BUTTERFLY_RAY, NpcID.SAILING_BUTTERFLY_RAY_DEAD, 6, 2),
	PORT_TYRAS_HAMMERHEAD_SHARK_BOUNTY_565(9228, 565, PortLocation.PORT_TYRAS, "Port Tyras hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 6, 2),
	PORT_TYRAS_BULL_SHARK_BOUNTY_566(9229, 566, PortLocation.PORT_TYRAS, "Port Tyras bull shark bounty", ItemID.SAILING_BULL_SHARK_JAW, NpcID.SAILING_BULL_SHARK, NpcID.SAILING_BULL_SHARK_DEAD, 5, 2),
	PORT_TYRAS_ARMOURED_KRAKEN_BOUNTY_567(9230, 567, PortLocation.PORT_TYRAS, "Port Tyras armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 6, 2),
	PORT_TYRAS_PYGMY_KRAKEN_BOUNTY_568(9231, 568, PortLocation.PORT_TYRAS, "Port Tyras pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_INK_SAC, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 1, 10),
	PORT_TYRAS_GREAT_WHITE_SHARK_BOUNTY_569(9232, 569, PortLocation.PORT_TYRAS, "Port Tyras great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	PORT_TYRAS_MANTA_RAY_BOUNTY_570(9233, 570, PortLocation.PORT_TYRAS, "Port Tyras manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	PRIFDDINAS_HAMMERHEAD_SHARK_BOUNTY_571(9234, 571, PortLocation.PRIFDDINAS, "Prifddinas hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 6, 2),
	PRIFDDINAS_PYGMY_KRAKEN_BOUNTY_572(9235, 572, PortLocation.PRIFDDINAS, "Prifddinas pygmy kraken bounty", ItemID.SAILING_PYGMY_KRAKEN_TENTACLE, NpcID.SAILING_PYGMY_KRAKEN, NpcID.SAILING_PYGMY_KRAKEN_DEAD, 6, 2),
	PRIFDDINAS_ARMOURED_KRAKEN_BOUNTY_573(9236, 573, PortLocation.PRIFDDINAS, "Prifddinas armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 6, 2),
	PRIFDDINAS_OSPREY_BOUNTY_574(9237, 574, PortLocation.PRIFDDINAS, "Prifddinas osprey bounty", ItemID.SAILING_OSPREY_FEATHER, NpcID.SAILING_OSPREY, NpcID.SAILING_OSPREY_DEAD, 6, 2),
	PRIFDDINAS_GREAT_WHITE_SHARK_BOUNTY_575(9238, 575, PortLocation.PRIFDDINAS, "Prifddinas great white shark bounty", ItemID.SAILING_GREAT_WHITE_SHARK_LIVER, NpcID.SAILING_GREAT_WHITE_SHARK, NpcID.SAILING_GREAT_WHITE_SHARK_DEAD, 1, 10),
	PRIFDDINAS_MANTA_RAY_BOUNTY_576(9239, 576, PortLocation.PRIFDDINAS, "Prifddinas manta ray bounty", ItemID.SAILING_MANTA_RAY_SKIN, NpcID.SAILING_MANTA_RAY, NpcID.SAILING_MANTA_RAY_DEAD, 1, 10),
	PRIFDDINAS_HAMMERHEAD_SHARK_BOUNTY_577(9240, 577, PortLocation.PRIFDDINAS, "Prifddinas hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_LIVER, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 1, 10),
	RELLEKKA_ALBATROSS_BOUNTY_578(9241, 578, PortLocation.RELLEKKA, "Rellekka albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 5, 2),
	RELLEKKA_HAMMERHEAD_SHARK_BOUNTY_579(9242, 579, PortLocation.RELLEKKA, "Rellekka hammerhead shark bounty", ItemID.SAILING_HAMMERHEAD_SHARK_JAW, NpcID.SAILING_HAMMERHEAD_SHARK, NpcID.SAILING_HAMMERHEAD_SHARK_DEAD, 4, 2),
	RELLEKKA_NARWHAL_BOUNTY_580(9243, 580, PortLocation.RELLEKKA, "Rellekka narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 6, 2),
	RELLEKKA_ARMOURED_KRAKEN_BOUNTY_581(9244, 581, PortLocation.RELLEKKA, "Rellekka armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 5, 2),
	RELLEKKA_ORCA_BOUNTY_582(9245, 582, PortLocation.RELLEKKA, "Rellekka orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	RELLEKKA_VAMPYRE_KRAKEN_BOUNTY_583(9246, 583, PortLocation.RELLEKKA, "Rellekka vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_INK_SAC, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 1, 10),
	RELLEKKA_SPINED_KRAKEN_BOUNTY_584(9247, 584, PortLocation.RELLEKKA, "Rellekka spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ETCETERIA_ALBATROSS_BOUNTY_585(9248, 585, PortLocation.ETCETERIA, "Etceteria albatross bounty", ItemID.SAILING_ALBATROSS_FEATHER, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 6, 2),
	ETCETERIA_ORCA_BOUNTY_586(9249, 586, PortLocation.ETCETERIA, "Etceteria orca bounty", ItemID.SAILING_ORCA_BLUBBER, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 6, 2),
	ETCETERIA_VAMPYRE_KRAKEN_BOUNTY_587(9250, 587, PortLocation.ETCETERIA, "Etceteria vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_TENTACLE, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 4, 2),
	ETCETERIA_NARWHAL_BOUNTY_588(9251, 588, PortLocation.ETCETERIA, "Etceteria narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 6, 2),
	ETCETERIA_SPINED_KRAKEN_BOUNTY_589(9252, 589, PortLocation.ETCETERIA, "Etceteria spined kraken bounty", ItemID.SAILING_SPINED_KRAKEN_INK_SAC, NpcID.SAILING_SPINED_KRAKEN, NpcID.SAILING_SPINED_KRAKEN_DEAD, 1, 10),
	ETCETERIA_ORCA_BOUNTY_590(9253, 590, PortLocation.ETCETERIA, "Etceteria orca bounty", ItemID.SAILING_ORCA_TEETH, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 1, 10),
	ETCETERIA_ARMOURED_KRAKEN_BOUNTY_591(9254, 591, PortLocation.ETCETERIA, "Etceteria armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_INK_SAC, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 1, 10),
	LUNAR_ISLE_ARMOURED_KRAKEN_BOUNTY_592(9255, 592, PortLocation.LUNAR_ISLE, "Lunar Isle armoured kraken bounty", ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE, NpcID.SAILING_ARMOURED_KRAKEN, NpcID.SAILING_ARMOURED_KRAKEN_DEAD, 4, 2),
	LUNAR_ISLE_VAMPYRE_KRAKEN_BOUNTY_593(9256, 593, PortLocation.LUNAR_ISLE, "Lunar Isle vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_TENTACLE, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 6, 2),
	LUNAR_ISLE_NARWHAL_BOUNTY_594(9257, 594, PortLocation.LUNAR_ISLE, "Lunar Isle narwhal bounty", ItemID.SAILING_NARWHAL_BLUBBER, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 5, 2),
	LUNAR_ISLE_ORCA_BOUNTY_595(9258, 595, PortLocation.LUNAR_ISLE, "Lunar Isle orca bounty", ItemID.SAILING_ORCA_BLUBBER, NpcID.SAILING_ORCA, NpcID.SAILING_ORCA_DEAD, 6, 2),
	LUNAR_ISLE_ALBATROSS_BOUNTY_596(9259, 596, PortLocation.LUNAR_ISLE, "Lunar Isle albatross bounty", ItemID.SAILING_ALBATROSS_BEAK, NpcID.SAILING_ALBATROSS, NpcID.SAILING_ALBATROSS_DEAD, 1, 10),
	LUNAR_ISLE_VAMPYRE_KRAKEN_BOUNTY_597(9260, 597, PortLocation.LUNAR_ISLE, "Lunar Isle vampyre kraken bounty", ItemID.SAILING_VAMPYRE_KRAKEN_INK_SAC, NpcID.SAILING_VAMPYRE_KRAKEN, NpcID.SAILING_VAMPYRE_KRAKEN_DEAD, 1, 10),
	LUNAR_ISLE_NARWHAL_BOUNTY_598(9261, 598, PortLocation.LUNAR_ISLE, "Lunar Isle narwhal bounty", ItemID.SAILING_NARWHAL_TUSK, NpcID.SAILING_NARWHAL, NpcID.SAILING_NARWHAL_DEAD, 1, 10),
	;
	private final int dbrow;
	private final int id;
	private final PortLocation bountyLocation;
	public final String taskName;
	public final int itemId;
	public final int npcId;
	private final int deadNpcId;
	public final int itemQuantity;
	public final int itemRarity;

	private static final Set<Integer> VARBIT_VALUES;

	BountyTaskData(int dbrow, int id, PortLocation bountyLocation, String taskName, int itemId, int npcId, int deadNpcId, int itemQuantity, int itemRarity)
	{
		this.dbrow = dbrow;
		this.id = id;
		this.bountyLocation = bountyLocation;
		this.taskName = taskName;
		this.itemId = itemId;
		this.npcId = npcId;
		this.deadNpcId = deadNpcId;
		this.itemQuantity = itemQuantity;
		this.itemRarity = itemRarity; //
	}

	static
	{
		Set<Integer> varbitValues = new HashSet<>();
		for (BountyTaskData b : values())
		{
			varbitValues.add(b.id);
		}
		VARBIT_VALUES = Collections.unmodifiableSet(varbitValues);
	}

	public static BountyTaskData fromId(int id)
	{
		for (BountyTaskData task : values())
		{
			if (task.id == id)
				return task;
		}
		return null;
	}

	public static boolean isBountyTask(int id)
	{
		return VARBIT_VALUES.contains(id);
	}
}
