package com.nucleon.porttasks.enums;

import lombok.Value;
import net.runelite.api.gameval.ItemID;
import java.util.HashMap;
import java.util.Map;

@Value
public class Cargo
{
	int itemId;
	String name;
	PortLocation destination;

	private static final Map<Integer, Cargo> BY_ITEM_ID = new HashMap<>();

	static
	{
		register(ItemID.CARGO_CRATE_ADAMANTITE_ORE_ALDARIN, "adamantite", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_ADAMANTITE_ORE_ETCETERIA, "adamantite", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_ADAMANTITE_ORE_RELLEKKA, "adamantite", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_ALPACA_WOOL_DEEPFIN_POINT, "wool", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_AMULETS_PORT_SARIM, "amulet", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_ANGLER_OUTFIT_PIECES_PORT_KHAZARD, "angler outfit", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_ANTELOPE_FUR_LUNAR_ISLE, "fur", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_ANTELOPE_FUR_PORT_ROBERTS, "fur", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_ANTELOPE_MEAT_PORT_PISCARILIUS, "meat", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_ARROWTIPS_ARDOUGNE, "arrowtip", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_ARROWTIPS_CATHERBY, "arrowtip", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_ARROWTIPS_CORSAIR_COVE, "arrowtip", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_ARROWTIPS_PORT_KHAZARD, "arrowtip", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_ARROWTIPS_PORT_TYRAS, "arrowtip", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_ARROWTIPS_THE_PANDEMONIUM, "arrowtip", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_ASTRAL_RUNES_CIVITAS_ILLA_FORTIS, "rune", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_ASTRAL_RUNES_PORT_PISCARILIUS, "rune", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_ASTRAL_RUNES_PRIFDDINAS, "rune", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_ASTRAL_RUNES_RED_ROCK, "rune", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_BAIT_CATHERBY, "bait", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_BANANAS_ARDOUGNE, "banana", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_BANANAS_CATHERBY, "banana", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_BANANAS_ENTRANA, "banana", PortLocation.ENTRANA);
		register(ItemID.CARGO_CRATE_BANANAS_MUSA_POINT, "banana", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_BANANAS_THE_PANDEMONIUM, "banana", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_BANANAS_THE_SUMMER_SHORE, "banana", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_BARLEY_ENTRANA, "barley", PortLocation.ENTRANA);
		register(ItemID.CARGO_CRATE_BATTLEAXES_RED_ROCK, "battleaxe", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_BATTLEAXES_THE_PANDEMONIUM, "battleaxe", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_BEAR_MEAT_BRIMHAVEN, "meat", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_BEAR_MEAT_CORSAIR_COVE, "meat", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_BEAR_MEAT_LANDS_END, "meat", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_BEER_BRIMHAVEN, "beer", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_BEER_CORSAIR_COVE, "beer", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_BEER_GLASSES_MUSA_POINT, "beer glass", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_BEER_PORT_SARIM, "beer", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_BEER_RELLEKKA, "beer", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_BEER_SUNSET_COAST, "beer", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_BERRIES_LUNAR_ISLE, "berry", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_BERRIES_PORT_ROBERTS, "berry", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_BOOKS_CIVITAS_ILLA_FORTIS, "book", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, "book", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_BOOKS_PORT_SARIM, "book", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_BOOKS_PRIFDDINAS, "book", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_BOWS_PORT_KHAZARD, "bow", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_BOWS_PORT_ROBERTS, "bow", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_BREAD_PORT_KHAZARD, "bread", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_CACTI_BRIMHAVEN, "cacti", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_CACTI_PORT_SARIM, "cacti", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_CACTI_THE_PANDEMONIUM, "cacti", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_CACTI_THE_SUMMER_SHORE, "cacti", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_CALQUAT_RUINS_OF_UNKAH, "calquat", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_CAMPHOR_LOGS_BRIMHAVEN, "camphor", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_CAMPHOR_LOGS_DEEPFIN_POINT, "camphor", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_CAMPHOR_LOGS_PORT_SARIM, "camphor", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_CANNONBALLS_PORT_PISCARILIUS, "cannonball", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_CHAINBODIES_PORT_KHAZARD, "chainbody", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_CHINCHOMPAS_PORT_TYRAS, "chinchompa", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_CLOTHES_PRIFDDINAS, "clothes", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_COAL_LUNAR_ISLE, "coal", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_COAL_NEITIZNOT, "coal", PortLocation.NEITIZNOT);
		register(ItemID.CARGO_CRATE_COAL_PORT_KHAZARD, "coal", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_COAL_PORT_PISCARILIUS, "coal", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_COAL_PORT_TYRAS, "coal", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_COAL_RED_ROCK, "coal", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_COCKTAILS_MUSA_POINT, "cocktail", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_COCKTAILS_RUINS_OF_UNKAH, "cocktail", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_COCONUTS_CATHERBY, "coconut", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_COCONUTS_PORT_SARIM, "coconut", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_COMPOST_BRIMHAVEN, "compost", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_CORAL_CIVITAS_ILLA_FORTIS, "coral", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_CORAL_PORT_ROBERTS, "coral", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_CORAL_RUINS_OF_UNKAH, "coral", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_CORAL_THE_PANDEMONIUM, "coral", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_CORAL_VOID_KNIGHTS_OUTPOST, "coral", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_CRAB_PASTE_ALDARIN, "crab paste", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_CRAB_PASTE_PORT_KHAZARD, "crab paste", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ALDARIN, "crystal seed", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ARDOUGNE, "crystal seed", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_CRYSTAL_SEEDS_LUNAR_ISLE, "crystal seed", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_DAGGERS_ALDARIN, "dagger", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_DAGGERS_CORSAIR_COVE, "dagger", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_DRAGONHIDE_VOID_KNIGHTS_OUTPOST, "dragonhide", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_DRAGON_BITTER_RELLEKKA, "dragon bitter", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_DYES_ALDARIN, "dye", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_EYE_PATCHES_MUSA_POINT, "eye patch", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_FABRICS_DEEPFIN_POINT, "fabric", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_FABRICS_PISCATORIS, "fabric", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_FABRICS_PORT_PISCARILIUS, "fabric", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_FABRICS_PORT_ROBERTS, "fabric", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_FABRICS_PORT_TYRAS, "fabric", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_FABRICS_RELLEKKA, "fabric", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_FABRICS_SUNSET_COAST, "fabric", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_FISHING_SUPPLIES_RUINS_OF_UNKAH, "fishing supplies", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_FISH_ARDOUGNE, "fish", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_FISH_BRIMHAVEN, "fish", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_FISH_CIVITAS_ILLA_FORTIS, "fish", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_FISH_CORSAIR_COVE, "fish", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_FISH_ETCETERIA, "fish", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_FISH_HOSIDIUS, "fish", PortLocation.HOSIDIUS);
		register(ItemID.CARGO_CRATE_FISH_JATIZSO, "fish", PortLocation.JATIZSO);
		register(ItemID.CARGO_CRATE_FISH_LANDS_END, "fish", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, "fish", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_FISH_MUSA_POINT, "fish", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_FISH_PISCATORIS, "fish", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, "fish", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_FISH_PORT_SARIM, "fish", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_FISH_PORT_TYRAS, "fish", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_FISH_PRIFDDINAS, "fish", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_FISH_RED_ROCK, "fish", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_FISH_RELLEKKA, "fish", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_FISH_RUINS_OF_UNKAH, "fish", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_FISH_SUNSET_COAST, "fish", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_FLAX_JATIZSO, "flax", PortLocation.JATIZSO);
		register(ItemID.CARGO_CRATE_FLAX_PISCATORIS, "flax", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_FLAX_PORT_ROBERTS, "flax", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_FLAX_PORT_SARIM, "flax", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_FRUIT_CIVITAS_ILLA_FORTIS, "fruit", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_FRUIT_DEEPFIN_POINT, "fruit", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_FRUIT_ETCETERIA, "fruit", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_FRUIT_PORT_KHAZARD, "fruit", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_FRUIT_PORT_TYRAS, "fruit", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_FURS_ALDARIN, "fur", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_FURS_ARDOUGNE, "fur", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_FURS_CATHERBY, "fur", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_FURS_DEEPFIN_POINT, "fur", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_FURS_LANDS_END, "fur", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_FURS_LUNAR_ISLE, "fur", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_FURS_PISCATORIS, "fur", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_FURS_PISCATORIS, "fur", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_FURS_PORT_PISCARILIUS, "fur", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_FURS_PORT_PISCARILIUS, "fur", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_FURS_PORT_ROBERTS, "fur", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_FURS_PORT_TYRAS, "fur", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_FURS_RED_ROCK, "fur", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_GEMS_BRIMHAVEN, "gem", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_GEMS_CIVITAS_ILLA_FORTIS, "gem", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_GEMS_CORSAIR_COVE, "gem", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_GEMS_LANDS_END, "gem", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_GEMS_PORT_PISCARILIUS, "gem", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_GEMS_PORT_ROBERTS, "gem", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_GEMS_THE_SUMMER_SHORE, "gem", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_GIN_PORT_PISCARILIUS, "gin", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_GLASSMAKING_SUPPLIES_CATHERBY, "glassmaking supplies", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_GOLD_BARS_CAIRN_ISLE, "gold", PortLocation.CAIRN_ISLE);
		register(ItemID.CARGO_CRATE_GOLD_BARS_THE_PANDEMONIUM, "gold", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_GOLD_ORE_ARDOUGNE, "gold", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_GOLD_ORE_CATHERBY, "gold", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_GRANITE_DEEPFIN_POINT, "granite", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_GRANITE_RED_ROCK, "granite", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_GRANITE_THE_PANDEMONIUM, "granite", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_GRANITE_VOID_KNIGHTS_OUTPOST, "granite", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_GROG_CATHERBY, "grog", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_GUNPOWDER_PORT_KHAZARD, "gunpowder", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_HALBERDS_ARDOUGNE, "halberd", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_HALBERDS_PRIFDDINAS, "halberd", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_HALBERDS_RELLEKKA, "halberd", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_HERBS_PORT_KHAZARD, "herb", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_HERBS_PORT_TYRAS, "herb", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_HERBS_PRIFDDINAS, "herb", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_HERBS_RED_ROCK, "herb", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_HERBS_VOID_KNIGHTS_OUTPOST, "herb", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_HIGH_IMPORTANCE_MUSA_POINT, "important", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_HISTORICAL_ARTEFACTS_CIVITAS_ILLA_FORTIS, "artefact", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_HONEY_MUSA_POINT, "honey", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_HONEY_PORT_PISCARILIUS, "honey", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_HONEY_PORT_ROBERTS, "honey", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_HONEY_PORT_SARIM, "honey", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_HUASCA_PORT_KHAZARD, "huasca", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_IRON_BARS_BRIMHAVEN, "iron", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_IRON_ORE_ETCETERIA, "iron", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_JAVELINS_CATHERBY, "javelin", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_JAVELINS_DEEPFIN_POINT, "javelin", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_JAVELINS_RUINS_OF_UNKAH, "javelin", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_JAVELINS_THE_SUMMER_SHORE, "javelin", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_JEWELLERY_ALDARIN, "jewellery", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_JEWELLERY_ARDOUGNE, "jewellery", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_JEWELLERY_BRIMHAVEN, "jewellery", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_JEWELLERY_CATHERBY, "jewellery", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, "jewellery", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_JEWELLERY_PORT_ROBERTS, "jewellery", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_JEWELLERY_PORT_SARIM, "jewellery", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_JEWELLERY_THE_SUMMER_SHORE, "jewellery", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_KARAMBWANS_CATHERBY, "karambwan", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_KARAMBWANS_RED_ROCK, "karambwan", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_KEBABS_PORT_SARIM, "kebab", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_KEBBIT_FUR_LANDS_END, "fur", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_KEBBIT_FUR_LUNAR_ISLE, "fur", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_KEBBIT_FUR_PORT_PISCARILIUS, "fur", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_KHALI_BREWS_CORSAIR_COVE, "khali brew", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_KYATT_TEETH_PORT_KHAZARD, "kyatt teeth", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_LEAD_ORE_ALDARIN, "lead", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_LEAD_ORE_HOSIDIUS, "lead", PortLocation.HOSIDIUS);
		register(ItemID.CARGO_CRATE_LEAD_ORE_RELLEKKA, "lead", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_LEATHER_THE_SUMMER_SHORE, "leather", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_LOBSTERS_MUSA_POINT, "lobster", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, "logs", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_LOGS_JATIZSO, "logs", PortLocation.JATIZSO);
		register(ItemID.CARGO_CRATE_LOGS_LUNAR_ISLE, "logs", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_LOGS_MUSA_POINT, "logs", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_LOGS_PORT_ROBERTS, "logs", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_LOGS_PORT_SARIM, "logs", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_LOGS_PRIFDDINAS, "logs", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_LOGS_VOID_KNIGHTS_OUTPOST, "logs", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_MACES_SUNSET_COAST, "mace", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_MACES_VOID_KNIGHTS_OUTPOST, "mace", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_MACHINERY_PARTS_BRIMHAVEN, "machinery", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_MACHINERY_PARTS_DEEPFIN_POINT, "machinery", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_MAHOGANY_LOGS_DEEPFIN_POINT, "mahogany", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_MAHOGANY_LOGS_MUSA_POINT, "mahogany", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_MAHOGANY_LOGS_NEITIZNOT, "mahogany", PortLocation.NEITIZNOT);
		register(ItemID.CARGO_CRATE_MAHOGANY_LOGS_PORT_PISCARILIUS, "mahogany", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_MEAT_LANDS_END, "meat", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_MEAT_MUSA_POINT, "meat", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_MEAT_PORT_ROBERTS, "meat", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_MEAT_THE_PANDEMONIUM, "meat", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_MEAT_THE_SUMMER_SHORE, "meat", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_MITHRIL_ORE_PORT_TYRAS, "mithril", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_MONKFISH_ALDARIN, "monkfish", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_MONKFISH_ETCETERIA, "monkfish", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_MONKFISH_RELLEKKA, "monkfish", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_NICKEL_ORE_ALDARIN, "nickel", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_NICKEL_ORE_CIVITAS_ILLA_FORTIS, "nickel", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_NICKEL_ORE_PORT_ROBERTS, "nickel", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_NICKEL_ORE_THE_SUMMER_SHORE, "nickel", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_NOTHING_SINISTER_PORT_SARIM, "nothing sinister", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_ONIONS_ETCETERIA, "onion", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_ORANGES_CIVITAS_ILLA_FORTIS, "orange", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_ORES_CIVITAS_ILLA_FORTIS, "ore", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_ORES_LANDS_END, "ore", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_ORES_PORT_ROBERTS, "ore", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_ORES_PORT_TYRAS, "ore", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_ORES_PRIFDDINAS, "ore", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_ORES_RED_ROCK, "ore", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_ORES_VOID_KNIGHTS_OUTPOST, "ore", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_PEG_LEGS_CORSAIR_COVE, "peg leg", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_PEST_REMAINS_ALDARIN, "pest remains", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_PEST_REMAINS_DEEPFIN_POINT, "pest remains", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_PEST_REMAINS_PORT_SARIM, "pest remains", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_PEST_REMAINS_THE_SUMMER_SHORE, "pest remains", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_PICKAXES_DEEPFIN_POINT, "pickaxe", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_PIES_RELLEKKA, "pie", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_PINEAPPLES_CATHERBY, "pineapple", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_PINEAPPLES_CIVITAS_ILLA_FORTIS, "pineapple", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_PINEAPPLES_THE_PANDEMONIUM, "pineapple", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_PINEAPPLES_THE_SUMMER_SHORE, "pineapple", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, "plank", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_PLANKS_ETCETERIA, "plank", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_PLANKS_PORT_KHAZARD, "plank", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, "plank", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, "plank", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_PLANKS_RELLEKKA, "plank", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_PLANKS_RUINS_OF_UNKAH, "plank", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_PLATEBODIES_ALDARIN, "platebody", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_PLATEBODIES_CORSAIR_COVE, "platebody", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_PLATEBODIES_PORT_KHAZARD, "platebody", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_PLATEBODIES_PORT_PISCARILIUS, "platebody", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_PLATEBODIES_PORT_TYRAS, "platebody", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_PLATEBODIES_THE_PANDEMONIUM, "platebody", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_PLATEBODIES_VOID_KNIGHTS_OUTPOST, "platebody", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_POISON_ARDOUGNE, "poison", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_POTATOES_CATHERBY, "potato", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_POTIONS_LUNAR_ISLE, "potion", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_POTIONS_PISCATORIS, "potion", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_POTIONS_PRIFDDINAS, "potion", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_POTIONS_THE_SUMMER_SHORE, "potion", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_POTIONS_VOID_KNIGHTS_OUTPOST, "potion", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_PROTECTIVE_CLOTHING_RED_ROCK, "protective clothing", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_RABBIT_MEAT_ARDOUGNE, "meat", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_REDWOOD_LOGS_RELLEKKA, "redwood", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_RED_CORAL_ARDOUGNE, "red coral", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_RED_CORAL_CIVITAS_ILLA_FORTIS, "red coral", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_RED_CORAL_LUNAR_ISLE, "red coral", PortLocation.LUNAR_ISLE);
		register(ItemID.CARGO_CRATE_RED_CORAL_PORT_KHAZARD, "red coral", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_RED_CORAL_PORT_PISCARILIUS, "red coral", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_RED_CORAL_PORT_ROBERTS, "red coral", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_RED_CORAL_PORT_SARIM, "red coral", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_ROPE_HOSIDIUS, "rope", PortLocation.HOSIDIUS);
		register(ItemID.CARGO_CRATE_ROPE_RELLEKKA, "rope", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_ROPE_THE_SUMMER_SHORE, "rope", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_ROTTEN_BANANAS_MUSA_POINT, "rotten banana", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_RUM_BRIMHAVEN, "rum", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_RUM_CORSAIR_COVE, "rum", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_RUM_THE_PANDEMONIUM, "rum", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_RUNES_ARDOUGNE, "rune", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_RUNES_CIVITAS_ILLA_FORTIS, "rune", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_RUNES_PORT_ROBERTS, "rune", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_RUNES_PORT_SARIM, "rune", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_RUNES_RED_ROCK, "rune", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_RUNES_RUINS_OF_UNKAH, "rune", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_RUNES_VOID_KNIGHTS_OUTPOST, "rune", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_SALAMANDERS_ARDOUGNE, "salamander", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_SANDSTONE_BRIMHAVEN, "sandstone", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_SANDSTONE_THE_SUMMER_SHORE, "sandstone", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_SAND_ARDOUGNE, "sand", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_SAND_ENTRANA, "sand", PortLocation.ENTRANA);
		register(ItemID.CARGO_CRATE_SAND_NEITIZNOT, "sand", PortLocation.NEITIZNOT);
		register(ItemID.CARGO_CRATE_SCIMITARS_CORSAIR_COVE, "scimitar", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_SCIMITARS_PORT_KHAZARD, "scimitar", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_SEA_SHELLS_THE_PANDEMONIUM, "sea shell", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_SECRET_STUFF_CAIRN_ISLE, "secret", PortLocation.CAIRN_ISLE);
		register(ItemID.CARGO_CRATE_SECRET_STUFF_MUSA_POINT, "secret", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_SECRET_STUFF_PORT_KHAZARD, "secret", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_SECRET_THINGS_LANDS_END, "secret", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_SEEDS_CATHERBY, "seed", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_SEEDS_CIVITAS_ILLA_FORTIS, "seed", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_SEEDS_PORT_PISCARILIUS, "seed", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_SEEDS_PORT_ROBERTS, "seed", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_SEEDS_PORT_SARIM, "seed", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_SEEDS_PORT_TYRAS, "seed", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_SEEDS_VOID_KNIGHTS_OUTPOST, "seed", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_SHIELDS_PORT_TYRAS, "shield", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_SHIELDS_THE_SUMMER_SHORE, "shield", PortLocation.SUMMER_SHORE);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_CIVITAS_ILLA_FORTIS, "ship part", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_CORSAIR_COVE, "ship part", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_MUSA_POINT, "ship part", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_RED_ROCK, "ship part", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_RELLEKKA, "ship part", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_SHIP_PARTS_RUINS_OF_UNKAH, "ship part", PortLocation.RUINS_OF_UNKAH);
		register(ItemID.CARGO_CRATE_SILK_ARDOUGNE, "silk", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_SILK_CATHERBY, "silk", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_SILK_MUSA_POINT, "silk", PortLocation.MUSA_POINT);
		register(ItemID.CARGO_CRATE_SILK_PORT_ROBERTS, "silk", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_SILK_PRIFDDINAS, "silk", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_SILVER_ORE_BRIMHAVEN, "silver", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_SILVER_ORE_CATHERBY, "silver", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_SILVER_ORE_PORT_ROBERTS, "silver", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_SNAKESKIN_PORT_TYRAS, "snakeskin", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_SPEARS_ALDARIN, "spear", PortLocation.ALDARIN);
		register(ItemID.CARGO_CRATE_SPEARS_PORT_KHAZARD, "spear", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_SPEARS_VOID_KNIGHTS_OUTPOST, "spear", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_SPICES_ARDOUGNE, "spice", PortLocation.ARDOUGNE);
		register(ItemID.CARGO_CRATE_SPICES_BRIMHAVEN, "spice", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_SPICES_CIVITAS_ILLA_FORTIS, "spice", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_SPICES_PORT_SARIM, "spice", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_SPICES_PRIFDDINAS, "spice", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_SPICES_RED_ROCK, "spice", PortLocation.RED_ROCK);
		register(ItemID.CARGO_CRATE_SPICES_THE_PANDEMONIUM, "spice", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_STAFFS_CIVITAS_ILLA_FORTIS, "staff", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_STAFFS_PORT_ROBERTS, "staff", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_STEEL_BARS_THE_PANDEMONIUM, "steel", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_SUNBEAM_ALE_PORT_SARIM, "sunbeam ale", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_SUQAH_HIDES_DEEPFIN_POINT, "suqah hide", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_SWAMP_PASTE_PORT_KHAZARD, "swamp paste", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_SWAMP_PASTE_THE_PANDEMONIUM, "swamp paste", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_SWORDS_CORSAIR_COVE, "sword", PortLocation.CORSAIR_COVE);
		register(ItemID.CARGO_CRATE_SWORDS_ETCETERIA, "sword", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_SWORDS_LANDS_END, "sword", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_SWORDS_PORT_SARIM, "sword", PortLocation.PORT_SARIM);
		register(ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, "sword", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_TEAK_LOGS_PORT_ROBERTS, "teak", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_TEAK_LOGS_RELLEKKA, "teak", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_TOKENS_CIVITAS_ILLA_FORTIS, "token", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_VEGETABLES_CIVITAS_ILLA_FORTIS, "vegetable", PortLocation.CIVITAS_ILLA_FORTIS);
		register(ItemID.CARGO_CRATE_VEGETABLES_LANDS_END, "vegetable", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_VEGETABLES_PORT_TYRAS, "vegetable", PortLocation.PORT_TYRAS);
		register(ItemID.CARGO_CRATE_VIALS_CATHERBY, "vial", PortLocation.CATHERBY);
		register(ItemID.CARGO_CRATE_VODKA_BRIMHAVEN, "vodka", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_VODKA_PISCATORIS, "vodka", PortLocation.PISCATORIS);
		register(ItemID.CARGO_CRATE_VODKA_PORT_KHAZARD, "vodka", PortLocation.PORT_KHAZARD);
		register(ItemID.CARGO_CRATE_WARHAMMERS_DEEPFIN_POINT, "warhammer", PortLocation.DEEPFIN_POINT);
		register(ItemID.CARGO_CRATE_WARHAMMERS_ETCETERIA, "warhammer", PortLocation.ETCETERIA);
		register(ItemID.CARGO_CRATE_WARHAMMERS_SUNSET_COAST, "warhammer", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_WAX_THE_PANDEMONIUM, "wax", PortLocation.PANDEMONIUM);
		register(ItemID.CARGO_CRATE_WINE_BRIMHAVEN, "wine", PortLocation.BRIMHAVEN);
		register(ItemID.CARGO_CRATE_WINE_LANDS_END, "wine", PortLocation.LANDS_END);
		register(ItemID.CARGO_CRATE_WINE_PORT_PISCARILIUS, "wine", PortLocation.PORT_PISCARILIUS);
		register(ItemID.CARGO_CRATE_WINE_PORT_ROBERTS, "wine", PortLocation.PORT_ROBERTS);
		register(ItemID.CARGO_CRATE_WINE_RELLEKKA, "wine", PortLocation.RELLEKKA);
		register(ItemID.CARGO_CRATE_WINE_SUNSET_COAST, "wine", PortLocation.SUNSET_COAST);
		register(ItemID.CARGO_CRATE_WRATH_RUNES_VOID_KNIGHTS_OUTPOST, "rune", PortLocation.VOID_KNIGHTS_OUTPOST);
		register(ItemID.CARGO_CRATE_XERICIAN_FABRICS_HOSIDIUS, "fabric", PortLocation.HOSIDIUS);
		register(ItemID.CARGO_CRATE_XERICIAN_FABRICS_PRIFDDINAS, "fabric", PortLocation.PRIFDDINAS);
		register(ItemID.CARGO_CRATE_YAK_HAIR_ETCETERIA, "yak hair", PortLocation.ETCETERIA);
		
		// Special tutorial/quest items
		register(ItemID.PRYING_TIMES_CARGO_CRATE, "pirate looty", PortLocation.PANDEMONIUM);
		register(ItemID.SAILING_INTRO_CARGO_CRATE, "ship part", PortLocation.PANDEMONIUM);
	}

	private static void register(int itemId, String name, PortLocation destination)
	{
		BY_ITEM_ID.put(itemId, new Cargo(itemId, name, destination));
	}

	/**
	 * Get the Cargo instance for a given ItemID.
	 * @param itemId the ItemID integer value
	 * @return the Cargo instance, or null if not found
	 */
	public static Cargo fromItemId(int itemId)
	{
        Cargo cargo = BY_ITEM_ID.get(itemId);
        if (cargo == null) {
            throw new IllegalArgumentException("No cargo found for ItemID: " + itemId);
        }

        return cargo;
	}
}
