/*
 * Copyright (c) 2025, nucleon <https://github.com/nucleon>
 * Copyright (c) 2025, Cooper Morris <https://github.com/coopermor>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.nucleon.porttasks.enums;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

@Getter
public enum CourierTaskData
{
	PANDEMONIUM_PLATEBODY_DELIVERY_1(8664, 1, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_PLATEBODIES_THE_PANDEMONIUM, 1, 71),
	PORT_SARIM_SPICE_DELIVERY_2(8665, 2, PortLocation.PORT_SARIM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SPICES_PORT_SARIM, 1, 141),
	MUSA_POINT_LOGS_DELIVERY_3(8666, 3, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_LOGS_MUSA_POINT, 1, 72),
	PORT_SARIM_LOGS_DELIVERY_4(8667, 4, PortLocation.PORT_SARIM, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_LOGS_PORT_SARIM, 1, 80),
	CATHERBY_BAIT_DELIVERY_5(8668, 5, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BAIT_CATHERBY, 1, 525),
	PORT_SARIM_HONEY_DELIVERY_6(8669, 6, PortLocation.PORT_SARIM, PortLocation.CATHERBY, ItemID.CARGO_CRATE_HONEY_PORT_SARIM, 1, 525),
	PANDEMONIUM_BATTLEAXE_DELIVERY_7(8670, 7, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BATTLEAXES_THE_PANDEMONIUM, 1, 71),
	MUSA_POINT_FISH_DELIVERY_8(8671, 8, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_FISH_MUSA_POINT, 2, 90),
	CATHERBY_POTATO_DELIVERY_9(8672, 9, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_POTATOES_CATHERBY, 1, 294),
	ARDOUGNE_SALAMANDER_DELIVERY_10(8673, 10, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_SALAMANDERS_ARDOUGNE, 1, 273),
	PORT_SARIM_SEED_DELIVERY_11(8674, 11, PortLocation.PORT_SARIM, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SEEDS_PORT_SARIM, 1, 546),
	PORT_KHAZARD_SWAMP_PASTE_DELIVERY_12(8675, 12, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_SWAMP_PASTE_PORT_KHAZARD, 1, 321),
	PORT_SARIM_SWORD_DELIVERY_13(8676, 13, PortLocation.PORT_SARIM, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SWORDS_PORT_SARIM, 1, 641),
	BRIMHAVEN_VODKA_DELIVERY_14(8677, 14, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_VODKA_BRIMHAVEN, 1, 238),
	PORT_SARIM_DELIVERY_OF_NOTHING_SINISTER_15(8678, 15, PortLocation.PORT_SARIM, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_NOTHING_SINISTER_PORT_SARIM, 2, 504),
	PORT_PISCARILIUS_BOOK_DELIVERY_16(8679, 16, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 2, 919),
	RUIN_OF_UNKAH_RUNE_DELIVERY_17(8680, 17, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_RUNES_RUINS_OF_UNKAH, 2, 517),
	RELLEKKA_PIE_DELIVERY_18(8681, 18, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_PIES_RELLEKKA, 4, 5155),
	PORT_SARIM_PEST_REMAINS_DELIVERY_19(8682, 19, PortLocation.PORT_SARIM, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_PEST_REMAINS_PORT_SARIM, 3, 1976),
	PORT_SARIM_JEWELLERY_DELIVERY_20(8683, 20, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_JEWELLERY_PORT_SARIM, 1, 71),
	PANDEMONIUM_STEEL_DELIVERY_21(8684, 21, PortLocation.PANDEMONIUM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_STEEL_BARS_THE_PANDEMONIUM, 1, 141),
	MUSA_POINT_ROTTEN_BANANA_DELIVERY_22(8685, 22, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_ROTTEN_BANANAS_MUSA_POINT, 1, 81),
	PANDEMONIUM_RUM_DELIVERY_23(8686, 23, PortLocation.PANDEMONIUM, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_RUM_THE_PANDEMONIUM, 1, 100),
	BRIMHAVEN_JEWELLERY_DELIVERY_24(8687, 24, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_JEWELLERY_BRIMHAVEN, 2, 273),
	PANDEMONIUM_PINEAPPLE_DELIVERY_25(8688, 25, PortLocation.PANDEMONIUM, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_PINEAPPLES_THE_PANDEMONIUM, 2, 546),
	PORT_SARIM_FISH_DELIVERY_26(8689, 26, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_FISH_PORT_SARIM, 1, 71),
	MUSA_POINT_SHIP_PART_DELIVERY_27(8690, 27, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SHIP_PARTS_MUSA_POINT, 1, 90),
	BRIMHAVEN_CACTI_DELIVERY_28(8691, 28, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_CACTI_BRIMHAVEN, 1, 276),
	CATHERBY_GROG_DELIVERY_29(8692, 29, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_GROG_CATHERBY, 1, 269),
	PANDEMONIUM_ARROWTIP_DELIVERY_30(8693, 30, PortLocation.PANDEMONIUM, PortLocation.CATHERBY, ItemID.CARGO_CRATE_ARROWTIPS_THE_PANDEMONIUM, 1, 538),
	CORSAIR_COVE_SCIMITAR_DELIVERY_31(8694, 31, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SCIMITARS_CORSAIR_COVE, 3, 595),
	PANDEMONIUM_GOLD_DELIVERY_32(8695, 32, PortLocation.PANDEMONIUM, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_GOLD_BARS_THE_PANDEMONIUM, 3, 1190),
	PORT_KHAZARD_KYATT_TEETH_DELIVERY_33(8696, 33, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_KYATT_TEETH_PORT_KHAZARD, 1, 343),
	PANDEMONIUM_SWAMP_PASTE_DELIVERY_34(8697, 34, PortLocation.PANDEMONIUM, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SWAMP_PASTE_THE_PANDEMONIUM, 1, 686),
	RUIN_OF_UNKAH_COCKTAIL_DELIVERY_35(8698, 35, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_COCKTAILS_RUINS_OF_UNKAH, 2, 243),
	PANDEMONIUM_GRANITE_DELIVERY_36(8699, 36, PortLocation.PANDEMONIUM, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_GRANITE_THE_PANDEMONIUM, 3, 548),
	CAIRN_ISLE_SECRET_DELIVERY_37(8700, 37, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SECRET_STUFF_CAIRN_ISLE, 3, 538),
	ARDOUGNE_SAND_DELIVERY_38(8701, 38, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SAND_ARDOUGNE, 1, 118),
	PORT_SARIM_COCONUT_DELIVERY_39(8702, 39, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_COCONUTS_PORT_SARIM, 1, 72),
	MUSA_POINT_BANANA_DELIVERY_40(8703, 40, PortLocation.MUSA_POINT, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BANANAS_MUSA_POINT, 1, 144),
	PANDEMONIUM_BANANA_DELIVERY_41(8704, 41, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_BANANAS_THE_PANDEMONIUM, 1, 81),
	MUSA_POINT_EYE_PATCH_DELIVERY_42(8705, 42, PortLocation.MUSA_POINT, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_EYE_PATCHES_MUSA_POINT, 1, 162),
	BRIMHAVEN_RUM_DELIVERY_43(8706, 43, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_RUM_BRIMHAVEN, 1, 154),
	MUSA_POINT_MAHOGANY_DELIVERY_44(8707, 44, PortLocation.MUSA_POINT, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_MAHOGANY_LOGS_MUSA_POINT, 1, 308),
	PORT_SARIM_LOGS_DELIVERY_45(8708, 45, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_LOGS_PORT_SARIM, 1, 144),
	PANDEMONIUM_RUM_DELIVERY_46(8709, 46, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_RUM_THE_PANDEMONIUM, 2, 162),
	BRIMHAVEN_SILVER_DELIVERY_47(8710, 47, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_SILVER_ORE_BRIMHAVEN, 2, 179),
	CATHERBY_COCONUT_DELIVERY_48(8711, 48, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_COCONUTS_CATHERBY, 1, 175),
	MUSA_POINT_HONEY_DELIVERY_49(8712, 49, PortLocation.MUSA_POINT, PortLocation.CATHERBY, ItemID.CARGO_CRATE_HONEY_MUSA_POINT, 2, 375),
	ENTRANA_BANANA_DELIVERY_50(8713, 50, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_BANANAS_ENTRANA, 2, 168),
	MUSA_POINT_BEER_GLASS_DELIVERY_51(8714, 51, PortLocation.MUSA_POINT, PortLocation.ENTRANA, ItemID.CARGO_CRATE_BEER_GLASSES_MUSA_POINT, 2, 337),
	ARDOUGNE_BANANA_DELIVERY_52(8715, 52, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_BANANAS_ARDOUGNE, 2, 203),
	MUSA_POINT_SILK_DELIVERY_53(8716, 53, PortLocation.MUSA_POINT, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SILK_MUSA_POINT, 1, 378),
	CORSAIR_COVE_PEG_LEG_DELIVERY_54(8717, 54, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_PEG_LEGS_CORSAIR_COVE, 2, 751),
	SUMMER_SHORE_BANANA_DELIVERY_55(8718, 55, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_BANANAS_THE_SUMMER_SHORE, 2, 791),
	PORT_TYRAS_SNAKESKIN_DELIVERY_56(8719, 56, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_SNAKESKIN_PORT_TYRAS, 6, 3313),
	MUSA_POINT_SECRET_DELIVERY_57(8720, 57, PortLocation.MUSA_POINT, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SECRET_STUFF_MUSA_POINT, 2, 492),
	PORT_SARIM_FLAX_DELIVERY_58(8721, 58, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_FLAX_PORT_SARIM, 1, 263),
	CATHERBY_BAIT_DELIVERY_59(8722, 59, PortLocation.CATHERBY, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BAIT_CATHERBY, 1, 525),
	ARDOUGNE_FISH_DELIVERY_60(8723, 60, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_FISH_ARDOUGNE, 2, 63),
	CATHERBY_ARROWTIP_DELIVERY_61(8724, 61, PortLocation.CATHERBY, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_ARROWTIPS_CATHERBY, 2, 280),
	PORT_KHAZARD_BOW_DELIVERY_62(8725, 62, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_BOWS_PORT_KHAZARD, 2, 179),
	CATHERBY_GLASSMAKING_SUPPLIES_DELIVERY_63(8726, 63, PortLocation.CATHERBY, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_GLASSMAKING_SUPPLIES_CATHERBY, 2, 358),
	PORT_SARIM_BEER_DELIVERY_64(8727, 64, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_BEER_PORT_SARIM, 1, 294),
	ARDOUGNE_POISON_DELIVERY_65(8728, 65, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_POISON_ARDOUGNE, 1, 134),
	PORT_KHAZARD_COAL_DELIVERY_66(8729, 66, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_COAL_PORT_KHAZARD, 3, 219),
	ENTRANA_BARLEY_DELIVERY_67(8730, 67, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_BARLEY_ENTRANA, 2, 118),
	CATHERBY_VIAL_DELIVERY_68(8731, 68, PortLocation.CATHERBY, PortLocation.ENTRANA, ItemID.CARGO_CRATE_VIALS_CATHERBY, 2, 236),
	PANDEMONIUM_WAX_DELIVERY_69(8732, 69, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_WAX_THE_PANDEMONIUM, 1, 269),
	CATHERBY_COCONUT_DELIVERY_70(8733, 70, PortLocation.CATHERBY, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_COCONUTS_CATHERBY, 1, 538),
	BRIMHAVEN_FISH_DELIVERY_71(8734, 71, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_FISH_BRIMHAVEN, 1, 105),
	CATHERBY_KARAMBWAN_DELIVERY_72(8735, 72, PortLocation.CATHERBY, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_KARAMBWANS_CATHERBY, 1, 210),
	MUSA_POINT_LOBSTER_DELIVERY_73(8736, 73, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_LOBSTERS_MUSA_POINT, 2, 188),
	CATHERBY_BANANA_DELIVERY_74(8737, 74, PortLocation.CATHERBY, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_BANANAS_CATHERBY, 2, 375),
	PORT_PISCARILIUS_HONEY_DELIVERY_75(8738, 75, PortLocation.CATHERBY, PortLocation.CATHERBY, ItemID.CARGO_CRATE_HONEY_PORT_PISCARILIUS, 1, 980),
	CATHERBY_JAVELIN_DELIVERY_76(8739, 76, PortLocation.CATHERBY, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_JAVELINS_CATHERBY, 3, 2488),
	MUSA_POINT_COCKTAIL_DELIVERY_77(8740, 77, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_COCKTAILS_MUSA_POINT, 2, 168),
	BRIMHAVEN_FISH_DELIVERY_78(8741, 78, PortLocation.BRIMHAVEN, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_FISH_BRIMHAVEN, 1, 308),
	PORT_KHAZARD_SPEAR_DELIVERY_79(8742, 79, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_SPEARS_PORT_KHAZARD, 1, 97),
	BRIMHAVEN_IRON_DELIVERY_80(8743, 80, PortLocation.BRIMHAVEN, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_IRON_BARS_BRIMHAVEN, 2, 224),
	CORSAIR_COVE_SWORD_DELIVERY_81(8744, 81, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_SWORDS_CORSAIR_COVE, 3, 595),
	BRIMHAVEN_GEM_DELIVERY_82(8745, 82, PortLocation.BRIMHAVEN, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_GEMS_BRIMHAVEN, 2, 1133),
	MUSA_POINT_MEAT_DELIVERY_83(8746, 83, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_MEAT_MUSA_POINT, 1, 164),
	PORT_KHAZARD_FRUIT_DELIVERY_84(8747, 84, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_FRUIT_PORT_KHAZARD, 3, 143),
	CORSAIR_COVE_BEER_DELIVERY_85(8748, 85, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_BEER_CORSAIR_COVE, 3, 639),
	PANDEMONIUM_MEAT_DELIVERY_86(8749, 86, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_MEAT_THE_PANDEMONIUM, 1, 259),
	BRIMHAVEN_SPICE_DELIVERY_87(8750, 87, PortLocation.BRIMHAVEN, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SPICES_BRIMHAVEN, 2, 63),
	CATHERBY_PINEAPPLE_DELIVERY_88(8751, 88, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_PINEAPPLES_CATHERBY, 2, 119),
	BRIMHAVEN_COMPOST_DELIVERY_89(8752, 89, PortLocation.BRIMHAVEN, PortLocation.CATHERBY, ItemID.CARGO_CRATE_COMPOST_BRIMHAVEN, 1, 210),
	RED_ROCK_KARAMBWAN_DELIVERY_90(8753, 90, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_KARAMBWANS_RED_ROCK, 3, -1),
	BRIMHAVEN_MACHINERY_DELIVERY_91(8754, 91, PortLocation.BRIMHAVEN, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_MACHINERY_PARTS_BRIMHAVEN, 4, -1),
	PORT_SARIM_AMULET_DELIVERY_92(8755, 92, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_AMULETS_PORT_SARIM, 2, 252),
	ARDOUGNE_FISH_DELIVERY_93(8756, 93, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_FISH_ARDOUGNE, 1, 63),
	CIVITAS_ILLA_FORTIS_PINEAPPLE_DELIVERY_94(8757, 94, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_PINEAPPLES_CIVITAS_ILLA_FORTIS, 3, 859),
	BRIMHAVEN_CAMPHOR_DELIVERY_95(8758, 95, PortLocation.BRIMHAVEN, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CAMPHOR_LOGS_BRIMHAVEN, 3, 2768),
	BRIMHAVEN_SPICE_DELIVERY_96(8759, 96, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SPICES_BRIMHAVEN, 1, 546),
	ARDOUGNE_GOLD_DELIVERY_97(8760, 97, PortLocation.ARDOUGNE, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_GOLD_ORE_ARDOUGNE, 1, 126),
	CATHERBY_FUR_DELIVERY_98(8761, 98, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_FURS_CATHERBY, 1, 126),
	ARDOUGNE_ARROWTIP_DELIVERY_99(8762, 99, PortLocation.ARDOUGNE, PortLocation.CATHERBY, ItemID.CARGO_CRATE_ARROWTIPS_ARDOUGNE, 1, 252),
	PORT_TYRAS_PLATEBODY_DELIVERY_100(8763, 100, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_PLATEBODIES_PORT_TYRAS, 6, 2438),
	ARDOUGNE_MEAT_DELIVERY_101(8764, 101, PortLocation.ARDOUGNE, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_RABBIT_MEAT_ARDOUGNE, 5, 5625),
	BRIMHAVEN_BEER_DELIVERY_102(8765, 102, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_BEER_BRIMHAVEN, 3, 109),
	CATHERBY_SEED_DELIVERY_103(8766, 103, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SEEDS_CATHERBY, 2, 149),
	PORT_TYRAS_SWORD_DELIVERY_104(8767, 104, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6, 1836),
	PORT_PISCARILIUS_WINE_DELIVERY_105(8768, 105, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_WINE_PORT_PISCARILIUS, 2, 955),
	ARDOUGNE_FUR_DELIVERY_106(8769, 106, PortLocation.ARDOUGNE, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FURS_ARDOUGNE, 1, 1880),
	RED_ROCK_PROTECTIVE_CLOTHING_DELIVERY_107(8770, 107, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_PROTECTIVE_CLOTHING_RED_ROCK, 4, -1),
	ARDOUGNE_RED_CORAL_DELIVERY_108(8771, 108, PortLocation.ARDOUGNE, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_ARDOUGNE, 4, -1),
	PORT_KHAZARD_BREAD_DELIVERY_109(8772, 109, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_BREAD_PORT_KHAZARD, 2, 90),
	ARDOUGNE_FISH_DELIVERY_110(8773, 110, PortLocation.ARDOUGNE, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_FISH_ARDOUGNE, 1, 149),
	SUMMER_SHORE_JEWELLERY_DELIVERY_111(8774, 111, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_JEWELLERY_THE_SUMMER_SHORE, 2, 1475),
	CIVITAS_ILLA_FORTIS_ARTEFACT_DELIVERY_112(8775, 112, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_HISTORICAL_ARTEFACTS_CIVITAS_ILLA_FORTIS, 3, 951),
	VOID_KNIGHTS_OUTPOST_PLATEBODY_DELIVERY_113(8776, 113, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_PLATEBODIES_VOID_KNIGHTS_OUTPOST, 3, 951),
	ARDOUGNE_RUNE_DELIVERY_114(8777, 114, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_RUNES_ARDOUGNE, 2, 574),
	ARDOUGNE_FISH_DELIVERY_115(8778, 115, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_FISH_ARDOUGNE, 2, 140),
	PORT_KHAZARD_PLATEBODY_DELIVERY_116(8779, 116, PortLocation.PORT_KHAZARD, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_PLATEBODIES_PORT_KHAZARD, 1, 149),
	CORSAIR_COVE_DAGGER_DELIVERY_117(8780, 117, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_DAGGERS_CORSAIR_COVE, 3, 425),
	PORT_KHAZARD_VODKA_DELIVERY_118(8781, 118, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_VODKA_PORT_KHAZARD, 2, 793),
	PORT_SARIM_SWORD_DELIVERY_119(8782, 119, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SWORDS_PORT_SARIM, 2, 336),
	PORT_KHAZARD_SWAMP_PASTE_DELIVERY_120(8783, 120, PortLocation.PORT_KHAZARD, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_SWAMP_PASTE_PORT_KHAZARD, 2, 671),
	ARDOUGNE_SAND_DELIVERY_121(8784, 121, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SAND_ARDOUGNE, 3, 301),
	CORSAIR_COVE_KHALI_BREW_DELIVERY_122(8785, 122, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_KHALI_BREWS_CORSAIR_COVE, 3, 456),
	PORT_SARIM_FISH_DELIVERY_123(8786, 123, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_FISH_PORT_SARIM, 2, 379),
	CATHERBY_GOLD_DELIVERY_124(8787, 124, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_GOLD_ORE_CATHERBY, 1, 164),
	PORT_KHAZARD_SECRET_DELIVERY_125(8788, 125, PortLocation.PORT_KHAZARD, PortLocation.CATHERBY, ItemID.CARGO_CRATE_SECRET_STUFF_PORT_KHAZARD, 1, 328),
	CIVITAS_ILLA_FORTIS_PINEAPPLE_DELIVERY_126(8789, 126, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_PINEAPPLES_CIVITAS_ILLA_FORTIS, 2, 859),
	PORT_KHAZARD_HUASCA_DELIVERY_127(8790, 127, PortLocation.PORT_KHAZARD, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_HUASCA_PORT_KHAZARD, 3, 1751),
	RUIN_OF_UNKAH_SHIP_PART_DELIVERY_128(8791, 128, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SHIP_PARTS_RUINS_OF_UNKAH, 3, 776),
	PORT_KHAZARD_ANGLER_OUTFIT_DELIVERY_129(8792, 129, PortLocation.PORT_KHAZARD, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_ANGLER_OUTFIT_PIECES_PORT_KHAZARD, 3, 1551),
	RELLEKKA_DRAGON_BITTER_DELIVERY_130(8793, 130, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_DRAGON_BITTER_RELLEKKA, 4, 4366),
	PORT_PISCARILIUS_PLATEBODY_DELIVERY_131(8794, 131, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_PLATEBODIES_PORT_PISCARILIUS, 2, 888),
	ENTRANA_SAND_DELIVERY_132(8795, 132, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SAND_ENTRANA, 3, 236),
	PORT_KHAZARD_HERB_DELIVERY_133(8796, 133, PortLocation.PORT_KHAZARD, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_HERBS_PORT_KHAZARD, 2, 224),
	PORT_KHAZARD_SCIMITAR_DELIVERY_134(8797, 134, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_SCIMITARS_PORT_KHAZARD, 3, 425),
	CORSAIR_COVE_PLATEBODY_DELIVERY_135(8798, 135, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_PLATEBODIES_CORSAIR_COVE, 2, 793),
	VOID_KNIGHTS_OUTPOST_DRAGONHIDE_DELIVERY_136(8799, 136, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_DRAGONHIDE_VOID_KNIGHTS_OUTPOST, 4, 402),
	CORSAIR_COVE_ARROWTIP_DELIVERY_137(8800, 137, PortLocation.CORSAIR_COVE, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_ARROWTIPS_CORSAIR_COVE, 3, 732),
	PORT_TYRAS_HERB_DELIVERY_138(8801, 138, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_HERBS_PORT_TYRAS, 6, 1781),
	CORSAIR_COVE_MEAT_DELIVERY_139(8802, 139, PortLocation.CORSAIR_COVE, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_BEAR_MEAT_CORSAIR_COVE, 5, 3438),
	PORT_KHAZARD_GUNPOWDER_DELIVERY_140(8803, 140, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_GUNPOWDER_PORT_KHAZARD, 3, 456),
	VOID_KNIGHTS_OUTPOST_RUNE_DELIVERY_141(8804, 141, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_WRATH_RUNES_VOID_KNIGHTS_OUTPOST, 3, 530),
	PORT_TYRAS_SWORD_DELIVERY_142(8805, 142, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6, 5750),
	PORT_PISCARILIUS_JEWELLERY_DELIVERY_143(8806, 143, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, 2, 928),
	CORSAIR_COVE_FISH_DELIVERY_144(8807, 144, PortLocation.CORSAIR_COVE, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_CORSAIR_COVE, 2, 2692),
	CAIRN_ISLE_GOLD_DELIVERY_145(8808, 145, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_GOLD_BARS_CAIRN_ISLE, 2, 283),
	CORSAIR_COVE_GEM_DELIVERY_146(8809, 146, PortLocation.CORSAIR_COVE, PortLocation.CAIRN_ISLE, ItemID.CARGO_CRATE_GEMS_CORSAIR_COVE, 3, 623),
	BRIMHAVEN_JEWELLERY_DELIVERY_147(8810, 147, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_JEWELLERY_BRIMHAVEN, 3, 595),
	CORSAIR_COVE_RUM_DELIVERY_148(8811, 148, PortLocation.CORSAIR_COVE, PortLocation.BRIMHAVEN, ItemID.CARGO_CRATE_RUM_CORSAIR_COVE, 3, 1190),
	PANDEMONIUM_SPICE_DELIVERY_149(8812, 149, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_SPICES_THE_PANDEMONIUM, 3, 595),
	CORSAIR_COVE_SHIP_PART_DELIVERY_150(8813, 150, PortLocation.CORSAIR_COVE, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_SHIP_PARTS_CORSAIR_COVE, 3, 1190),
	CIVITAS_ILLA_FORTIS_BOOK_DELIVERY_151(8814, 151, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_BOOKS_CIVITAS_ILLA_FORTIS, 2, 1105),
	ALDARIN_DAGGER_DELIVERY_152(8815, 152, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_DAGGERS_ALDARIN, 3, 1384),
	PORT_SARIM_CACTI_DELIVERY_153(8816, 153, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_CACTI_PORT_SARIM, 3, 548),
	RUIN_OF_UNKAH_RUNE_DELIVERY_154(8817, 154, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_RUNES_RUINS_OF_UNKAH, 3, 1095),
	SUMMER_SHORE_SANDSTONE_DELIVERY_155(8818, 155, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_SANDSTONE_THE_SUMMER_SHORE, 2, 624),
	RUIN_OF_UNKAH_CORAL_DELIVERY_156(8819, 156, PortLocation.RUINS_OF_UNKAH, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CORAL_RUINS_OF_UNKAH, 3, 1308),
	RED_ROCK_GRANITE_DELIVERY_157(8820, 157, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_GRANITE_RED_ROCK, 3, -1),
	RUIN_OF_UNKAH_PLANK_DELIVERY_158(8821, 158, PortLocation.RUINS_OF_UNKAH, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_PLANKS_RUINS_OF_UNKAH, 3, -1),
	PORT_SARIM_KEBAB_DELIVERY_159(8822, 159, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_KEBABS_PORT_SARIM, 4, 695),
	SUMMER_SHORE_CACTI_DELIVERY_160(8823, 160, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_CACTI_THE_SUMMER_SHORE, 4, 1193),
	RED_ROCK_FISH_DELIVERY_161(8824, 161, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_FISH_RED_ROCK, 4, -1),
	PANDEMONIUM_CACTI_DELIVERY_162(8825, 162, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_CACTI_THE_PANDEMONIUM, 3, 274),
	RUIN_OF_UNKAH_COCKTAIL_DELIVERY_163(8826, 163, PortLocation.RUINS_OF_UNKAH, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_COCKTAILS_RUINS_OF_UNKAH, 2, 487),
	VOID_KNIGHTS_OUTPOST_GRANITE_DELIVERY_164(8827, 164, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_GRANITE_VOID_KNIGHTS_OUTPOST, 4, 860),
	RUIN_OF_UNKAH_JAVELIN_DELIVERY_165(8828, 165, PortLocation.RUINS_OF_UNKAH, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_JAVELINS_RUINS_OF_UNKAH, 4, 1719),
	ARDOUGNE_SILK_DELIVERY_166(8829, 166, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_SILK_ARDOUGNE, 3, 882),
	RUIN_OF_UNKAH_FISHING_SUPPLIES_DELIVERY_167(8830, 167, PortLocation.RUINS_OF_UNKAH, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_FISHING_SUPPLIES_RUINS_OF_UNKAH, 2, 1703),
	BRIMHAVEN_SANDSTONE_DELIVERY_168(8831, 168, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_SANDSTONE_BRIMHAVEN, 4, 1024),
	CATHERBY_SILK_DELIVERY_169(8832, 169, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_SILK_CATHERBY, 2, 882),
	DEEPFIN_POINT_GRANITE_DELIVERY_170(8833, 170, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_GRANITE_DEEPFIN_POINT, 5, 3094),
	RUIN_OF_UNKAH_SHIP_PART_DELIVERY_171(8834, 171, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_SHIP_PARTS_RUINS_OF_UNKAH, 2, 1490),
	RED_ROCK_RUNE_DELIVERY_172(8835, 172, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_RUNES_RED_ROCK, 4, -1),
	VOID_KNIGHTS_OUTPOST_HERB_DELIVERY_173(8836, 173, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_HERBS_VOID_KNIGHTS_OUTPOST, 4, -1),
	SUMMER_SHORE_PEST_REMAINS_DELIVERY_174(8837, 174, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_PEST_REMAINS_THE_SUMMER_SHORE, 3, 933),
	VOID_KNIGHTS_OUTPOST_LOGS_DELIVERY_175(8838, 175, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_LOGS_VOID_KNIGHTS_OUTPOST, 4, 1939),
	DEEPFIN_POINT_JAVELIN_DELIVERY_176(8839, 176, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_JAVELINS_DEEPFIN_POINT, 6, 2094),
	VOID_KNIGHTS_OUTPOST_ORE_DELIVERY_177(8840, 177, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_VOID_KNIGHTS_OUTPOST, 5, 4063),
	RED_ROCK_FISH_DELIVERY_178(8841, 178, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_FISH_RED_ROCK, 5, -1),
	SUMMER_SHORE_JAVELIN_DELIVERY_179(8842, 179, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_JAVELINS_THE_SUMMER_SHORE, 3, 1866),
	DEEPFIN_POINT_PEST_REMAINS_DELIVERY_180(8843, 180, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_PEST_REMAINS_DEEPFIN_POINT, 6, 2158),
	PORT_SARIM_RUNE_DELIVERY_181(8844, 181, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_RUNES_PORT_SARIM, 4, 1024),
	VOID_KNIGHTS_OUTPOST_POTION_DELIVERY_182(8845, 182, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_POTIONS_VOID_KNIGHTS_OUTPOST, 3, 1976),
	CIVITAS_ILLA_FORTIS_RUNE_DELIVERY_183(8846, 183, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_RUNES_CIVITAS_ILLA_FORTIS, 4, 2544),
	VOID_KNIGHTS_OUTPOST_MACE_DELIVERY_184(8847, 184, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_MACES_VOID_KNIGHTS_OUTPOST, 3, 4982),
	PORT_ROBERTS_FISH_DELIVERY_185(8848, 185, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 4, 1280),
	VOID_KNIGHTS_OUTPOST_SEED_DELIVERY_186(8849, 186, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SEEDS_VOID_KNIGHTS_OUTPOST, 3, 3366),
	PORT_KHAZARD_ARROWTIP_DELIVERY_187(8850, 187, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_ARROWTIPS_PORT_KHAZARD, 4, 805),
	PORT_TYRAS_ARROWTIP_DELIVERY_188(8851, 188, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_ARROWTIPS_PORT_TYRAS, 5, 2000),
	CATHERBY_ARROWTIP_DELIVERY_189(8852, 189, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_ARROWTIPS_CATHERBY, 3, 1244),
	VOID_KNIGHTS_OUTPOST_POTION_DELIVERY_190(8853, 190, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_POTIONS_VOID_KNIGHTS_OUTPOST, 4, 1847),
	RUIN_OF_UNKAH_CALQUAT_DELIVERY_191(8854, 191, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CALQUAT_RUINS_OF_UNKAH, 2, 624),
	SUMMER_SHORE_ROPE_DELIVERY_192(8855, 192, PortLocation.SUMMER_SHORE, PortLocation.RUINS_OF_UNKAH, ItemID.CARGO_CRATE_ROPE_THE_SUMMER_SHORE, 2, 1247),
	VOID_KNIGHTS_OUTPOST_CORAL_DELIVERY_193(8856, 193, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CORAL_VOID_KNIGHTS_OUTPOST, 4, 969),
	SUMMER_SHORE_JAVELIN_DELIVERY_194(8857, 194, PortLocation.SUMMER_SHORE, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_JAVELINS_THE_SUMMER_SHORE, 3, 1352),
	PANDEMONIUM_CORAL_DELIVERY_195(8858, 195, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CORAL_THE_PANDEMONIUM, 2, 791),
	SUMMER_SHORE_GEM_DELIVERY_196(8859, 196, PortLocation.SUMMER_SHORE, PortLocation.PANDEMONIUM, ItemID.CARGO_CRATE_GEMS_THE_SUMMER_SHORE, 2, 1582),
	RUIN_OF_UNKAH_FISH_DELIVERY_197(8860, 197, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_FISH_RUINS_OF_UNKAH, 4, 823),
	VOID_KNIGHTS_OUTPOST_SPEAR_DELIVERY_198(8861, 198, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_SPEARS_VOID_KNIGHTS_OUTPOST, 3, 1352),
	PANDEMONIUM_SEA_SHELL_DELIVERY_199(8862, 199, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_SEA_SHELLS_THE_PANDEMONIUM, 3, 988),
	PORT_SARIM_CAMPHOR_DELIVERY_200(8863, 200, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CAMPHOR_LOGS_PORT_SARIM, 3, 1065),
	SUMMER_SHORE_SHIELD_DELIVERY_201(8864, 201, PortLocation.SUMMER_SHORE, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_SHIELDS_THE_SUMMER_SHORE, 2, 2068),
	ALDARIN_CRAB_PASTE_DELIVERY_202(8865, 202, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CRAB_PASTE_ALDARIN, 3, 2144),
	SUMMER_SHORE_POTION_DELIVERY_203(8866, 203, PortLocation.SUMMER_SHORE, PortLocation.ALDARIN, ItemID.CARGO_CRATE_POTIONS_THE_SUMMER_SHORE, 2, 4228),
	PORT_ROBERTS_CORAL_DELIVERY_204(8867, 204, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CORAL_PORT_ROBERTS, 3, 2433),
	SUMMER_SHORE_MEAT_DELIVERY_205(8868, 205, PortLocation.SUMMER_SHORE, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_MEAT_THE_SUMMER_SHORE, 3, 4866),
	DEEPFIN_POINT_CAMPHOR_DELIVERY_206(8869, 206, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CAMPHOR_LOGS_DEEPFIN_POINT, 5, 3344),
	PORT_KHAZARD_CRAB_PASTE_DELIVERY_207(8870, 207, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CRAB_PASTE_PORT_KHAZARD, 2, 1156),
	CIVITAS_ILLA_FORTIS_CORAL_DELIVERY_208(8871, 208, PortLocation.SUMMER_SHORE, PortLocation.SUMMER_SHORE, ItemID.CARGO_CRATE_CORAL_CIVITAS_ILLA_FORTIS, 4, 2597),
	SUMMER_SHORE_PINEAPPLE_DELIVERY_209(8872, 209, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, ItemID.CARGO_CRATE_PINEAPPLES_THE_SUMMER_SHORE, 2, 1582),
	PORT_KHAZARD_RED_CORAL_DELIVERY_210(8873, 210, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_PORT_KHAZARD, 3, -1),
	RED_ROCK_FISH_DELIVERY_211(8874, 211, PortLocation.RED_ROCK, PortLocation.PORT_KHAZARD, ItemID.CARGO_CRATE_FISH_RED_ROCK, 3, -1),
	DEEPFIN_POINT_PLANK_DELIVERY_212(8875, 212, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 6, -1),
	RED_ROCK_ORE_DELIVERY_213(8876, 213, PortLocation.RED_ROCK, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_RED_ROCK, 5, -1),
	PORT_SARIM_RED_CORAL_DELIVERY_214(8877, 214, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_PORT_SARIM, 4, -1),
	RED_ROCK_BATTLEAXE_DELIVERY_215(8878, 215, PortLocation.RED_ROCK, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BATTLEAXES_RED_ROCK, 4, -1),
	PORT_KHAZARD_PLANK_DELIVERY_216(8879, 216, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_PLANKS_PORT_KHAZARD, 3, -1),
	DEEPFIN_POINT_LOGS_DELIVERY_217(8880, 217, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 7, -1),
	PORT_SARIM_FISH_DELIVERY_218(8881, 218, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_FISH_PORT_SARIM, 3, -1),
	PORT_ROBERTS_RED_CORAL_DELIVERY_219(8882, 219, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_PORT_ROBERTS, 4, -1),
	RED_ROCK_SPICE_DELIVERY_220(8883, 220, PortLocation.RED_ROCK, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SPICES_RED_ROCK, 4, -1),
	VOID_KNIGHTS_OUTPOST_ORE_DELIVERY_221(8884, 221, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_ORES_VOID_KNIGHTS_OUTPOST, 4, 4063),
	RED_ROCK_RUNE_DELIVERY_222(8885, 222, PortLocation.RED_ROCK, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_RUNES_RED_ROCK, 3, -1),
	PORT_PISCARILIUS_RED_CORAL_DELIVERY_223(8886, 223, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_PORT_PISCARILIUS, 5, -1),
	RED_ROCK_FISH_DELIVERY_224(8887, 224, PortLocation.RED_ROCK, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_RED_ROCK, 5, -1),
	LANDS_END_FISH_DELIVERY_225(8888, 225, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_FISH_LANDS_END, 4, -1),
	ARDOUGNE_RED_CORAL_DELIVERY_226(8889, 226, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_ARDOUGNE, 4, -1),
	CATHERBY_JEWELLERY_DELIVERY_227(8890, 227, PortLocation.RED_ROCK, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_JEWELLERY_CATHERBY, 3, -1),
	RED_ROCK_FUR_DELIVERY_228(8891, 228, PortLocation.RED_ROCK, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_FURS_RED_ROCK, 6, -1),
	HOSIDIUS_ROPE_DELIVERY_229(8892, 229, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_ROPE_HOSIDIUS, 1, 83),
	LANDS_END_VEGETABLE_DELIVERY_230(8893, 230, PortLocation.LANDS_END, PortLocation.HOSIDIUS, ItemID.CARGO_CRATE_VEGETABLES_LANDS_END, 1, 166),
	PORT_PISCARILIUS_PLANK_DELIVERY_231(8894, 231, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, 1, 230),
	LANDS_END_FISH_DELIVERY_232(8895, 232, PortLocation.LANDS_END, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_LANDS_END, 1, 460),
	PORT_ROBERTS_BERRY_DELIVERY_233(8896, 233, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_BERRIES_PORT_ROBERTS, 4, 640),
	LANDS_END_WINE_DELIVERY_234(8897, 234, PortLocation.LANDS_END, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_WINE_LANDS_END, 3, 1207),
	HOSIDIUS_FABRIC_DELIVERY_235(8898, 235, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_XERICIAN_FABRICS_HOSIDIUS, 1, 83),
	PORT_PISCARILIUS_FUR_DELIVERY_236(8899, 236, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_FURS_PORT_PISCARILIUS, 1, 288),
	PORT_ROBERTS_MEAT_DELIVERY_237(8900, 237, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_MEAT_PORT_ROBERTS, 4, 928),
	PORT_TYRAS_CHINCHOMPA_DELIVERY_238(8901, 238, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_CHINCHOMPAS_PORT_TYRAS, 6, 1969),
	LANDS_END_MEAT_DELIVERY_239(8902, 239, PortLocation.LANDS_END, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_BEAR_MEAT_LANDS_END, 5, 300),
	PRIFDDINAS_FABRIC_DELIVERY_240(8903, 240, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_XERICIAN_FABRICS_PRIFDDINAS, 7, 1997),
	LANDS_END_GEM_DELIVERY_241(8904, 241, PortLocation.LANDS_END, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_GEMS_LANDS_END, 7, 3458),
	PISCATORIS_FUR_DELIVERY_242(8905, 242, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_FURS_PISCATORIS, 8, 1530),
	LANDS_END_FUR_DELIVERY_243(8906, 243, PortLocation.LANDS_END, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_KEBBIT_FUR_LANDS_END, 8, 1906),
	DEEPFIN_POINT_LOGS_DELIVERY_244(8907, 244, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 5, 1546),
	PORT_KHAZARD_CHAINBODY_DELIVERY_245(8908, 245, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_CHAINBODIES_PORT_KHAZARD, 1, 873),
	LUNAR_ISLE_BERRY_DELIVERY_246(8909, 246, PortLocation.LANDS_END, PortLocation.LANDS_END, ItemID.CARGO_CRATE_BERRIES_LUNAR_ISLE, 8, 3025),
	LANDS_END_SWORD_DELIVERY_247(8910, 247, PortLocation.LANDS_END, PortLocation.CORSAIR_COVE, ItemID.CARGO_CRATE_SWORDS_LANDS_END, 2, 2692),
	LANDS_END_FISH_DELIVERY_248(8911, 248, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_LANDS_END, 2, 240),
	PORT_PISCARILIUS_PLANK_DELIVERY_249(8912, 249, PortLocation.PORT_PISCARILIUS, PortLocation.LANDS_END, ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, 1, 460),
	PORT_ROBERTS_FISH_DELIVERY_250(8913, 250, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 3, 640),
	PORT_PISCARILIUS_GIN_DELIVERY_251(8914, 251, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_GIN_PORT_PISCARILIUS, 3, 1280),
	PISCATORIS_FISH_DELIVERY_252(8915, 252, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_PISCATORIS, 8, 1779),
	PORT_PISCARILIUS_FUR_DELIVERY_253(8916, 253, PortLocation.PORT_PISCARILIUS, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_KEBBIT_FUR_PORT_PISCARILIUS, 8, 3558),
	LANDS_END_MEAT_DELIVERY_254(8917, 254, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_MEAT_LANDS_END, 2, 300),
	PORT_ROBERTS_JEWELLERY_DELIVERY_255(8918, 255, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_JEWELLERY_PORT_ROBERTS, 3, 928),
	PISCATORIS_VODKA_DELIVERY_256(8919, 256, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_VODKA_PISCATORIS, 7, -1),
	HOSIDIUS_FISH_DELIVERY_257(8920, 257, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_HOSIDIUS, 2, 175),
	PORT_PISCARILIUS_SEED_DELIVERY_258(8921, 258, PortLocation.PORT_PISCARILIUS, PortLocation.HOSIDIUS, ItemID.CARGO_CRATE_SEEDS_PORT_PISCARILIUS, 2, 350),
	LUNAR_ISLE_FISH_DELIVERY_259(8922, 259, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 7, 1601),
	PORT_PISCARILIUS_BOOK_DELIVERY_260(8923, 260, PortLocation.PORT_PISCARILIUS, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 8, 3345),
	PORT_SARIM_BOOK_DELIVERY_261(8924, 261, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_BOOKS_PORT_SARIM, 1, 906),
	PORT_PISCARILIUS_BOOK_DELIVERY_262(8925, 262, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_SARIM, ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 2, 1838),
	PORT_TYRAS_FUR_DELIVERY_263(8926, 263, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FURS_PORT_TYRAS, 5, 1781),
	MUSA_POINT_IMPORTANT_DELIVERY_264(8927, 264, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_HIGH_IMPORTANCE_MUSA_POINT, 2, 900),
	RELLEKKA_BEER_DELIVERY_265(8928, 265, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_BEER_RELLEKKA, 5, 1831),
	PORT_PISCARILIUS_GEM_DELIVERY_266(8929, 266, PortLocation.PORT_PISCARILIUS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_GEMS_PORT_PISCARILIUS, 6, 3285),
	ALDARIN_PLATEBODY_DELIVERY_267(8930, 267, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_PLATEBODIES_ALDARIN, 3, 1004),
	CIVITAS_ILLA_FORTIS_ORANGE_DELIVERY_268(8931, 268, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.ALDARIN, ItemID.CARGO_CRATE_ORANGES_CIVITAS_ILLA_FORTIS, 2, 1947),
	PORT_PISCARILIUS_MEAT_DELIVERY_269(8932, 269, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_ANTELOPE_MEAT_PORT_PISCARILIUS, 3, 412),
	CIVITAS_ILLA_FORTIS_VEGETABLE_DELIVERY_270(8933, 270, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_VEGETABLES_CIVITAS_ILLA_FORTIS, 3, 825),
	PORT_ROBERTS_GEM_DELIVERY_271(8934, 271, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_GEMS_PORT_ROBERTS, 3, 384),
	CIVITAS_ILLA_FORTIS_TOKEN_DELIVERY_272(8935, 272, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_TOKENS_CIVITAS_ILLA_FORTIS, 4, 841),
	ALDARIN_FUR_DELIVERY_273(8936, 273, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_FURS_ALDARIN, 3, 1207),
	PORT_PISCARILIUS_JEWELLERY_DELIVERY_274(8937, 274, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, 2, 396),
	PORT_ROBERTS_SILK_DELIVERY_275(8938, 275, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_SILK_PORT_ROBERTS, 4, 610),
	DEEPFIN_POINT_WOOL_DELIVERY_276(8939, 276, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_ALPACA_WOOL_DEEPFIN_POINT, 6, 1719),
	CIVITAS_ILLA_FORTIS_ORE_DELIVERY_277(8940, 277, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_CIVITAS_ILLA_FORTIS, 5, 3313),
	PRIFDDINAS_CLOTHES_DELIVERY_278(8941, 278, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_CLOTHES_PRIFDDINAS, 7, 1643),
	CIVITAS_ILLA_FORTIS_SEED_DELIVERY_279(8942, 279, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_SEEDS_CIVITAS_ILLA_FORTIS, 7, 3285),
	SUNSET_COAST_MACE_DELIVERY_280(8943, 280, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_MACES_SUNSET_COAST, 3, 907),
	CIVITAS_ILLA_FORTIS_FISH_DELIVERY_281(8944, 281, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.SUNSET_COAST, ItemID.CARGO_CRATE_FISH_CIVITAS_ILLA_FORTIS, 2, 1757),
	PORT_SARIM_SUNBEAM_ALE_DELIVERY_282(8945, 282, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_SUNBEAM_ALE_PORT_SARIM, 2, 1842),
	ARDOUGNE_SPICE_DELIVERY_283(8946, 283, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_SPICES_ARDOUGNE, 3, 1601),
	SUMMER_SHORE_LEATHER_DELIVERY_284(8947, 284, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_LEATHER_THE_SUMMER_SHORE, 2, 2099),
	CIVITAS_ILLA_FORTIS_RED_CORAL_DELIVERY_285(8948, 285, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_CIVITAS_ILLA_FORTIS, 4, -1),
	SUNSET_COAST_BEER_DELIVERY_286(8949, 286, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_BEER_SUNSET_COAST, 2, 167),
	ALDARIN_FUR_DELIVERY_287(8950, 287, PortLocation.ALDARIN, PortLocation.SUNSET_COAST, ItemID.CARGO_CRATE_FURS_ALDARIN, 2, 335),
	CIVITAS_ILLA_FORTIS_FRUIT_DELIVERY_288(8951, 288, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_FRUIT_CIVITAS_ILLA_FORTIS, 2, 973),
	ALDARIN_SPEAR_DELIVERY_289(8952, 289, PortLocation.ALDARIN, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_SPEARS_ALDARIN, 2, 1947),
	DEEPFIN_POINT_PICKAXE_DELIVERY_290(8953, 290, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_PICKAXES_DEEPFIN_POINT, 6, 1500),
	ALDARIN_NICKEL_DELIVERY_291(8954, 291, PortLocation.ALDARIN, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_NICKEL_ORE_ALDARIN, 6, 3000),
	SUNSET_COAST_WINE_DELIVERY_292(8955, 292, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_WINE_SUNSET_COAST, 4, 274),
	CIVITAS_ILLA_FORTIS_GEM_DELIVERY_293(8956, 293, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_GEMS_CIVITAS_ILLA_FORTIS, 4, 1244),
	DEEPFIN_POINT_MACHINERY_DELIVERY_294(8957, 294, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_MACHINERY_PARTS_DEEPFIN_POINT, 7, 1610),
	PORT_ROBERTS_WINE_DELIVERY_295(8958, 295, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_WINE_PORT_ROBERTS, 3, 1207),
	ALDARIN_JEWELLERY_DELIVERY_296(8959, 296, PortLocation.ALDARIN, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_JEWELLERY_ALDARIN, 3, 2415),
	PRIFDDINAS_POTION_DELIVERY_297(8960, 297, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_POTIONS_PRIFDDINAS, 7, 2802),
	ALDARIN_DYE_DELIVERY_298(8961, 298, PortLocation.ALDARIN, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_DYES_ALDARIN, 7, 5604),
	VOID_KNIGHTS_OUTPOST_POTION_DELIVERY_299(8962, 299, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_POTIONS_VOID_KNIGHTS_OUTPOST, 4, 805),
	ALDARIN_PEST_REMAINS_DELIVERY_300(8963, 300, PortLocation.ALDARIN, PortLocation.VOID_KNIGHTS_OUTPOST, ItemID.CARGO_CRATE_PEST_REMAINS_ALDARIN, 4, 3695),
	PORT_TYRAS_SHIELD_DELIVERY_301(8964, 301, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_SHIELDS_PORT_TYRAS, 5, 2125),
	BRIMHAVEN_WINE_DELIVERY_302(8965, 302, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_WINE_BRIMHAVEN, 2, 1901),
	RELLEKKA_WINE_DELIVERY_303(8966, 303, PortLocation.ALDARIN, PortLocation.ALDARIN, ItemID.CARGO_CRATE_WINE_RELLEKKA, 4, 3718),
	ALDARIN_MONKFISH_DELIVERY_304(8967, 304, PortLocation.ALDARIN, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_MONKFISH_ALDARIN, 9, 8255),
	PORT_PISCARILIUS_CANNONBALL_DELIVERY_305(8968, 305, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_CANNONBALLS_PORT_PISCARILIUS, 4, 677),
	PORT_ROBERTS_FISH_DELIVERY_306(8969, 306, PortLocation.PORT_ROBERTS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 3, 1719),
	CIVITAS_ILLA_FORTIS_SPICE_DELIVERY_307(8970, 307, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SPICES_CIVITAS_ILLA_FORTIS, 3, 384),
	PORT_ROBERTS_FUR_DELIVERY_308(8971, 308, PortLocation.PORT_ROBERTS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_ANTELOPE_FUR_PORT_ROBERTS, 4, 841),
	LANDS_END_ORE_DELIVERY_309(8972, 309, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_ORES_LANDS_END, 4, 640),
	PORT_ROBERTS_SEED_DELIVERY_310(8973, 310, PortLocation.PORT_ROBERTS, PortLocation.LANDS_END, ItemID.CARGO_CRATE_SEEDS_PORT_ROBERTS, 3, 1207),
	PORT_PISCARILIUS_JEWELLERY_DELIVERY_311(8974, 311, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, 3, 1346),
	CIVITAS_ILLA_FORTIS_SHIP_PART_DELIVERY_312(8975, 312, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SHIP_PARTS_CIVITAS_ILLA_FORTIS, 3, 557),
	LANDS_END_SECRET_DELIVERY_313(8976, 313, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SECRET_THINGS_LANDS_END, 4, 928),
	DEEPFIN_POINT_PLANK_DELIVERY_314(8977, 314, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 5, 1438),
	PORT_ROBERTS_ORE_DELIVERY_315(8978, 315, PortLocation.PORT_ROBERTS, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_PORT_ROBERTS, 5, 3188),
	LUNAR_ISLE_FUR_DELIVERY_316(8979, 316, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_FURS_LUNAR_ISLE, 8, 2384),
	PORT_ROBERTS_RUNE_DELIVERY_317(8980, 317, PortLocation.PORT_ROBERTS, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_RUNES_PORT_ROBERTS, 8, -1),
	CATHERBY_SILVER_DELIVERY_318(8981, 318, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SILVER_ORE_CATHERBY, 5, 3915),
	PORT_ROBERTS_HONEY_DELIVERY_319(8982, 319, PortLocation.PORT_ROBERTS, PortLocation.CATHERBY, ItemID.CARGO_CRATE_HONEY_PORT_ROBERTS, 5, 7830),
	PORT_SARIM_SEED_DELIVERY_320(8983, 320, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SEEDS_PORT_SARIM, 5, 4000),
	RELLEKKA_SHIP_PART_DELIVERY_321(8984, 321, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_SHIP_PARTS_RELLEKKA, 4, 2084),
	RED_ROCK_HERB_DELIVERY_322(8985, 322, PortLocation.PORT_ROBERTS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_HERBS_RED_ROCK, 4, -1),
	PORT_ROBERTS_SILK_DELIVERY_323(8986, 323, PortLocation.PORT_ROBERTS, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SILK_PORT_ROBERTS, 3, 6413),
	PORT_ROBERTS_NICKEL_DELIVERY_324(8987, 324, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_NICKEL_ORE_PORT_ROBERTS, 6, 1656),
	DEEPFIN_POINT_FABRIC_DELIVERY_325(8988, 325, PortLocation.DEEPFIN_POINT, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_FABRICS_DEEPFIN_POINT, 5, 3188),
	PORT_TYRAS_MITHRIL_DELIVERY_326(8989, 326, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_MITHRIL_ORE_PORT_TYRAS, 6, 1438),
	DEEPFIN_POINT_LOGS_DELIVERY_327(8990, 327, PortLocation.DEEPFIN_POINT, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 6, 2313),
	ALDARIN_ADAMANTITE_DELIVERY_328(8991, 328, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ADAMANTITE_ORE_ALDARIN, 5, 1438),
	DEEPFIN_POINT_FRUIT_DELIVERY_329(8992, 329, PortLocation.DEEPFIN_POINT, PortLocation.ALDARIN, ItemID.CARGO_CRATE_FRUIT_DEEPFIN_POINT, 6, 3000),
	PORT_ROBERTS_SILVER_DELIVERY_330(8993, 330, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_SILVER_ORE_PORT_ROBERTS, 6, 1707),
	PORT_TYRAS_COAL_DELIVERY_331(8994, 331, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_COAL_PORT_TYRAS, 6, 1482),
	ALDARIN_LEAD_DELIVERY_332(8995, 332, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_LEAD_ORE_ALDARIN, 6, 1546),
	CIVITAS_ILLA_FORTIS_NICKEL_DELIVERY_333(8996, 333, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_NICKEL_ORE_CIVITAS_ILLA_FORTIS, 5, 1656),
	DEEPFIN_POINT_WOOL_DELIVERY_334(8997, 334, PortLocation.DEEPFIN_POINT, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_ALPACA_WOOL_DEEPFIN_POINT, 6, 3438),
	PORT_PISCARILIUS_COAL_DELIVERY_335(8998, 335, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_COAL_PORT_PISCARILIUS, 5, 2469),
	DEEPFIN_POINT_PLANK_DELIVERY_336(8999, 336, PortLocation.DEEPFIN_POINT, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 5, 1933),
	RED_ROCK_COAL_DELIVERY_337(9000, 337, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_COAL_RED_ROCK, 8, -1),
	DEEPFIN_POINT_FABRIC_DELIVERY_338(9001, 338, PortLocation.DEEPFIN_POINT, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_FABRICS_DEEPFIN_POINT, 8, 3188),
	RELLEKKA_LEAD_DELIVERY_339(9002, 339, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_LEAD_ORE_RELLEKKA, 7, 3865),
	DEEPFIN_POINT_WARHAMMER_DELIVERY_340(9003, 340, PortLocation.DEEPFIN_POINT, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_WARHAMMERS_DEEPFIN_POINT, 6, 7601),
	HOSIDIUS_LEAD_DELIVERY_341(9004, 341, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_LEAD_ORE_HOSIDIUS, 7, 2255),
	SUMMER_SHORE_NICKEL_DELIVERY_342(9005, 342, PortLocation.DEEPFIN_POINT, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_NICKEL_ORE_THE_SUMMER_SHORE, 7, -1),
	PRIFDDINAS_LOGS_DELIVERY_343(9006, 343, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_LOGS_PRIFDDINAS, 7, 966),
	PORT_TYRAS_VEGETABLE_DELIVERY_344(9007, 344, PortLocation.PORT_TYRAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_VEGETABLES_PORT_TYRAS, 7, 1933),
	PORT_ROBERTS_FUR_DELIVERY_345(9008, 345, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_FURS_PORT_ROBERTS, 5, 1219),
	PORT_TYRAS_PLATEBODY_DELIVERY_346(9009, 346, PortLocation.PORT_TYRAS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_PLATEBODIES_PORT_TYRAS, 5, 2875),
	DEEPFIN_POINT_PLANK_DELIVERY_347(9010, 347, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 6, 1594),
	PORT_TYRAS_ORE_DELIVERY_348(9011, 348, PortLocation.PORT_TYRAS, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_PORT_TYRAS, 5, 1139),
	PRIFDDINAS_HALBERD_DELIVERY_349(9012, 349, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_HALBERDS_PRIFDDINAS, 6, 902),
	PORT_ROBERTS_BOW_DELIVERY_350(9013, 350, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_BOWS_PORT_ROBERTS, 6, 1281),
	DEEPFIN_POINT_LOGS_DELIVERY_351(9014, 351, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 7, 2875),
	ARDOUGNE_HALBERD_DELIVERY_352(9015, 352, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_HALBERDS_ARDOUGNE, 5, 2813),
	PORT_TYRAS_SWORD_DELIVERY_353(9016, 353, PortLocation.PORT_TYRAS, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6, 2963),
	LANDS_END_FUR_DELIVERY_354(9017, 354, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_FURS_LANDS_END, 5, 1906),
	PORT_TYRAS_SEED_DELIVERY_355(9018, 355, PortLocation.PORT_TYRAS, PortLocation.LANDS_END, ItemID.CARGO_CRATE_SEEDS_PORT_TYRAS, 5, 3813),
	PORT_PISCARILIUS_PLANK_DELIVERY_356(9019, 356, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, 6, 1844),
	PORT_TYRAS_FISH_DELIVERY_357(9020, 357, PortLocation.PORT_TYRAS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_PORT_TYRAS, 5, 3563),
	BRIMHAVEN_MEAT_DELIVERY_358(9021, 358, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_BEAR_MEAT_BRIMHAVEN, 6, 2906),
	LUNAR_ISLE_LOGS_DELIVERY_359(9022, 359, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_LOGS_LUNAR_ISLE, 7, 2598),
	RED_ROCK_SHIP_PART_DELIVERY_360(9023, 360, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_SHIP_PARTS_RED_ROCK, 6, -1),
	PORT_TYRAS_FRUIT_DELIVERY_361(9024, 361, PortLocation.PORT_TYRAS, PortLocation.ALDARIN, ItemID.CARGO_CRATE_FRUIT_PORT_TYRAS, 6, 4375),
	PORT_TYRAS_FABRIC_DELIVERY_362(9025, 362, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_FABRICS_PORT_TYRAS, 6, 902),
	PRIFDDINAS_LOGS_DELIVERY_363(9026, 363, PortLocation.PRIFDDINAS, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_LOGS_PRIFDDINAS, 6, 1804),
	PORT_ROBERTS_LOGS_DELIVERY_364(9027, 364, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_LOGS_PORT_ROBERTS, 7, 1321),
	PRIFDDINAS_FISH_DELIVERY_365(9028, 365, PortLocation.PRIFDDINAS, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_FISH_PRIFDDINAS, 6, 2512),
	ARDOUGNE_CRYSTAL_SEED_DELIVERY_366(9029, 366, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ARDOUGNE, 7, 3543),
	PRIFDDINAS_SILK_DELIVERY_367(9030, 367, PortLocation.PRIFDDINAS, PortLocation.ARDOUGNE, ItemID.CARGO_CRATE_SILK_PRIFDDINAS, 6, 6957),
	PORT_TYRAS_ORE_DELIVERY_368(9031, 368, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_ORES_PORT_TYRAS, 8, 2750),
	PORT_ROBERTS_STAFF_DELIVERY_369(9032, 369, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_STAFFS_PORT_ROBERTS, 7, 1459),
	ARDOUGNE_JEWELLERY_DELIVERY_370(9033, 370, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_JEWELLERY_ARDOUGNE, 9, -1),
	DEEPFIN_POINT_PLANK_DELIVERY_371(9034, 371, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 7, 4938),
	PRIFDDINAS_ORE_DELIVERY_372(9035, 372, PortLocation.PRIFDDINAS, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_ORES_PRIFDDINAS, 6, 3736),
	ALDARIN_CRYSTAL_SEED_DELIVERY_373(9036, 373, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ALDARIN, 7, 2802),
	PRIFDDINAS_POTION_DELIVERY_374(9037, 374, PortLocation.PRIFDDINAS, PortLocation.ALDARIN, ItemID.CARGO_CRATE_POTIONS_PRIFDDINAS, 7, 5604),
	CIVITAS_ILLA_FORTIS_STAFF_DELIVERY_375(9038, 375, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_STAFFS_CIVITAS_ILLA_FORTIS, 6, 1578),
	PRIFDDINAS_SPICE_DELIVERY_376(9039, 376, PortLocation.PRIFDDINAS, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_SPICES_PRIFDDINAS, 7, 3285),
	LUNAR_ISLE_CRYSTAL_SEED_DELIVERY_377(9040, 377, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_CRYSTAL_SEEDS_LUNAR_ISLE, 8, 2171),
	RELLEKKA_PLANK_DELIVERY_378(9041, 378, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_PLANKS_RELLEKKA, 7, 4169),
	VOID_KNIGHTS_OUTPOST_RUNE_DELIVERY_379(9042, 379, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_RUNES_VOID_KNIGHTS_OUTPOST, 6, 2577),
	PRIFDDINAS_BOOK_DELIVERY_380(9043, 380, PortLocation.PRIFDDINAS, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_BOOKS_PRIFDDINAS, 7, 3414),
	ETCETERIA_FISH_DELIVERY_381(9044, 381, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FISH_ETCETERIA, 6, 688),
	RELLEKKA_TEAK_DELIVERY_382(9045, 382, PortLocation.RELLEKKA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_TEAK_LOGS_RELLEKKA, 6, 773),
	NEITIZNOT_COAL_DELIVERY_383(9046, 383, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_COAL_NEITIZNOT, 5, 1000),
	RELLEKKA_ROPE_DELIVERY_384(9047, 384, PortLocation.RELLEKKA, PortLocation.NEITIZNOT, ItemID.CARGO_CRATE_ROPE_RELLEKKA, 5, 2000),
	SUNSET_COAST_WARHAMMER_DELIVERY_385(9048, 385, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_WARHAMMERS_SUNSET_COAST, 5, 3774),
	RELLEKKA_FABRIC_DELIVERY_386(9049, 386, PortLocation.RELLEKKA, PortLocation.SUNSET_COAST, ItemID.CARGO_CRATE_FABRICS_RELLEKKA, 5, 7549),
	ETCETERIA_WARHAMMER_DELIVERY_387(9050, 387, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_WARHAMMERS_ETCETERIA, 7, 773),
	NEITIZNOT_SAND_DELIVERY_388(9051, 388, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_SAND_NEITIZNOT, 6, 1095),
	SUNSET_COAST_FISH_DELIVERY_389(9052, 389, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FISH_SUNSET_COAST, 6, 4250),
	PORT_ROBERTS_FISH_DELIVERY_390(9053, 390, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 5, 2141),
	RELLEKKA_PLANK_DELIVERY_391(9054, 391, PortLocation.RELLEKKA, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_PLANKS_RELLEKKA, 4, 2480),
	PISCATORIS_FUR_DELIVERY_392(9055, 392, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FURS_PISCATORIS, 8, 1530),
	RELLEKKA_MONKFISH_DELIVERY_393(9056, 393, PortLocation.RELLEKKA, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_MONKFISH_RELLEKKA, 7, 2918),
	PORT_PISCARILIUS_FUR_DELIVERY_394(9057, 394, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FURS_PORT_PISCARILIUS, 4, 1775),
	RELLEKKA_REDWOOD_DELIVERY_395(9058, 395, PortLocation.RELLEKKA, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_REDWOOD_LOGS_RELLEKKA, 4, 3549),
	JATIZSO_LOGS_DELIVERY_396(9059, 396, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_LOGS_JATIZSO, 5, 875),
	RELLEKKA_ADAMANTITE_DELIVERY_397(9060, 397, PortLocation.RELLEKKA, PortLocation.JATIZSO, ItemID.CARGO_CRATE_ADAMANTITE_ORE_RELLEKKA, 6, 1875),
	DEEPFIN_POINT_FUR_DELIVERY_398(9061, 398, PortLocation.RELLEKKA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_FURS_DEEPFIN_POINT, 5, 3625),
	RELLEKKA_HALBERD_DELIVERY_399(9062, 399, PortLocation.RELLEKKA, PortLocation.PORT_TYRAS, ItemID.CARGO_CRATE_HALBERDS_RELLEKKA, 6, 5500),
	RELLEKKA_FISH_DELIVERY_400(9063, 400, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FISH_RELLEKKA, 6, 688),
	ETCETERIA_IRON_DELIVERY_401(9064, 401, PortLocation.ETCETERIA, PortLocation.RELLEKKA, ItemID.CARGO_CRATE_IRON_ORE_ETCETERIA, 5, 1250),
	JATIZSO_FISH_DELIVERY_402(9065, 402, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FISH_JATIZSO, 5, 781),
	ETCETERIA_ADAMANTITE_DELIVERY_403(9066, 403, PortLocation.ETCETERIA, PortLocation.JATIZSO, ItemID.CARGO_CRATE_ADAMANTITE_ORE_ETCETERIA, 6, 1688),
	PORT_ROBERTS_TEAK_DELIVERY_404(9067, 404, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_TEAK_LOGS_PORT_ROBERTS, 5, 2375),
	ETCETERIA_FRUIT_DELIVERY_405(9068, 405, PortLocation.ETCETERIA, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_FRUIT_ETCETERIA, 5, 4750),
	RELLEKKA_TEAK_DELIVERY_406(9069, 406, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_TEAK_LOGS_RELLEKKA, 7, 1375),
	JATIZSO_FLAX_DELIVERY_407(9070, 407, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FLAX_JATIZSO, 7, 934),
	PORT_ROBERTS_FLAX_DELIVERY_408(9071, 408, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FLAX_PORT_ROBERTS, 6, 2512),
	PORT_PISCARILIUS_MAHOGANY_DELIVERY_409(9072, 409, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_MAHOGANY_LOGS_PORT_PISCARILIUS, 5, 2031),
	ETCETERIA_PLANK_DELIVERY_410(9073, 410, PortLocation.ETCETERIA, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_PLANKS_ETCETERIA, 6, 4188),
	NEITIZNOT_MAHOGANY_DELIVERY_411(9074, 411, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_MAHOGANY_LOGS_NEITIZNOT, 6, 1125),
	ETCETERIA_YAK_HAIR_DELIVERY_412(9075, 412, PortLocation.ETCETERIA, PortLocation.NEITIZNOT, ItemID.CARGO_CRATE_YAK_HAIR_ETCETERIA, 5, 2125),
	SUNSET_COAST_FABRIC_DELIVERY_413(9076, 413, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FABRICS_SUNSET_COAST, 5, 4188),
	ETCETERIA_SWORD_DELIVERY_414(9077, 414, PortLocation.ETCETERIA, PortLocation.SUNSET_COAST, ItemID.CARGO_CRATE_SWORDS_ETCETERIA, 5, 8375),
	PISCATORIS_FLAX_DELIVERY_415(9078, 415, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_FLAX_PISCATORIS, 8, -1),
	ETCETERIA_MONKFISH_DELIVERY_416(9079, 416, PortLocation.ETCETERIA, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_MONKFISH_ETCETERIA, 9, 3203),
	DEEPFIN_POINT_MAHOGANY_DELIVERY_417(9080, 417, PortLocation.ETCETERIA, PortLocation.ETCETERIA, ItemID.CARGO_CRATE_MAHOGANY_LOGS_DEEPFIN_POINT, 6, 3688),
	ETCETERIA_ONION_DELIVERY_418(9081, 418, PortLocation.ETCETERIA, PortLocation.HOSIDIUS, ItemID.CARGO_CRATE_ONIONS_ETCETERIA, 5, 5250),
	PORT_PISCARILIUS_FABRIC_DELIVERY_419(9082, 419, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_FABRICS_PORT_PISCARILIUS, 7, 1601),
	LUNAR_ISLE_FISH_DELIVERY_420(9083, 420, PortLocation.LUNAR_ISLE, PortLocation.PORT_PISCARILIUS, ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 8, 3345),
	PISCATORIS_FABRIC_DELIVERY_421(9084, 421, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_FABRICS_PISCATORIS, 8, 1245),
	LUNAR_ISLE_FUR_DELIVERY_422(9085, 422, PortLocation.LUNAR_ISLE, PortLocation.PISCATORIS, ItemID.CARGO_CRATE_KEBBIT_FUR_LUNAR_ISLE, 8, 2491),
	PRIFDDINAS_HERB_DELIVERY_423(9086, 423, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_HERBS_PRIFDDINAS, 8, 2171),
	LUNAR_ISLE_POTION_DELIVERY_424(9087, 424, PortLocation.LUNAR_ISLE, PortLocation.PRIFDDINAS, ItemID.CARGO_CRATE_POTIONS_LUNAR_ISLE, 8, 4341),
	PORT_PISCARILIUS_RUNE_DELIVERY_425(9088, 425, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_ASTRAL_RUNES_PORT_PISCARILIUS, 9, 1948),
	PISCATORIS_POTION_DELIVERY_426(9089, 426, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_POTIONS_PISCATORIS, 8, 1391),
	PRIFDDINAS_RUNE_DELIVERY_427(9090, 427, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_ASTRAL_RUNES_PRIFDDINAS, 9, 2504),
	DEEPFIN_POINT_SUQAH_HIDE_DELIVERY_428(9091, 428, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_SUQAH_HIDES_DEEPFIN_POINT, 8, 3665),
	LUNAR_ISLE_COAL_DELIVERY_429(9092, 429, PortLocation.LUNAR_ISLE, PortLocation.DEEPFIN_POINT, ItemID.CARGO_CRATE_COAL_LUNAR_ISLE, 7, 7188),
	PORT_ROBERTS_FABRIC_DELIVERY_430(9093, 430, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_FABRICS_PORT_ROBERTS, 7, 2313),
	LUNAR_ISLE_FISH_DELIVERY_431(9094, 431, PortLocation.LUNAR_ISLE, PortLocation.PORT_ROBERTS, ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 7, 4626),
	CIVITAS_ILLA_FORTIS_RUNE_DELIVERY_432(9095, 432, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_ASTRAL_RUNES_CIVITAS_ILLA_FORTIS, 8, 2989),
	LUNAR_ISLE_FUR_DELIVERY_433(9096, 433, PortLocation.LUNAR_ISLE, PortLocation.CIVITAS_ILLA_FORTIS, ItemID.CARGO_CRATE_ANTELOPE_FUR_LUNAR_ISLE, 7, 5836),
	RED_ROCK_RUNE_DELIVERY_434(9097, 434, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_ASTRAL_RUNES_RED_ROCK, 8, -1),
	LUNAR_ISLE_RED_CORAL_DELIVERY_435(9098, 435, PortLocation.LUNAR_ISLE, PortLocation.RED_ROCK, ItemID.CARGO_CRATE_RED_CORAL_LUNAR_ISLE, 8, -1),
	LANDS_END_GEM_DELIVERY_436(9099, 436, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, ItemID.CARGO_CRATE_GEMS_LANDS_END, 9, -1),
	LUNAR_ISLE_POTION_DELIVERY_437(9100, 437, PortLocation.LUNAR_ISLE, PortLocation.ALDARIN, ItemID.CARGO_CRATE_POTIONS_LUNAR_ISLE, 8, 10017),
	PANDEMONIUM_SHIP_PART_DELIVERY_599(9262, 599, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.SAILING_INTRO_CARGO_CRATE, 1, -1),
	PANDEMONIUM_PIRATE_LOOTY_DELIVERY_600(9263, 600, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, ItemID.PRYING_TIMES_CARGO_CRATE, 1, -1),
	;
	private final int dbrow;
	private final int id;
	private final PortLocation noticeboardLocation;
	private final PortLocation cargoLocation;
	private final Cargo cargo;
	public final int cargoAmount;
	private final int reward;

	private static final Set<Integer> VARBIT_VALUES;
	private static final Map<Integer, CourierTaskData> BY_DBROW = new HashMap<>();

	CourierTaskData(int dbrow, int id, PortLocation noticeboardLocation, PortLocation cargoLocation, int cargoItemId, int cargoAmount, int reward)
	{
		this.dbrow = dbrow;
		this.id = id;
		this.noticeboardLocation = noticeboardLocation;
		this.cargoLocation = cargoLocation;
		this.cargo = Cargo.fromItemId(cargoItemId);
		this.cargoAmount = cargoAmount;
		this.reward = reward;
    }

	/**
	 * Returns the PortPaths (dock markers) for this courier task.
	 * The path is determined by looking up the cargo and delivery locations.
	 */
	public PortPaths getDockMarkers()
	{
		return PortPaths.getPath(cargoLocation, cargo.getDestination());
	}

	/**
	 * Returns true if this is an A-B-A (round-trip) task.
	 * An A-B-A task is one where you start at the noticeboard location,
	 * sail to pick up cargo at a different location, and then deliver it
	 * back to the noticeboard location (A→B→A round trip).
	 * This happens when the delivery destination equals the noticeboard location.
	 */
	public boolean isRoundTripTask()
	{
		return cargo.getDestination() == noticeboardLocation;
	}

	/**
	 * Get the pickup port for this courier task.
	 * This is where the cargo is picked up.
	 */
	public PortLocation getPickupPort()
	{
		return cargoLocation;
	}

	/**
	 * Get the delivery port for this courier task.
	 * This is where the cargo is delivered to.
	 */
	public PortLocation getDeliveryPort()
	{
		return cargo.getDestination();
	}

	/**
	 * Get the cargo type name for this task.
	 * Used for detecting cargo-type conflicts (game prevents holding two tasks 
	 * that deliver the same cargo type).
	 */
	public String getCargoTypeName()
	{
		return cargo.getName();
	}

	/**
	 * Generates the task name dynamically based on delivery location and cargo type.
	 */
	public String getTaskName()
	{
		String port = cargo.getDestination().getTaskName();

		if (cargo.getItemId() == ItemID.CARGO_CRATE_NOTHING_SINISTER_PORT_SARIM)
		{
			return port + " delivery of " + cargo.getName();
		}

		return port + " " + cargo.getName() + " delivery";
	}

	static
	{
		Set<Integer> varbitValues = new HashSet<>();
		for (CourierTaskData p : values())
		{
			varbitValues.add(p.id);
		}
		VARBIT_VALUES = Collections.unmodifiableSet(varbitValues);
	}

	static
	{
		for (CourierTaskData task : values())
		{
			BY_DBROW.put(task.dbrow, task);
		}
	}

	public static CourierTaskData getByDbrow(int dbrow)
	{
		return BY_DBROW.get(dbrow);
	}

	public static boolean isCargoTask(int varbitValue)
	{
		return VARBIT_VALUES.contains(varbitValue);
	}

	public static CourierTaskData fromId(int id)
	{
		for (CourierTaskData task : values())
		{
			if (task.id == id)
				return task;
		}
		return null;
	}

}
