/*
 * Copyright (c) 2025, nucleon <https://github.com/nucleon>
 * Copyright (c) 2025, Cooper Morris <https://github.com/coopermor>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.nucleon.porttasks.enums;

import net.runelite.api.gameval.ItemID;

public enum PortTaskData
{
	PANDEMONIUM_PLATEBODY_DELIVERY_1(1, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.PANDEMONIUM, "Pandemonium platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_THE_PANDEMONIUM, 1),
	PORT_SARIM_SPICE_DELIVERY_2(2, PortLocation.PORT_SARIM, PortLocation.PANDEMONIUM, PortLocation.PORT_SARIM, "Port sarim spice delivery", ItemID.CARGO_CRATE_SPICES_PORT_SARIM, 1),
	MUSA_POINT_LOGS_DELIVERY_3(3, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.MUSA_POINT, "Musa point logs delivery", ItemID.CARGO_CRATE_LOGS_MUSA_POINT, 1),
	PORT_SARIM_LOGS_DELIVERY_4(4, PortLocation.PORT_SARIM, PortLocation.MUSA_POINT, PortLocation.PORT_SARIM, "Port sarim logs delivery", ItemID.CARGO_CRATE_LOGS_PORT_SARIM, 1),
	CATHERBY_FEATHER_DELIVERY_5(5, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.CATHERBY, "Catherby feather delivery", ItemID.CARGO_CRATE_FEATHERS_CATHERBY, 1),
	PORT_SARIM_HONEY_DELIVERY_6(6, PortLocation.PORT_SARIM, PortLocation.CATHERBY, PortLocation.PORT_SARIM, "Port sarim honey delivery", ItemID.CARGO_CRATE_HONEY_PORT_SARIM, 1),
	PANDEMONIUM_BATTLEAXE_DELIVERY_7(7, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.PANDEMONIUM, "Pandemonium battleaxe delivery", ItemID.CARGO_CRATE_BATTLEAXES_THE_PANDEMONIUM, 1),
	MUSA_POINT_FISH_DELIVERY_8(8, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.MUSA_POINT, "Musa point fish delivery", ItemID.CARGO_CRATE_FISH_MUSA_POINT, 2),
	CATHERBY_POTATO_DELIVERY_9(9, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.CATHERBY, "Catherby potato delivery", ItemID.CARGO_CRATE_POTATOES_CATHERBY, 1),
	ARDOUGNE_SALAMANDER_DELIVERY_10(10, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.ARDOUGNE, "Ardougne salamander delivery", ItemID.CARGO_CRATE_SALAMANDERS_ARDOUGNE, 1),
	PORT_SARIM_SEED_DELIVERY_11(11, PortLocation.PORT_SARIM, PortLocation.ARDOUGNE, PortLocation.PORT_SARIM, "Port sarim seed delivery", ItemID.CARGO_CRATE_SEEDS_PORT_SARIM, 1),
	PORT_KHAZARD_SWAMP_PASTE_DELIVERY_12(12, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.PORT_KHAZARD, "Port khazard swamp paste delivery", ItemID.CARGO_CRATE_SWAMP_PASTE_PORT_KHAZARD, 1),
	PORT_SARIM_SWORD_DELIVERY_13(13, PortLocation.PORT_SARIM, PortLocation.PORT_KHAZARD, PortLocation.PORT_SARIM, "Port sarim sword delivery", ItemID.CARGO_CRATE_SWORDS_PORT_SARIM, 1),
	BRIMHAVEN_VODKA_DELIVERY_14(14, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.BRIMHAVEN, "Brimhaven vodka delivery", ItemID.CARGO_CRATE_VODKA_BRIMHAVEN, 1),
	PORT_SARIM_DELIVERY_OF_NOTHING_SINISTER_15(15, PortLocation.PORT_SARIM, PortLocation.BRIMHAVEN, PortLocation.PORT_SARIM, "Port sarim delivery of nothing sinister", ItemID.CARGO_CRATE_NOTHING_SINISTER_PORT_SARIM, 2),
	PORT_PISCARILIUS_BOOK_DELIVERY_16(16, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.PORT_PISCARILIUS, "Port piscarilius book delivery", ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 2),
	RUIN_OF_UNKAH_RUNE_DELIVERY_17(17, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah rune delivery", ItemID.CARGO_CRATE_RUNES_RUINS_OF_UNKAH, 2),
	RELLEKKA_PIE_DELIVERY_18(18, PortLocation.PORT_SARIM, PortLocation.PORT_SARIM, PortLocation.RELLEKKA, "Rellekka pie delivery", ItemID.CARGO_CRATE_PIES_RELLEKKA, 4),
	PORT_SARIM_PEST_REMAINS_DELIVERY_19(19, PortLocation.PORT_SARIM, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.PORT_SARIM, "Port sarim pest remains delivery", ItemID.CARGO_CRATE_PEST_REMAINS_PORT_SARIM, 3),
	PORT_SARIM_JEWELLERY_DELIVERY_20(20, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.PORT_SARIM, "Port sarim jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_PORT_SARIM, 1),
	PANDEMONIUM_STEEL_DELIVERY_21(21, PortLocation.PANDEMONIUM, PortLocation.PORT_SARIM, PortLocation.PANDEMONIUM, "Pandemonium steel delivery", ItemID.CARGO_CRATE_STEEL_BARS_THE_PANDEMONIUM, 1),
	MUSA_POINT_ROTTEN_BANANA_DELIVERY_22(22, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.MUSA_POINT, "Musa point rotten banana delivery", ItemID.CARGO_CRATE_ROTTEN_BANANAS_MUSA_POINT, 1),
	PANDEMONIUM_RUM_DELIVERY_23(23, PortLocation.PANDEMONIUM, PortLocation.MUSA_POINT, PortLocation.PANDEMONIUM, "Pandemonium rum delivery", ItemID.CARGO_CRATE_RUM_THE_PANDEMONIUM, 1),
	BRIMHAVEN_JEWELLERY_DELIVERY_24(24, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.BRIMHAVEN, "Brimhaven jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_BRIMHAVEN, 2),
	PANDEMONIUM_PINEAPPLE_DELIVERY_25(25, PortLocation.PANDEMONIUM, PortLocation.BRIMHAVEN, PortLocation.PANDEMONIUM, "Pandemonium pineapple delivery", ItemID.CARGO_CRATE_PINEAPPLES_THE_PANDEMONIUM, 2),
	PORT_SARIM_FISH_DELIVERY_26(26, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.PORT_SARIM, "Port sarim fish delivery", ItemID.CARGO_CRATE_FISH_PORT_SARIM, 1),
	MUSA_POINT_SHIP_PART_DELIVERY_27(27, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.MUSA_POINT, "Musa point ship part delivery", ItemID.CARGO_CRATE_SHIP_PARTS_MUSA_POINT, 1),
	BRIMHAVEN_CACTI_DELIVERY_28(28, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.BRIMHAVEN, "Brimhaven cacti delivery", ItemID.CARGO_CRATE_CACTI_BRIMHAVEN, 1),
	CATHERBY_GROG_DELIVERY_29(29, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.CATHERBY, "Catherby grog delivery", ItemID.CARGO_CRATE_GROG_CATHERBY, 1),
	PANDEMONIUM_ARROWTIP_DELIVERY_30(30, PortLocation.PANDEMONIUM, PortLocation.CATHERBY, PortLocation.PANDEMONIUM, "Pandemonium arrowtip delivery", ItemID.CARGO_CRATE_ARROWTIPS_THE_PANDEMONIUM, 1),
	CORSAIR_COVE_SCIMITAR_DELIVERY_31(31, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.CORSAIR_COVE, "Corsair cove scimitar delivery", ItemID.CARGO_CRATE_SCIMITARS_CORSAIR_COVE, 3),
	PANDEMONIUM_GOLD_DELIVERY_32(32, PortLocation.PANDEMONIUM, PortLocation.CORSAIR_COVE, PortLocation.PANDEMONIUM, "Pandemonium gold delivery", ItemID.CARGO_CRATE_GOLD_BARS_THE_PANDEMONIUM, 3),
	PORT_KHAZARD_KYATT_TEETH_DELIVERY_33(33, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.PORT_KHAZARD, "Port khazard kyatt teeth delivery", ItemID.CARGO_CRATE_KYATT_TEETH_PORT_KHAZARD, 1),
	PANDEMONIUM_SWAMP_PASTE_DELIVERY_34(34, PortLocation.PANDEMONIUM, PortLocation.PORT_KHAZARD, PortLocation.PANDEMONIUM, "Pandemonium swamp paste delivery", ItemID.CARGO_CRATE_SWAMP_PASTE_THE_PANDEMONIUM, 1),
	RUIN_OF_UNKAH_COCKTAIL_DELIVERY_35(35, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah cocktail delivery", ItemID.CARGO_CRATE_COCKTAILS_RUINS_OF_UNKAH, 2),
	PANDEMONIUM_GRANITE_DELIVERY_36(36, PortLocation.PANDEMONIUM, PortLocation.RUINS_OF_UNKAH, PortLocation.PANDEMONIUM, "Pandemonium granite delivery", ItemID.CARGO_CRATE_GRANITE_THE_PANDEMONIUM, 3),
	CAIRN_ISLE_SECRET_DELIVERY_37(37, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.CAIRN_ISLE, "Cairn isle secret delivery", ItemID.CARGO_CRATE_SECRET_STUFF_CAIRN_ISLE, 3),
	ARDOUGNE_SAND_DELIVERY_38(38, PortLocation.PANDEMONIUM, PortLocation.PANDEMONIUM, PortLocation.ARDOUGNE, "Ardougne sand delivery", ItemID.CARGO_CRATE_SAND_ARDOUGNE, 1),
	PORT_SARIM_COCONUT_DELIVERY_39(39, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.PORT_SARIM, "Port sarim coconut delivery", ItemID.CARGO_CRATE_COCONUTS_PORT_SARIM, 1),
	MUSA_POINT_BANANA_DELIVERY_40(40, PortLocation.MUSA_POINT, PortLocation.PORT_SARIM, PortLocation.MUSA_POINT, "Musa point banana delivery", ItemID.CARGO_CRATE_BANANAS_MUSA_POINT, 1),
	PANDEMONIUM_BANANA_DELIVERY_41(41, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.PANDEMONIUM, "Pandemonium banana delivery", ItemID.CARGO_CRATE_BANANAS_THE_PANDEMONIUM, 1),
	MUSA_POINT_EYE_PATCH_DELIVERY_42(42, PortLocation.MUSA_POINT, PortLocation.PANDEMONIUM, PortLocation.MUSA_POINT, "Musa point eye patch delivery", ItemID.CARGO_CRATE_EYE_PATCHES_MUSA_POINT, 1),
	BRIMHAVEN_RUM_DELIVERY_43(43, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.BRIMHAVEN, "Brimhaven rum delivery", ItemID.CARGO_CRATE_RUM_BRIMHAVEN, 1),
	MUSA_POINT_MAHOGANY_DELIVERY_44(44, PortLocation.MUSA_POINT, PortLocation.BRIMHAVEN, PortLocation.MUSA_POINT, "Musa point mahogany delivery", ItemID.CARGO_CRATE_MAHOGANY_LOGS_MUSA_POINT, 1),
	PORT_SARIM_LOGS_DELIVERY_45(45, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.PORT_SARIM, "Port sarim logs delivery", ItemID.CARGO_CRATE_LOGS_PORT_SARIM, 1),
	PANDEMONIUM_RUM_DELIVERY_46(46, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.PANDEMONIUM, "Pandemonium rum delivery", ItemID.CARGO_CRATE_RUM_THE_PANDEMONIUM, 2),
	BRIMHAVEN_SILVER_DELIVERY_47(47, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.BRIMHAVEN, "Brimhaven silver delivery", ItemID.CARGO_CRATE_SILVER_ORE_BRIMHAVEN, 2),
	CATHERBY_COCONUT_DELIVERY_48(48, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.CATHERBY, "Catherby coconut delivery", ItemID.CARGO_CRATE_COCONUTS_CATHERBY, 1),
	MUSA_POINT_HONEY_DELIVERY_49(49, PortLocation.MUSA_POINT, PortLocation.CATHERBY, PortLocation.MUSA_POINT, "Musa point honey delivery", ItemID.CARGO_CRATE_HONEY_MUSA_POINT, 2),
	ENTRANA_BANANA_DELIVERY_50(50, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.ENTRANA, "Entrana banana delivery", ItemID.CARGO_CRATE_BANANAS_ENTRANA, 2),
	MUSA_POINT_BEER_GLASS_DELIVERY_51(51, PortLocation.MUSA_POINT, PortLocation.ENTRANA, PortLocation.MUSA_POINT, "Musa point beer glass delivery", ItemID.CARGO_CRATE_BEER_GLASSES_MUSA_POINT, 2),
	ARDOUGNE_BANANA_DELIVERY_52(52, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.ARDOUGNE, "Ardougne banana delivery", ItemID.CARGO_CRATE_BANANAS_ARDOUGNE, 2),
	MUSA_POINT_SILK_DELIVERY_53(53, PortLocation.MUSA_POINT, PortLocation.ARDOUGNE, PortLocation.MUSA_POINT, "Musa point silk delivery", ItemID.CARGO_CRATE_SILK_MUSA_POINT, 1),
	CORSAIR_COVE_PEG_LEG_DELIVERY_54(54, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.CORSAIR_COVE, "Corsair cove peg leg delivery", ItemID.CARGO_CRATE_PEG_LEGS_CORSAIR_COVE, 2),
	SUMMER_SHORE_BANANA_DELIVERY_55(55, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.SUMMER_SHORE, "Summer shore banana delivery", ItemID.CARGO_CRATE_BANANAS_THE_SUMMER_SHORE, 2),
	PORT_TYRAS_SNAKESKIN_DELIVERY_56(56, PortLocation.MUSA_POINT, PortLocation.MUSA_POINT, PortLocation.PORT_TYRAS, "Port tyras snakeskin delivery", ItemID.CARGO_CRATE_SNAKESKIN_PORT_TYRAS, 6),
	MUSA_POINT_SECRET_DELIVERY_57(57, PortLocation.MUSA_POINT, PortLocation.PORT_KHAZARD, PortLocation.MUSA_POINT, "Musa point secret delivery", ItemID.CARGO_CRATE_SECRET_STUFF_MUSA_POINT, 2),
	PORT_SARIM_FLAX_DELIVERY_58(58, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PORT_SARIM, "Port sarim flax delivery", ItemID.CARGO_CRATE_FLAX_PORT_SARIM, 1),
	CATHERBY_BAIT_DELIVERY_59(59, PortLocation.CATHERBY, PortLocation.PORT_SARIM, PortLocation.CATHERBY, "Catherby bait delivery", ItemID.CARGO_CRATE_BAIT_CATHERBY, 1),
	ARDOUGNE_FISH_DELIVERY_60(60, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.ARDOUGNE, "Ardougne fish delivery", ItemID.CARGO_CRATE_FISH_ARDOUGNE, 2),
	CATHERBY_ARROWTIP_DELIVERY_61(61, PortLocation.CATHERBY, PortLocation.ARDOUGNE, PortLocation.CATHERBY, "Catherby arrowtip delivery", ItemID.CARGO_CRATE_ARROWTIPS_CATHERBY, 2),
	PORT_KHAZARD_BOW_DELIVERY_62(62, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PORT_KHAZARD, "Port khazard bow delivery", ItemID.CARGO_CRATE_BOWS_PORT_KHAZARD, 2),
	CATHERBY_GLASSMAKING_SUPPLIES_DELIVERY_63(63, PortLocation.CATHERBY, PortLocation.PORT_KHAZARD, PortLocation.CATHERBY, "Catherby glassmaking supplies delivery", ItemID.CARGO_CRATE_GLASSMAKING_SUPPLIES_CATHERBY, 2),
	PORT_SARIM_BEER_DELIVERY_64(64, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PORT_SARIM, "Port sarim beer delivery", ItemID.CARGO_CRATE_BEER_PORT_SARIM, 1),
	ARDOUGNE_POISON_DELIVERY_65(65, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.ARDOUGNE, "Ardougne poison delivery", ItemID.CARGO_CRATE_POISON_ARDOUGNE, 1),
	PORT_KHAZARD_COAL_DELIVERY_66(66, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PORT_KHAZARD, "Port khazard coal delivery", ItemID.CARGO_CRATE_COAL_PORT_KHAZARD, 3),
	ENTRANA_BARLEY_DELIVERY_67(67, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.ENTRANA, "Entrana barley delivery", ItemID.CARGO_CRATE_BARLEY_ENTRANA, 2),
	CATHERBY_VIAL_DELIVERY_68(68, PortLocation.CATHERBY, PortLocation.ENTRANA, PortLocation.CATHERBY, "Catherby vial delivery", ItemID.CARGO_CRATE_VIALS_CATHERBY, 2),
	PANDEMONIUM_WAX_DELIVERY_69(69, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PANDEMONIUM, "Pandemonium wax delivery", ItemID.CARGO_CRATE_WAX_THE_PANDEMONIUM, 1),
	CATHERBY_COCONUT_DELIVERY_70(70, PortLocation.CATHERBY, PortLocation.PANDEMONIUM, PortLocation.CATHERBY, "Catherby coconut delivery", ItemID.CARGO_CRATE_COCONUTS_CATHERBY, 1),
	BRIMHAVEN_FISH_DELIVERY_71(71, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.BRIMHAVEN, "Brimhaven fish delivery", ItemID.CARGO_CRATE_FISH_BRIMHAVEN, 1),
	CATHERBY_KARAMBWAN_DELIVERY_72(72, PortLocation.CATHERBY, PortLocation.BRIMHAVEN, PortLocation.CATHERBY, "Catherby karambwan delivery", ItemID.CARGO_CRATE_KARAMBWANS_CATHERBY, 1),
	MUSA_POINT_LOBSTER_DELIVERY_73(73, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.MUSA_POINT, "Musa point lobster delivery", ItemID.CARGO_CRATE_LOBSTERS_MUSA_POINT, 2),
	CATHERBY_BANANA_DELIVERY_74(74, PortLocation.CATHERBY, PortLocation.MUSA_POINT, PortLocation.CATHERBY, "Catherby banana delivery", ItemID.CARGO_CRATE_BANANAS_CATHERBY, 2),
	PORT_PISCARILIUS_HONEY_DELIVERY_75(75, PortLocation.CATHERBY, PortLocation.CATHERBY, PortLocation.PORT_PISCARILIUS, "Port piscarilius honey delivery", ItemID.CARGO_CRATE_HONEY_PORT_PISCARILIUS, 1),
	CATHERBY_JAVELIN_DELIVERY_76(76, PortLocation.CATHERBY, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.CATHERBY, "Catherby javelin delivery", ItemID.CARGO_CRATE_JAVELINS_CATHERBY, 3),
	MUSA_POINT_COCKTAIL_DELIVERY_77(77, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.MUSA_POINT, "Musa point cocktail delivery", ItemID.CARGO_CRATE_COCKTAILS_MUSA_POINT, 2),
	BRIMHAVEN_FISH_DELIVERY_78(78, PortLocation.BRIMHAVEN, PortLocation.MUSA_POINT, PortLocation.BRIMHAVEN, "Brimhaven fish delivery", ItemID.CARGO_CRATE_FISH_BRIMHAVEN, 1),
	PORT_KHAZARD_SPEAR_DELIVERY_79(79, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.PORT_KHAZARD, "Port khazard spear delivery", ItemID.CARGO_CRATE_SPEARS_PORT_KHAZARD, 1),
	BRIMHAVEN_IRON_DELIVERY_80(80, PortLocation.BRIMHAVEN, PortLocation.PORT_KHAZARD, PortLocation.BRIMHAVEN, "Brimhaven iron delivery", ItemID.CARGO_CRATE_IRON_BARS_BRIMHAVEN, 2),
	CORSAIR_COVE_SWORD_DELIVERY_81(81, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.CORSAIR_COVE, "Corsair cove sword delivery", ItemID.CARGO_CRATE_SWORDS_CORSAIR_COVE, 3),
	BRIMHAVEN_GEM_DELIVERY_82(82, PortLocation.BRIMHAVEN, PortLocation.CORSAIR_COVE, PortLocation.BRIMHAVEN, "Brimhaven gem delivery", ItemID.CARGO_CRATE_GEMS_BRIMHAVEN, 2),
	MUSA_POINT_MEAT_DELIVERY_83(83, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.MUSA_POINT, "Musa point meat delivery", ItemID.CARGO_CRATE_MEAT_MUSA_POINT, 1),
	PORT_KHAZARD_FRUIT_DELIVERY_84(84, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.PORT_KHAZARD, "Port khazard fruit delivery", ItemID.CARGO_CRATE_FRUIT_PORT_KHAZARD, 3),
	CORSAIR_COVE_BEER_DELIVERY_85(85, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.CORSAIR_COVE, "Corsair cove beer delivery", ItemID.CARGO_CRATE_BEER_CORSAIR_COVE, 3),
	PANDEMONIUM_MEAT_DELIVERY_86(86, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.PANDEMONIUM, "Pandemonium meat delivery", ItemID.CARGO_CRATE_MEAT_THE_PANDEMONIUM, 1),
	BRIMHAVEN_SPICE_DELIVERY_87(87, PortLocation.BRIMHAVEN, PortLocation.PANDEMONIUM, PortLocation.BRIMHAVEN, "Brimhaven spice delivery", ItemID.CARGO_CRATE_SPICES_BRIMHAVEN, 2),
	CATHERBY_PINEAPPLE_DELIVERY_88(88, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.CATHERBY, "Catherby pineapple delivery", ItemID.CARGO_CRATE_PINEAPPLES_CATHERBY, 2),
	BRIMHAVEN_COMPOST_DELIVERY_89(89, PortLocation.BRIMHAVEN, PortLocation.CATHERBY, PortLocation.BRIMHAVEN, "Brimhaven compost delivery", ItemID.CARGO_CRATE_COMPOST_BRIMHAVEN, 1),
	RED_ROCK_KARAMBWAN_DELIVERY_90(90, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.RED_ROCK, "Red rock karambwan delivery", ItemID.CARGO_CRATE_KARAMBWANS_RED_ROCK, 3),
	BRIMHAVEN_MACHINERY_DELIVERY_91(91, PortLocation.BRIMHAVEN, PortLocation.RED_ROCK, PortLocation.BRIMHAVEN, "Brimhaven machinery delivery", ItemID.CARGO_CRATE_MACHINERY_PARTS_BRIMHAVEN, 4),
	PORT_SARIM_AMULET_DELIVERY_92(92, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.PORT_SARIM, "Port sarim amulet delivery", ItemID.CARGO_CRATE_AMULETS_PORT_SARIM, 2),
	ARDOUGNE_FISH_DELIVERY_93(93, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.ARDOUGNE, "Ardougne fish delivery", ItemID.CARGO_CRATE_FISH_ARDOUGNE, 1),
	CIVITAS_ILLA_FORTIS_PINEAPPLE_DELIVERY_94(94, PortLocation.BRIMHAVEN, PortLocation.BRIMHAVEN, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis pineapple delivery", ItemID.CARGO_CRATE_PINEAPPLES_CIVITAS_ILLA_FORTIS, 3),
	BRIMHAVEN_CAMPHOR_DELIVERY_95(95, PortLocation.BRIMHAVEN, PortLocation.SUMMER_SHORE, PortLocation.BRIMHAVEN, "Brimhaven camphor delivery", ItemID.CARGO_CRATE_CAMPHOR_LOGS_BRIMHAVEN, 3),
	BRIMHAVEN_SPICE_DELIVERY_96(96, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.BRIMHAVEN, "Brimhaven spice delivery", ItemID.CARGO_CRATE_SPICES_BRIMHAVEN, 1),
	ARDOUGNE_GOLD_DELIVERY_97(97, PortLocation.ARDOUGNE, PortLocation.BRIMHAVEN, PortLocation.ARDOUGNE, "Ardougne gold delivery", ItemID.CARGO_CRATE_GOLD_ORE_ARDOUGNE, 1),
	CATHERBY_FUR_DELIVERY_98(98, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.CATHERBY, "Catherby fur delivery", ItemID.CARGO_CRATE_FURS_CATHERBY, 1),
	ARDOUGNE_ARROWTIP_DELIVERY_99(99, PortLocation.ARDOUGNE, PortLocation.CATHERBY, PortLocation.ARDOUGNE, "Ardougne arrowtip delivery", ItemID.CARGO_CRATE_ARROWTIPS_ARDOUGNE, 1),
	PORT_TYRAS_PLATEBODY_DELIVERY_100(100, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.PORT_TYRAS, "Port tyras platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_PORT_TYRAS, 6),
	ARDOUGNE_MEAT_DELIVERY_101(101, PortLocation.ARDOUGNE, PortLocation.PORT_TYRAS, PortLocation.ARDOUGNE, "Ardougne meat delivery", ItemID.CARGO_CRATE_RABBIT_MEAT_ARDOUGNE, 5),
	BRIMHAVEN_BEER_DELIVERY_102(102, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.BRIMHAVEN, "Brimhaven beer delivery", ItemID.CARGO_CRATE_BEER_BRIMHAVEN, 3),
	CATHERBY_SEED_DELIVERY_103(103, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.CATHERBY, "Catherby seed delivery", ItemID.CARGO_CRATE_SEEDS_CATHERBY, 2),
	PORT_TYRAS_SWORD_DELIVERY_104(104, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.PORT_TYRAS, "Port tyras sword delivery", ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6),
	PORT_PISCARILIUS_WINE_DELIVERY_105(105, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.PORT_PISCARILIUS, "Port piscarilius wine delivery", ItemID.CARGO_CRATE_WINE_PORT_PISCARILIUS, 2),
	ARDOUGNE_FUR_DELIVERY_106(106, PortLocation.ARDOUGNE, PortLocation.PORT_PISCARILIUS, PortLocation.ARDOUGNE, "Ardougne fur delivery", ItemID.CARGO_CRATE_FURS_ARDOUGNE, 1),
	RED_ROCK_PROTECTIVE_CLOTHING_DELIVERY_107(107, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.RED_ROCK, "Red rock protective clothing delivery", ItemID.CARGO_CRATE_PROTECTIVE_CLOTHING_RED_ROCK, 4),
	ARDOUGNE_RED_CORAL_DELIVERY_108(108, PortLocation.ARDOUGNE, PortLocation.RED_ROCK, PortLocation.ARDOUGNE, "Ardougne red coral delivery", ItemID.CARGO_CRATE_RED_CORAL_ARDOUGNE, 4),
	PORT_KHAZARD_BREAD_DELIVERY_109(109, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.PORT_KHAZARD, "Port khazard bread delivery", ItemID.CARGO_CRATE_BREAD_PORT_KHAZARD, 2),
	ARDOUGNE_FISH_DELIVERY_110(110, PortLocation.ARDOUGNE, PortLocation.PORT_KHAZARD, PortLocation.ARDOUGNE, "Ardougne fish delivery", ItemID.CARGO_CRATE_FISH_ARDOUGNE, 1),
	SUMMER_SHORE_JEWELLERY_DELIVERY_111(111, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.SUMMER_SHORE, "Summer shore jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_THE_SUMMER_SHORE, 2),
	CIVITAS_ILLA_FORTIS_ARTEFACT_DELIVERY_112(112, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis artefact delivery", ItemID.CARGO_CRATE_HISTORICAL_ARTEFACTS_CIVITAS_ILLA_FORTIS, 3),
	VOID_KNIGHTS_OUTPOST_PLATEBODY_DELIVERY_113(113, PortLocation.ARDOUGNE, PortLocation.ARDOUGNE, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_VOID_KNIGHTS_OUTPOST, 3),
	ARDOUGNE_RUNE_DELIVERY_114(114, PortLocation.ARDOUGNE, PortLocation.PORT_SARIM, PortLocation.ARDOUGNE, "Ardougne rune delivery", ItemID.CARGO_CRATE_RUNES_ARDOUGNE, 2),
	ARDOUGNE_FISH_DELIVERY_115(115, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.ARDOUGNE, "Ardougne fish delivery", ItemID.CARGO_CRATE_FISH_ARDOUGNE, 2),
	PORT_KHAZARD_PLATEBODY_DELIVERY_116(116, PortLocation.PORT_KHAZARD, PortLocation.ARDOUGNE, PortLocation.PORT_KHAZARD, "Port khazard platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_PORT_KHAZARD, 1),
	CORSAIR_COVE_DAGGER_DELIVERY_117(117, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, "Corsair cove dagger delivery", ItemID.CARGO_CRATE_DAGGERS_CORSAIR_COVE, 3),
	PORT_KHAZARD_VODKA_DELIVERY_118(118, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, PortLocation.PORT_KHAZARD, "Port khazard vodka delivery", ItemID.CARGO_CRATE_VODKA_PORT_KHAZARD, 2),
	PORT_SARIM_SWORD_DELIVERY_119(119, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.PORT_SARIM, "Port sarim sword delivery", ItemID.CARGO_CRATE_SWORDS_PORT_SARIM, 2),
	PORT_KHAZARD_SWAMP_PASTE_DELIVERY_120(120, PortLocation.PORT_KHAZARD, PortLocation.PORT_SARIM, PortLocation.PORT_KHAZARD, "Port khazard swamp paste delivery", ItemID.CARGO_CRATE_SWAMP_PASTE_PORT_KHAZARD, 2),
	ARDOUGNE_SAND_DELIVERY_121(121, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.ARDOUGNE, "Ardougne sand delivery", ItemID.CARGO_CRATE_SAND_ARDOUGNE, 3),
	CORSAIR_COVE_KHALI_BREW_DELIVERY_122(122, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, "Corsair cove khali brew delivery", ItemID.CARGO_CRATE_KHALI_BREWS_CORSAIR_COVE, 3),
	PORT_SARIM_FISH_DELIVERY_123(123, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.PORT_SARIM, "Port sarim fish delivery", ItemID.CARGO_CRATE_FISH_PORT_SARIM, 2),
	CATHERBY_GOLD_DELIVERY_124(124, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.CATHERBY, "Catherby gold delivery", ItemID.CARGO_CRATE_GOLD_ORE_CATHERBY, 1),
	PORT_KHAZARD_SECRET_DELIVERY_125(125, PortLocation.PORT_KHAZARD, PortLocation.CATHERBY, PortLocation.PORT_KHAZARD, "Port khazard secret delivery", ItemID.CARGO_CRATE_SECRET_STUFF_PORT_KHAZARD, 1),
	CIVITAS_ILLA_FORTIS_PINEAPPLE_DELIVERY_126(126, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis pineapple delivery", ItemID.CARGO_CRATE_PINEAPPLES_CIVITAS_ILLA_FORTIS, 2),
	PORT_KHAZARD_HUASCA_DELIVERY_127(127, PortLocation.PORT_KHAZARD, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_KHAZARD, "Port khazard huasca delivery", ItemID.CARGO_CRATE_HUASCA_PORT_KHAZARD, 3),
	RUIN_OF_UNKAH_SHIP_PART_DELIVERY_128(128, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah ship part delivery", ItemID.CARGO_CRATE_SHIP_PARTS_RUINS_OF_UNKAH, 3),
	PORT_KHAZARD_ANGLER_OUTFIT_DELIVERY_129(129, PortLocation.PORT_KHAZARD, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_KHAZARD, "Port khazard angler outfit delivery", ItemID.CARGO_CRATE_ANGLER_OUTFIT_PIECES_PORT_KHAZARD, 3),
	RELLEKKA_DRAGON_BITTER_DELIVERY_130(130, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.RELLEKKA, "Rellekka dragon bitter delivery", ItemID.CARGO_CRATE_DRAGON_BITTER_RELLEKKA, 4),
	PORT_PISCARILIUS_PLATEBODY_DELIVERY_131(131, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.PORT_PISCARILIUS, "Port piscarilius platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_PORT_PISCARILIUS, 2),
	ENTRANA_SAND_DELIVERY_132(132, PortLocation.PORT_KHAZARD, PortLocation.PORT_KHAZARD, PortLocation.ENTRANA, "Entrana sand delivery", ItemID.CARGO_CRATE_SAND_ENTRANA, 3),
	PORT_KHAZARD_HERB_DELIVERY_133(133, PortLocation.PORT_KHAZARD, PortLocation.BRIMHAVEN, PortLocation.PORT_KHAZARD, "Port khazard herb delivery", ItemID.CARGO_CRATE_HERBS_PORT_KHAZARD, 2),
	PORT_KHAZARD_SCIMITAR_DELIVERY_134(134, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PORT_KHAZARD, "Port khazard scimitar delivery", ItemID.CARGO_CRATE_SCIMITARS_PORT_KHAZARD, 3),
	CORSAIR_COVE_PLATEBODY_DELIVERY_135(135, PortLocation.CORSAIR_COVE, PortLocation.PORT_KHAZARD, PortLocation.CORSAIR_COVE, "Corsair cove platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_CORSAIR_COVE, 2),
	VOID_KNIGHTS_OUTPOST_DRAGONHIDE_DELIVERY_136(136, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost dragonhide delivery", ItemID.CARGO_CRATE_DRAGONHIDE_VOID_KNIGHTS_OUTPOST, 4),
	CORSAIR_COVE_ARROWTIP_DELIVERY_137(137, PortLocation.CORSAIR_COVE, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.CORSAIR_COVE, "Corsair cove arrowtip delivery", ItemID.CARGO_CRATE_ARROWTIPS_CORSAIR_COVE, 3),
	PORT_TYRAS_HERB_DELIVERY_138(138, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PORT_TYRAS, "Port tyras herb delivery", ItemID.CARGO_CRATE_HERBS_PORT_TYRAS, 6),
	CORSAIR_COVE_MEAT_DELIVERY_139(139, PortLocation.CORSAIR_COVE, PortLocation.PORT_TYRAS, PortLocation.CORSAIR_COVE, "Corsair cove meat delivery", ItemID.CARGO_CRATE_BEAR_MEAT_CORSAIR_COVE, 5),
	PORT_KHAZARD_GUNPOWDER_DELIVERY_140(140, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PORT_KHAZARD, "Port khazard gunpowder delivery", ItemID.CARGO_CRATE_GUNPOWDER_PORT_KHAZARD, 3),
	VOID_KNIGHTS_OUTPOST_RUNE_DELIVERY_141(141, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost rune delivery", ItemID.CARGO_CRATE_WRATH_RUNES_VOID_KNIGHTS_OUTPOST, 3),
	PORT_TYRAS_SWORD_DELIVERY_142(142, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PORT_TYRAS, "Port tyras sword delivery", ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6),
	PORT_PISCARILIUS_JEWELLERY_DELIVERY_143(143, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PORT_PISCARILIUS, "Port piscarilius jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, 2),
	CORSAIR_COVE_FISH_DELIVERY_144(144, PortLocation.CORSAIR_COVE, PortLocation.PORT_PISCARILIUS, PortLocation.CORSAIR_COVE, "Corsair cove fish delivery", ItemID.CARGO_CRATE_FISH_CORSAIR_COVE, 2),
	CAIRN_ISLE_GOLD_DELIVERY_145(145, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.CAIRN_ISLE, "Cairn isle gold delivery", ItemID.CARGO_CRATE_GOLD_BARS_CAIRN_ISLE, 2),
	CORSAIR_COVE_GEM_DELIVERY_146(146, PortLocation.CORSAIR_COVE, PortLocation.CAIRN_ISLE, PortLocation.CORSAIR_COVE, "Corsair cove gem delivery", ItemID.CARGO_CRATE_GEMS_CORSAIR_COVE, 3),
	BRIMHAVEN_JEWELLERY_DELIVERY_147(147, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.BRIMHAVEN, "Brimhaven jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_BRIMHAVEN, 3),
	CORSAIR_COVE_RUM_DELIVERY_148(148, PortLocation.CORSAIR_COVE, PortLocation.BRIMHAVEN, PortLocation.CORSAIR_COVE, "Corsair cove rum delivery", ItemID.CARGO_CRATE_RUM_CORSAIR_COVE, 3),
	PANDEMONIUM_SPICE_DELIVERY_149(149, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.PANDEMONIUM, "Pandemonium spice delivery", ItemID.CARGO_CRATE_SPICES_THE_PANDEMONIUM, 3),
	CORSAIR_COVE_SHIP_PART_DELIVERY_150(150, PortLocation.CORSAIR_COVE, PortLocation.PANDEMONIUM, PortLocation.CORSAIR_COVE, "Corsair cove ship part delivery", ItemID.CARGO_CRATE_SHIP_PARTS_CORSAIR_COVE, 3),
	CIVITAS_ILLA_FORTIS_BOOK_DELIVERY_151(151, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis book delivery", ItemID.CARGO_CRATE_BOOKS_CIVITAS_ILLA_FORTIS, 2),
	ALDARIN_DAGGER_DELIVERY_152(152, PortLocation.CORSAIR_COVE, PortLocation.CORSAIR_COVE, PortLocation.ALDARIN, "Aldarin dagger delivery", ItemID.CARGO_CRATE_DAGGERS_ALDARIN, 3),
	PORT_SARIM_CACTI_DELIVERY_153(153, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_SARIM, "Port sarim cacti delivery", ItemID.CARGO_CRATE_CACTI_PORT_SARIM, 3),
	RUIN_OF_UNKAH_RUNE_DELIVERY_154(154, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_SARIM, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah rune delivery", ItemID.CARGO_CRATE_RUNES_RUINS_OF_UNKAH, 3),
	SUMMER_SHORE_SANDSTONE_DELIVERY_155(155, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.SUMMER_SHORE, "Summer shore sandstone delivery", ItemID.CARGO_CRATE_SANDSTONE_THE_SUMMER_SHORE, 2),
	RUIN_OF_UNKAH_CORAL_DELIVERY_156(156, PortLocation.RUINS_OF_UNKAH, PortLocation.SUMMER_SHORE, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah coral delivery", ItemID.CARGO_CRATE_CORAL_RUINS_OF_UNKAH, 3),
	RED_ROCK_GRANITE_DELIVERY_157(157, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.RED_ROCK, "Red rock granite delivery", ItemID.CARGO_CRATE_GRANITE_RED_ROCK, 3),
	RUIN_OF_UNKAH_PLANK_DELIVERY_158(158, PortLocation.RUINS_OF_UNKAH, PortLocation.RED_ROCK, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah plank delivery", ItemID.CARGO_CRATE_PLANKS_RUINS_OF_UNKAH, 3),
	PORT_SARIM_KEBAB_DELIVERY_159(159, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_SARIM, "Port sarim kebab delivery", ItemID.CARGO_CRATE_KEBABS_PORT_SARIM, 4),
	SUMMER_SHORE_CACTI_DELIVERY_160(160, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.SUMMER_SHORE, "Summer shore cacti delivery", ItemID.CARGO_CRATE_CACTI_THE_SUMMER_SHORE, 4),
	RED_ROCK_FISH_DELIVERY_161(161, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.RED_ROCK, "Red rock fish delivery", ItemID.CARGO_CRATE_FISH_RED_ROCK, 4),
	PANDEMONIUM_CACTI_DELIVERY_162(162, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.PANDEMONIUM, "Pandemonium cacti delivery", ItemID.CARGO_CRATE_CACTI_THE_PANDEMONIUM, 3),
	RUIN_OF_UNKAH_COCKTAIL_DELIVERY_163(163, PortLocation.RUINS_OF_UNKAH, PortLocation.PANDEMONIUM, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah cocktail delivery", ItemID.CARGO_CRATE_COCKTAILS_RUINS_OF_UNKAH, 2),
	VOID_KNIGHTS_OUTPOST_GRANITE_DELIVERY_164(164, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost granite delivery", ItemID.CARGO_CRATE_GRANITE_VOID_KNIGHTS_OUTPOST, 4),
	RUIN_OF_UNKAH_JAVELIN_DELIVERY_165(165, PortLocation.RUINS_OF_UNKAH, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah javelin delivery", ItemID.CARGO_CRATE_JAVELINS_RUINS_OF_UNKAH, 4),
	ARDOUGNE_SILK_DELIVERY_166(166, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.ARDOUGNE, "Ardougne silk delivery", ItemID.CARGO_CRATE_SILK_ARDOUGNE, 3),
	RUIN_OF_UNKAH_FISHING_SUPPLIES_DELIVERY_167(167, PortLocation.RUINS_OF_UNKAH, PortLocation.ARDOUGNE, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah fishing supplies delivery", ItemID.CARGO_CRATE_FISHING_SUPPLIES_RUINS_OF_UNKAH, 2),
	BRIMHAVEN_SANDSTONE_DELIVERY_168(168, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.BRIMHAVEN, "Brimhaven sandstone delivery", ItemID.CARGO_CRATE_SANDSTONE_BRIMHAVEN, 4),
	CATHERBY_SILK_DELIVERY_169(169, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.CATHERBY, "Catherby silk delivery", ItemID.CARGO_CRATE_SILK_CATHERBY, 2),
	DEEPFIN_POINT_GRANITE_DELIVERY_170(170, PortLocation.RUINS_OF_UNKAH, PortLocation.RUINS_OF_UNKAH, PortLocation.DEEPFIN_POINT, "Deepfin point granite delivery", ItemID.CARGO_CRATE_GRANITE_DEEPFIN_POINT, 5),
	RUIN_OF_UNKAH_SHIP_PART_DELIVERY_171(171, PortLocation.RUINS_OF_UNKAH, PortLocation.PORT_KHAZARD, PortLocation.RUINS_OF_UNKAH, "Ruin of unkah ship part delivery", ItemID.CARGO_CRATE_SHIP_PARTS_RUINS_OF_UNKAH, 2),
	RED_ROCK_RUNE_DELIVERY_172(172, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.RED_ROCK, "Red rock rune delivery", ItemID.CARGO_CRATE_RUNES_RED_ROCK, 4),
	VOID_KNIGHTS_OUTPOST_HERB_DELIVERY_173(173, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.RED_ROCK, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost herb delivery", ItemID.CARGO_CRATE_HERBS_VOID_KNIGHTS_OUTPOST, 4),
	SUMMER_SHORE_PEST_REMAINS_DELIVERY_174(174, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.SUMMER_SHORE, "Summer shore pest remains delivery", ItemID.CARGO_CRATE_PEST_REMAINS_THE_SUMMER_SHORE, 3),
	VOID_KNIGHTS_OUTPOST_LOGS_DELIVERY_175(175, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.SUMMER_SHORE, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost logs delivery", ItemID.CARGO_CRATE_LOGS_VOID_KNIGHTS_OUTPOST, 4),
	DEEPFIN_POINT_JAVELIN_DELIVERY_176(176, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.DEEPFIN_POINT, "Deepfin point javelin delivery", ItemID.CARGO_CRATE_JAVELINS_DEEPFIN_POINT, 6),
	VOID_KNIGHTS_OUTPOST_ORE_DELIVERY_177(177, PortLocation.VOID_KNIGHTS_OUTPOST, PortLocation.DEEPFIN_POINT, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost ore delivery", ItemID.CARGO_CRATE_ORES_VOID_KNIGHTS_OUTPOST, 5),
	LANDS_END_GEM_DELIVERY_241(241, PortLocation.LANDS_END, PortLocation.PRIFDDINAS, PortLocation.LANDS_END, "Land's end gem delivery", ItemID.CARGO_CRATE_GEMS_LANDS_END, 7),
	PISCATORIS_FUR_DELIVERY_242(242, PortLocation.LANDS_END, PortLocation.LANDS_END, PortLocation.PISCATORIS, "Piscatoris fur delivery", ItemID.CARGO_CRATE_FURS_PISCATORIS, 8),
	LANDS_END_FUR_DELIVERY_243(243, PortLocation.LANDS_END, PortLocation.PISCATORIS, PortLocation.LANDS_END, "Land's end fur delivery", ItemID.CARGO_CRATE_KEBBIT_FUR_LANDS_END, 8),
	DEEPFIN_POINT_LOGS_DELIVERY_244(244, PortLocation.LANDS_END, PortLocation.LANDS_END, PortLocation.DEEPFIN_POINT, "Deepfin point logs delivery", ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 5),
	PORT_KHAZARD_CHAINBODY_DELIVERY_245(245, PortLocation.LANDS_END, PortLocation.LANDS_END, PortLocation.PORT_KHAZARD, "Port khazard chainbody delivery", ItemID.CARGO_CRATE_CHAINBODIES_PORT_KHAZARD, 1),
	LUNAR_ISLE_BERRY_DELIVERY_246(246, PortLocation.LANDS_END, PortLocation.LANDS_END, PortLocation.LUNAR_ISLE, "Lunar isle berry delivery", ItemID.CARGO_CRATE_BERRIES_LUNAR_ISLE, 8),
	LANDS_END_SWORD_DELIVERY_247(247, PortLocation.LANDS_END, PortLocation.CORSAIR_COVE, PortLocation.LANDS_END, "Land's end sword delivery", ItemID.CARGO_CRATE_SWORDS_LANDS_END, 2),
	LANDS_END_FISH_DELIVERY_248(248, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.LANDS_END, "Land's end fish delivery", ItemID.CARGO_CRATE_FISH_LANDS_END, 2),
	PORT_PISCARILIUS_PLANK_DELIVERY_249(249, PortLocation.PORT_PISCARILIUS, PortLocation.LANDS_END, PortLocation.PORT_PISCARILIUS, "Port piscarilius plank delivery", ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, 1),
	PORT_ROBERTS_FISH_DELIVERY_250(250, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_ROBERTS, "Port roberts fish delivery", ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 3),
	PORT_PISCARILIUS_GIN_DELIVERY_251(251, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_ROBERTS, PortLocation.PORT_PISCARILIUS, "Port piscarilius gin delivery", ItemID.CARGO_CRATE_GIN_PORT_PISCARILIUS, 3),
	PISCATORIS_FISH_DELIVERY_252(252, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PISCATORIS, "Piscatoris fish delivery", ItemID.CARGO_CRATE_FISH_PISCATORIS, 8),
	PORT_PISCARILIUS_FUR_DELIVERY_253(253, PortLocation.PORT_PISCARILIUS, PortLocation.PISCATORIS, PortLocation.PORT_PISCARILIUS, "Port piscarilius fur delivery", ItemID.CARGO_CRATE_KEBBIT_FUR_PORT_PISCARILIUS, 8),
	LANDS_END_MEAT_DELIVERY_254(254, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.LANDS_END, "Land's end meat delivery", ItemID.CARGO_CRATE_MEAT_LANDS_END, 2),
	PORT_ROBERTS_JEWELLERY_DELIVERY_255(255, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_ROBERTS, "Port roberts jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_PORT_ROBERTS, 3),
	PISCATORIS_VODKA_DELIVERY_256(256, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PISCATORIS, "Piscatoris vodka delivery", ItemID.CARGO_CRATE_VODKA_PISCATORIS, 7),
	HOSIDIUS_FISH_DELIVERY_257(257, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.HOSIDIUS, "Hosidius fish delivery", ItemID.CARGO_CRATE_FISH_HOSIDIUS, 2),
	PORT_PISCARILIUS_SEED_DELIVERY_258(258, PortLocation.PORT_PISCARILIUS, PortLocation.HOSIDIUS, PortLocation.PORT_PISCARILIUS, "Port piscarilius seed delivery", ItemID.CARGO_CRATE_SEEDS_PORT_PISCARILIUS, 2),
	LUNAR_ISLE_FISH_DELIVERY_259(259, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.LUNAR_ISLE, "Lunar isle fish delivery", ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 7),
	PORT_PISCARILIUS_BOOK_DELIVERY_260(260, PortLocation.PORT_PISCARILIUS, PortLocation.LUNAR_ISLE, PortLocation.PORT_PISCARILIUS, "Port piscarilius book delivery", ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 8),
	PORT_SARIM_BOOK_DELIVERY_261(261, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_SARIM, "Port sarim book delivery", ItemID.CARGO_CRATE_BOOKS_PORT_SARIM, 1),
	PORT_PISCARILIUS_BOOK_DELIVERY_262(262, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_SARIM, PortLocation.PORT_PISCARILIUS, "Port piscarilius book delivery", ItemID.CARGO_CRATE_BOOKS_PORT_PISCARILIUS, 2),
	PORT_TYRAS_FUR_DELIVERY_263(263, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_TYRAS, "Port tyras fur delivery", ItemID.CARGO_CRATE_FURS_PORT_TYRAS, 5),
	MUSA_POINT_IMPORTANT_DELIVERY_264(264, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.MUSA_POINT, "Musa point important delivery", ItemID.CARGO_CRATE_HIGH_IMPORTANCE_MUSA_POINT, 2),
	RELLEKKA_BEER_DELIVERY_265(265, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_PISCARILIUS, PortLocation.RELLEKKA, "Rellekka beer delivery", ItemID.CARGO_CRATE_BEER_RELLEKKA, 5),
	PORT_PISCARILIUS_GEM_DELIVERY_266(266, PortLocation.PORT_PISCARILIUS, PortLocation.PRIFDDINAS, PortLocation.PORT_PISCARILIUS, "Port piscarilius gem delivery", ItemID.CARGO_CRATE_GEMS_PORT_PISCARILIUS, 6),
	ALDARIN_PLATEBODY_DELIVERY_267(267, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.ALDARIN, "Aldarin platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_ALDARIN, 3),
	CIVITAS_ILLA_FORTIS_ORANGE_DELIVERY_268(268, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.ALDARIN, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis orange delivery", ItemID.CARGO_CRATE_ORANGES_CIVITAS_ILLA_FORTIS, 2),
	PORT_PISCARILIUS_MEAT_DELIVERY_269(269, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_PISCARILIUS, "Port piscarilius meat delivery", ItemID.CARGO_CRATE_ANTELOPE_MEAT_PORT_PISCARILIUS, 3),
	CIVITAS_ILLA_FORTIS_VEGETABLE_DELIVERY_270(270, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_PISCARILIUS, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis vegetable delivery", ItemID.CARGO_CRATE_VEGETABLES_CIVITAS_ILLA_FORTIS, 3),
	PORT_ROBERTS_GEM_DELIVERY_271(271, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_ROBERTS, "Port roberts gem delivery", ItemID.CARGO_CRATE_GEMS_PORT_ROBERTS, 3),
	CIVITAS_ILLA_FORTIS_TOKEN_DELIVERY_272(272, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_ROBERTS, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis token delivery", ItemID.CARGO_CRATE_TOKENS_CIVITAS_ILLA_FORTIS, 4),
	ALDARIN_FUR_DELIVERY_273(273, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.ALDARIN, "Aldarin fur delivery", ItemID.CARGO_CRATE_FURS_ALDARIN, 3),
	PORT_PISCARILIUS_JEWELLERY_DELIVERY_274(274, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_PISCARILIUS, "Port piscarilius jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_PORT_PISCARILIUS, 2),
	PORT_ROBERTS_SILK_DELIVERY_275(275, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_ROBERTS, "Port roberts silk delivery", ItemID.CARGO_CRATE_SILK_PORT_ROBERTS, 4),
	DEEPFIN_POINT_WOOL_DELIVERY_276(276, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.DEEPFIN_POINT, "Deepfin point wool delivery", ItemID.CARGO_CRATE_ALPACA_WOOL_DEEPFIN_POINT, 6),
	CIVITAS_ILLA_FORTIS_ORE_DELIVERY_277(277, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.DEEPFIN_POINT, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis ore delivery", ItemID.CARGO_CRATE_ORES_CIVITAS_ILLA_FORTIS, 5),
	PRIFDDINAS_CLOTHES_DELIVERY_278(278, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PRIFDDINAS, "Prifddinas clothes delivery", ItemID.CARGO_CRATE_CLOTHES_PRIFDDINAS, 7),
	CIVITAS_ILLA_FORTIS_SEED_DELIVERY_279(279, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PRIFDDINAS, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis seed delivery", ItemID.CARGO_CRATE_SEEDS_CIVITAS_ILLA_FORTIS, 7),
	SUNSET_COAST_MACE_DELIVERY_280(280, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.SUNSET_COAST, "Sunset coast mace delivery", ItemID.CARGO_CRATE_MACES_SUNSET_COAST, 3),
	CIVITAS_ILLA_FORTIS_FISH_DELIVERY_281(281, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.SUNSET_COAST, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis fish delivery", ItemID.CARGO_CRATE_FISH_CIVITAS_ILLA_FORTIS, 2),
	PORT_SARIM_SUNBEAM_ALE_DELIVERY_282(282, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PORT_SARIM, "Port sarim sunbeam ale delivery", ItemID.CARGO_CRATE_SUNBEAM_ALE_PORT_SARIM, 2),
	PORT_TYRAS_PLATEBODY_DELIVERY_346(346, PortLocation.PORT_TYRAS, PortLocation.PORT_ROBERTS, PortLocation.PORT_TYRAS, "Port tyras platebody delivery", ItemID.CARGO_CRATE_PLATEBODIES_PORT_TYRAS, 5),
	DEEPFIN_POINT_PLANK_DELIVERY_347(347, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.DEEPFIN_POINT, "Deepfin point plank delivery", ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 6),
	PORT_TYRAS_ORE_DELIVERY_348(348, PortLocation.PORT_TYRAS, PortLocation.DEEPFIN_POINT, PortLocation.PORT_TYRAS, "Port tyras ore delivery", ItemID.CARGO_CRATE_ORES_PORT_TYRAS, 5),
	PRIFDDINAS_HALBERD_DELIVERY_349(349, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.PRIFDDINAS, "Prifddinas halberd delivery", ItemID.CARGO_CRATE_HALBERDS_PRIFDDINAS, 6),
	PORT_ROBERTS_BOW_DELIVERY_350(350, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.PORT_ROBERTS, "Port roberts bow delivery", ItemID.CARGO_CRATE_BOWS_PORT_ROBERTS, 6),
	DEEPFIN_POINT_LOGS_DELIVERY_351(351, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.DEEPFIN_POINT, "Deepfin point logs delivery", ItemID.CARGO_CRATE_LOGS_DEEPFIN_POINT, 7),
	ARDOUGNE_HALBERD_DELIVERY_352(352, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.ARDOUGNE, "Ardougne halberd delivery", ItemID.CARGO_CRATE_HALBERDS_ARDOUGNE, 5),
	PORT_TYRAS_SWORD_DELIVERY_353(353, PortLocation.PORT_TYRAS, PortLocation.ARDOUGNE, PortLocation.PORT_TYRAS, "Port tyras sword delivery", ItemID.CARGO_CRATE_SWORDS_PORT_TYRAS, 6),
	LANDS_END_FUR_DELIVERY_354(354, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.LANDS_END, "Land's end fur delivery", ItemID.CARGO_CRATE_FURS_LANDS_END, 5),
	PORT_TYRAS_SEED_DELIVERY_355(355, PortLocation.PORT_TYRAS, PortLocation.LANDS_END, PortLocation.PORT_TYRAS, "Port tyras seed delivery", ItemID.CARGO_CRATE_SEEDS_PORT_TYRAS, 5),
	PORT_PISCARILIUS_PLANK_DELIVERY_356(356, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.PORT_PISCARILIUS, "Port piscarilius plank delivery", ItemID.CARGO_CRATE_PLANKS_PORT_PISCARILIUS, 6),
	PORT_TYRAS_FISH_DELIVERY_357(357, PortLocation.PORT_TYRAS, PortLocation.PORT_PISCARILIUS, PortLocation.PORT_TYRAS, "Port tyras fish delivery", ItemID.CARGO_CRATE_FISH_PORT_TYRAS, 5),
	BRIMHAVEN_MEAT_DELIVERY_358(358, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.BRIMHAVEN, "Brimhaven meat delivery", ItemID.CARGO_CRATE_BEAR_MEAT_BRIMHAVEN, 6),
	LUNAR_ISLE_LOGS_DELIVERY_359(359, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.LUNAR_ISLE, "Lunar isle logs delivery", ItemID.CARGO_CRATE_LOGS_LUNAR_ISLE, 7),
	RED_ROCK_SHIP_PART_DELIVERY_360(360, PortLocation.PORT_TYRAS, PortLocation.PORT_TYRAS, PortLocation.RED_ROCK, "Red rock ship part delivery", ItemID.CARGO_CRATE_SHIP_PARTS_RED_ROCK, 6),
	PORT_TYRAS_FRUIT_DELIVERY_361(361, PortLocation.PORT_TYRAS, PortLocation.ALDARIN, PortLocation.PORT_TYRAS, "Port tyras fruit delivery", ItemID.CARGO_CRATE_FRUIT_PORT_TYRAS, 6),
	PORT_TYRAS_FABRIC_DELIVERY_362(362, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.PORT_TYRAS, "Port tyras fabric delivery", ItemID.CARGO_CRATE_FABRICS_PORT_TYRAS, 6),
	PRIFDDINAS_LOGS_DELIVERY_363(363, PortLocation.PRIFDDINAS, PortLocation.PORT_TYRAS, PortLocation.PRIFDDINAS, "Prifddinas logs delivery", ItemID.CARGO_CRATE_LOGS_PRIFDDINAS, 6),
	PORT_ROBERTS_LOGS_DELIVERY_364(364, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.PORT_ROBERTS, "Port roberts logs delivery", ItemID.CARGO_CRATE_LOGS_PORT_ROBERTS, 7),
	PRIFDDINAS_FISH_DELIVERY_365(365, PortLocation.PRIFDDINAS, PortLocation.PORT_ROBERTS, PortLocation.PRIFDDINAS, "Prifddinas fish delivery", ItemID.CARGO_CRATE_FISH_PRIFDDINAS, 6),
	ARDOUGNE_CRYSTAL_SEED_DELIVERY_366(366, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.ARDOUGNE, "Ardougne crystal seed delivery", ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ARDOUGNE, 7),
	PRIFDDINAS_SILK_DELIVERY_367(367, PortLocation.PRIFDDINAS, PortLocation.ARDOUGNE, PortLocation.PRIFDDINAS, "Prifddinas silk delivery", ItemID.CARGO_CRATE_SILK_PRIFDDINAS, 6),
	PORT_TYRAS_ORE_DELIVERY_368(368, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.PORT_TYRAS, "Port tyras ore delivery", ItemID.CARGO_CRATE_ORES_PORT_TYRAS, 8),
	PORT_ROBERTS_STAFF_DELIVERY_369(369, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.PORT_ROBERTS, "Port roberts staff delivery", ItemID.CARGO_CRATE_STAFFS_PORT_ROBERTS, 7),
	ARDOUGNE_JEWELLERY_DELIVERY_370(370, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.ARDOUGNE, "Ardougne jewellery delivery", ItemID.CARGO_CRATE_JEWELLERY_ARDOUGNE, 9),
	DEEPFIN_POINT_PLANK_DELIVERY_371(371, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.DEEPFIN_POINT, "Deepfin point plank delivery", ItemID.CARGO_CRATE_PLANKS_DEEPFIN_POINT, 7),
	PRIFDDINAS_ORE_DELIVERY_372(372, PortLocation.PRIFDDINAS, PortLocation.DEEPFIN_POINT, PortLocation.PRIFDDINAS, "Prifddinas ore delivery", ItemID.CARGO_CRATE_ORES_PRIFDDINAS, 6),
	ALDARIN_CRYSTAL_SEED_DELIVERY_373(373, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.ALDARIN, "Aldarin crystal seed delivery", ItemID.CARGO_CRATE_CRYSTAL_SEEDS_ALDARIN, 7),
	PRIFDDINAS_POTION_DELIVERY_374(374, PortLocation.PRIFDDINAS, PortLocation.ALDARIN, PortLocation.PRIFDDINAS, "Prifddinas potion delivery", ItemID.CARGO_CRATE_POTIONS_PRIFDDINAS, 7),
	CIVITAS_ILLA_FORTIS_STAFF_DELIVERY_375(375, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis staff delivery", ItemID.CARGO_CRATE_STAFFS_CIVITAS_ILLA_FORTIS, 6),
	PRIFDDINAS_SPICE_DELIVERY_376(376, PortLocation.PRIFDDINAS, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.PRIFDDINAS, "Prifddinas spice delivery", ItemID.CARGO_CRATE_SPICES_PRIFDDINAS, 7),
	LUNAR_ISLE_CRYSTAL_SEED_DELIVERY_377(377, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.LUNAR_ISLE, "Lunar isle crystal seed delivery", ItemID.CARGO_CRATE_CRYSTAL_SEEDS_LUNAR_ISLE, 8),
	RELLEKKA_PLANK_DELIVERY_378(378, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.RELLEKKA, "Rellekka plank delivery", ItemID.CARGO_CRATE_PLANKS_RELLEKKA, 7),
	VOID_KNIGHTS_OUTPOST_RUNE_DELIVERY_379(379, PortLocation.PRIFDDINAS, PortLocation.PRIFDDINAS, PortLocation.VOID_KNIGHTS_OUTPOST, "Void knights' outpost rune delivery", ItemID.CARGO_CRATE_RUNES_VOID_KNIGHTS_OUTPOST, 6),
	PRIFDDINAS_BOOK_DELIVERY_380(380, PortLocation.PRIFDDINAS, PortLocation.PORT_PISCARILIUS, PortLocation.PRIFDDINAS, "Prifddinas book delivery", ItemID.CARGO_CRATE_BOOKS_PRIFDDINAS, 7),
	ETCETERIA_FISH_DELIVERY_381(381, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.ECETERIA, "Etceteria fish delivery", ItemID.CARGO_CRATE_FISH_ETCETERIA, 6),
	RELLEKKA_TEAK_DELIVERY_382(382, PortLocation.RELLEKKA, PortLocation.ECETERIA, PortLocation.RELLEKKA, "Rellekka teak delivery", ItemID.CARGO_CRATE_TEAK_LOGS_RELLEKKA, 6),
	NEITIZNOT_COAL_DELIVERY_383(383, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.NEITIZNOT, "Neitiznot coal delivery", ItemID.CARGO_CRATE_COAL_NEITIZNOT, 5),
	RELLEKKA_ROPE_DELIVERY_384(384, PortLocation.RELLEKKA, PortLocation.NEITIZNOT, PortLocation.RELLEKKA, "Rellekka rope delivery", ItemID.CARGO_CRATE_ROPE_RELLEKKA, 5),
	SUNSET_COAST_WARHAMMER_DELIVERY_385(385, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.SUNSET_COAST, "Sunset coast warhammer delivery", ItemID.CARGO_CRATE_WARHAMMERS_SUNSET_COAST, 5),
	RELLEKKA_FABRIC_DELIVERY_386(386, PortLocation.RELLEKKA, PortLocation.SUNSET_COAST, PortLocation.RELLEKKA, "Rellekka fabric delivery", ItemID.CARGO_CRATE_FABRICS_RELLEKKA, 5),
	ETCETERIA_WARHAMMER_DELIVERY_387(387, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.ECETERIA, "Etceteria warhammer delivery", ItemID.CARGO_CRATE_WARHAMMERS_ETCETERIA, 7),
	NEITIZNOT_SAND_DELIVERY_388(388, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.NEITIZNOT, "Neitiznot sand delivery", ItemID.CARGO_CRATE_SAND_NEITIZNOT, 6),
	SUNSET_COAST_FISH_DELIVERY_389(389, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.SUNSET_COAST, "Sunset coast fish delivery", ItemID.CARGO_CRATE_FISH_SUNSET_COAST, 6),
	PORT_ROBERTS_FISH_DELIVERY_390(390, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.PORT_ROBERTS, "Port roberts fish delivery", ItemID.CARGO_CRATE_FISH_PORT_ROBERTS, 5),
	RELLEKKA_PLANK_DELIVERY_391(391, PortLocation.RELLEKKA, PortLocation.PORT_ROBERTS, PortLocation.RELLEKKA, "Rellekka plank delivery", ItemID.CARGO_CRATE_PLANKS_RELLEKKA, 4),
	PISCATORIS_FUR_DELIVERY_392(392, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.PISCATORIS, "Piscatoris fur delivery", ItemID.CARGO_CRATE_FURS_PISCATORIS, 8),
	RELLEKKA_MONKFISH_DELIVERY_393(393, PortLocation.RELLEKKA, PortLocation.PISCATORIS, PortLocation.RELLEKKA, "Rellekka monkfish delivery", ItemID.CARGO_CRATE_MONKFISH_RELLEKKA, 7),
	PORT_PISCARILIUS_FUR_DELIVERY_394(394, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.PORT_PISCARILIUS, "Port piscarilius fur delivery", ItemID.CARGO_CRATE_FURS_PORT_PISCARILIUS, 4),
	RELLEKKA_REDWOOD_DELIVERY_395(395, PortLocation.RELLEKKA, PortLocation.PORT_PISCARILIUS, PortLocation.RELLEKKA, "Rellekka redwood delivery", ItemID.CARGO_CRATE_REDWOOD_LOGS_RELLEKKA, 4),
	JATIZSO_LOGS_DELIVERY_396(396, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.JATIZO, "Jatizso logs delivery", ItemID.CARGO_CRATE_LOGS_JATIZSO, 5),
	RELLEKKA_ADAMANTITE_DELIVERY_397(397, PortLocation.RELLEKKA, PortLocation.JATIZO, PortLocation.RELLEKKA, "Rellekka adamantite delivery", ItemID.CARGO_CRATE_ADAMANTITE_ORE_RELLEKKA, 6),
	DEEPFIN_POINT_FUR_DELIVERY_398(398, PortLocation.RELLEKKA, PortLocation.RELLEKKA, PortLocation.DEEPFIN_POINT, "Deepfin point fur delivery", ItemID.CARGO_CRATE_FURS_DEEPFIN_POINT, 5),
	RELLEKKA_HALBERD_DELIVERY_399(399, PortLocation.RELLEKKA, PortLocation.PORT_TYRAS, PortLocation.RELLEKKA, "Rellekka halberd delivery", ItemID.CARGO_CRATE_HALBERDS_RELLEKKA, 6),
	RELLEKKA_FISH_DELIVERY_400(400, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.RELLEKKA, "Rellekka fish delivery", ItemID.CARGO_CRATE_FISH_RELLEKKA, 6),
	ETCETERIA_IRON_DELIVERY_401(401, PortLocation.ECETERIA, PortLocation.RELLEKKA, PortLocation.ECETERIA, "Etceteria iron delivery", ItemID.CARGO_CRATE_IRON_ORE_ETCETERIA, 5),
	JATIZSO_FISH_DELIVERY_402(402, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.JATIZO, "Jatizso fish delivery", ItemID.CARGO_CRATE_FISH_JATIZSO, 5),
	ETCETERIA_ADAMANTITE_DELIVERY_403(403, PortLocation.ECETERIA, PortLocation.JATIZO, PortLocation.ECETERIA, "Etceteria adamantite delivery", ItemID.CARGO_CRATE_ADAMANTITE_ORE_ETCETERIA, 6),
	PORT_ROBERTS_TEAK_DELIVERY_404(404, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.PORT_ROBERTS, "Port roberts teak delivery", ItemID.CARGO_CRATE_TEAK_LOGS_PORT_ROBERTS, 5),
	ETCETERIA_FRUIT_DELIVERY_405(405, PortLocation.ECETERIA, PortLocation.PORT_ROBERTS, PortLocation.ECETERIA, "Etceteria fruit delivery", ItemID.CARGO_CRATE_FRUIT_ETCETERIA, 5),
	RELLEKKA_TEAK_DELIVERY_406(406, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.RELLEKKA, "Rellekka teak delivery", ItemID.CARGO_CRATE_TEAK_LOGS_RELLEKKA, 7),
	JATIZSO_FLAX_DELIVERY_407(407, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.JATIZO, "Jatizso flax delivery", ItemID.CARGO_CRATE_FLAX_JATIZSO, 7),
	PORT_ROBERTS_FLAX_DELIVERY_408(408, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.PORT_ROBERTS, "Port roberts flax delivery", ItemID.CARGO_CRATE_FLAX_PORT_ROBERTS, 6),
	PORT_PISCARILIUS_MAHOGANY_DELIVERY_409(409, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.PORT_PISCARILIUS, "Port piscarilius mahogany delivery", ItemID.CARGO_CRATE_MAHOGANY_LOGS_PORT_PISCARILIUS, 5),
	ETCETERIA_PLANK_DELIVERY_410(410, PortLocation.ECETERIA, PortLocation.PORT_PISCARILIUS, PortLocation.ECETERIA, "Etceteria plank delivery", ItemID.CARGO_CRATE_PLANKS_ETCETERIA, 6),
	NEITIZNOT_MAHOGANY_DELIVERY_411(411, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.NEITIZNOT, "Neitiznot mahogany delivery", ItemID.CARGO_CRATE_MAHOGANY_LOGS_NEITIZNOT, 6),
	ETCETERIA_YAK_HAIR_DELIVERY_412(412, PortLocation.ECETERIA, PortLocation.NEITIZNOT, PortLocation.ECETERIA, "Etceteria yak hair delivery", ItemID.CARGO_CRATE_YAK_HAIR_ETCETERIA, 5),
	SUNSET_COAST_FABRIC_DELIVERY_413(413, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.SUNSET_COAST, "Sunset coast fabric delivery", ItemID.CARGO_CRATE_FABRICS_SUNSET_COAST, 5),
	ETCETERIA_SWORD_DELIVERY_414(414, PortLocation.ECETERIA, PortLocation.SUNSET_COAST, PortLocation.ECETERIA, "Etceteria sword delivery", ItemID.CARGO_CRATE_SWORDS_ETCETERIA, 5),
	PISCATORIS_FLAX_DELIVERY_415(415, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.PISCATORIS, "Piscatoris flax delivery", ItemID.CARGO_CRATE_FLAX_PISCATORIS, 8),
	ETCETERIA_MONKFISH_DELIVERY_416(416, PortLocation.ECETERIA, PortLocation.PISCATORIS, PortLocation.ECETERIA, "Etceteria monkfish delivery", ItemID.CARGO_CRATE_MONKFISH_ETCETERIA, 9),
	DEEPFIN_POINT_MAHOGANY_DELIVERY_417(417, PortLocation.ECETERIA, PortLocation.ECETERIA, PortLocation.DEEPFIN_POINT, "Deepfin point mahogany delivery", ItemID.CARGO_CRATE_MAHOGANY_LOGS_DEEPFIN_POINT, 6),
	ETCETERIA_ONION_DELIVERY_418(418, PortLocation.ECETERIA, PortLocation.HOSIDIUS, PortLocation.ECETERIA, "Etceteria onion delivery", ItemID.CARGO_CRATE_ONIONS_ETCETERIA, 5),
	PORT_PISCARILIUS_FABRIC_DELIVERY_419(419, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PORT_PISCARILIUS, "Port piscarilius fabric delivery", ItemID.CARGO_CRATE_FABRICS_PORT_PISCARILIUS, 7),
	LUNAR_ISLE_FISH_DELIVERY_420(420, PortLocation.LUNAR_ISLE, PortLocation.PORT_PISCARILIUS, PortLocation.LUNAR_ISLE, "Lunar isle fish delivery", ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 8),
	PISCATORIS_FABRIC_DELIVERY_421(421, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PISCATORIS, "Piscatoris fabric delivery", ItemID.CARGO_CRATE_FABRICS_PISCATORIS, 8),
	LUNAR_ISLE_FUR_DELIVERY_422(422, PortLocation.LUNAR_ISLE, PortLocation.PISCATORIS, PortLocation.LUNAR_ISLE, "Lunar isle fur delivery", ItemID.CARGO_CRATE_KEBBIT_FUR_LUNAR_ISLE, 8),
	PRIFDDINAS_HERB_DELIVERY_423(423, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PRIFDDINAS, "Prifddinas herb delivery", ItemID.CARGO_CRATE_HERBS_PRIFDDINAS, 8),
	LUNAR_ISLE_POTION_DELIVERY_424(424, PortLocation.LUNAR_ISLE, PortLocation.PRIFDDINAS, PortLocation.LUNAR_ISLE, "Lunar isle potion delivery", ItemID.CARGO_CRATE_POTIONS_LUNAR_ISLE, 8),
	PORT_PISCARILIUS_RUNE_DELIVERY_425(425, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PORT_PISCARILIUS, "Port piscarilius rune delivery", ItemID.CARGO_CRATE_ASTRAL_RUNES_PORT_PISCARILIUS, 9),
	PISCATORIS_POTION_DELIVERY_426(426, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PISCATORIS, "Piscatoris potion delivery", ItemID.CARGO_CRATE_POTIONS_PISCATORIS, 8),
	PRIFDDINAS_RUNE_DELIVERY_427(427, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PRIFDDINAS, "Prifddinas rune delivery", ItemID.CARGO_CRATE_ASTRAL_RUNES_PRIFDDINAS, 9),
	DEEPFIN_POINT_SUQAH_HIDE_DELIVERY_428(428, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.DEEPFIN_POINT, "Deepfin point suqah hide delivery", ItemID.CARGO_CRATE_SUQAH_HIDES_DEEPFIN_POINT, 8),
	LUNAR_ISLE_COAL_DELIVERY_429(429, PortLocation.LUNAR_ISLE, PortLocation.DEEPFIN_POINT, PortLocation.LUNAR_ISLE, "Lunar isle coal delivery", ItemID.CARGO_CRATE_COAL_LUNAR_ISLE, 7),
	PORT_ROBERTS_FABRIC_DELIVERY_430(430, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.PORT_ROBERTS, "Port roberts fabric delivery", ItemID.CARGO_CRATE_FABRICS_PORT_ROBERTS, 7),
	LUNAR_ISLE_FISH_DELIVERY_431(431, PortLocation.LUNAR_ISLE, PortLocation.PORT_ROBERTS, PortLocation.LUNAR_ISLE, "Lunar isle fish delivery", ItemID.CARGO_CRATE_FISH_LUNAR_ISLE, 7),
	CIVITAS_ILLA_FORTIS_RUNE_DELIVERY_432(432, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.CIVITAS_ILLA_FORTIS, "Civitas illa fortis rune delivery", ItemID.CARGO_CRATE_ASTRAL_RUNES_CIVITAS_ILLA_FORTIS, 8),
	LUNAR_ISLE_FUR_DELIVERY_433(433, PortLocation.LUNAR_ISLE, PortLocation.CIVITAS_ILLA_FORTIS, PortLocation.LUNAR_ISLE, "Lunar isle fur delivery", ItemID.CARGO_CRATE_ANTELOPE_FUR_LUNAR_ISLE, 7),
	RED_ROCK_RUNE_DELIVERY_434(434, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.RED_ROCK, "Red rock rune delivery", ItemID.CARGO_CRATE_ASTRAL_RUNES_RED_ROCK, 8),
	LUNAR_ISLE_RED_CORAL_DELIVERY_435(435, PortLocation.LUNAR_ISLE, PortLocation.RED_ROCK, PortLocation.LUNAR_ISLE, "Lunar isle red coral delivery", ItemID.CARGO_CRATE_RED_CORAL_LUNAR_ISLE, 8),
	LANDS_END_GEM_DELIVERY_436(436, PortLocation.LUNAR_ISLE, PortLocation.LUNAR_ISLE, PortLocation.LANDS_END, "Land's end gem delivery", ItemID.CARGO_CRATE_GEMS_LANDS_END, 9),
	LUNAR_ISLE_POTION_DELIVERY_437(437, PortLocation.LUNAR_ISLE, PortLocation.ALDARIN, PortLocation.LUNAR_ISLE, "Lunar isle potion delivery", ItemID.CARGO_CRATE_POTIONS_LUNAR_ISLE, 8),
	;
	private final int id;
	private final PortLocation noticeBoard;
	private final PortLocation cargoLocation;
	private final PortLocation deliveryLocation;
	public final PortPaths dockMarkers;
	public final boolean reversePath;
	public final String taskName;
	public final int cargo;
	public final int cargoAmount;

	PortTaskData(Integer id, PortLocation noticeBoard, PortLocation cargoLocation, PortLocation deliveryLocation, PortPaths dockMarkers, boolean reversePath, String taskName, int cargo, int cargoAmount)
	{
		this.id = id;
		this.noticeBoard = noticeBoard;
		this.cargoLocation = cargoLocation;
		this.deliveryLocation = deliveryLocation;
		this.dockMarkers = dockMarkers;
		this.reversePath = reversePath;
		this.taskName = taskName;
		this.cargo = cargo;
		this.cargoAmount = cargoAmount;
	}

	PortTaskData(Integer id, PortLocation noticeBoard, PortLocation cargoLocation, PortLocation deliveryLocation, String taskName, int cargo, int cargoAmount)
	{
		this(id, noticeBoard, cargoLocation, deliveryLocation, null, false, taskName, cargo, cargoAmount);
	}

	public PortLocation getCargoLocation()
	{
		return cargoLocation;
	}

	public PortLocation getDeliveryLocation()
	{
		return deliveryLocation;
	}

	public PortLocation getNoticeBoard()
	{
		return noticeBoard;
	}

	public static PortTaskData fromId(int id)
	{
		for (PortTaskData task : values())
		{
			if (task.id == id)
				return task;
		}
		return null;
	}

	public int getCargoAmount()
	{
		return this.cargoAmount;
	}

}

